sfdx-source/SmartVisca/main/default/objects/NameCardRenkeiJyoken__c/NameCardRenkeiJyoken__c.object-meta.xml
<CustomObject>
    <label>名刺自動連携条件設定</label>
    <nameField>
        <displayFormat>RC-{000000}</displayFormat>
        <label>連携設定</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/SmartVisca/main/default/objects/NameCardRenkeiJyoken__c/fields/NameCardDataType__c.field-meta.xml
<CustomField>
    <fullName>NameCardDataType__c</fullName>
    <label>名刺の項目(データ型)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>String</fullName>
            </value>
            <value>
                <fullName>Boolean</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Double</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Url</fullName>
            </value>
            <value>
                <fullName>Textarea</fullName>
            </value>
            <value>
                <fullName>Datetime</fullName>
            </value>
            <value>
                <fullName>Integer</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
                <isActive>false</isActive>
                <label>Number</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardRenkeiJyoken__c/fields/NameCardName__c.field-meta.xml
<CustomField>
    <fullName>NameCardName__c</fullName>
    <label>名刺の項目(API名称)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardRenkeiJyoken__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <label>演算子</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Matches_next_character_string</fullName>
            </value>
            <value>
                <fullName>Does_not_match_next_character_string</fullName>
            </value>
            <value>
                <fullName>Start_with_the_following_string</fullName>
            </value>
            <value>
                <fullName>Contains_the_following_character_string</fullName>
            </value>
            <value>
                <fullName>Not_contain_the_following_character_string</fullName>
            </value>
            <value>
                <fullName>Matches_the_following_regular_expression</fullName>
            </value>
            <value>
                <fullName>＜</fullName>
            </value>
            <value>
                <fullName>＞</fullName>
            </value>
            <value>
                <fullName>＜＝</fullName>
            </value>
            <value>
                <fullName>＞＝</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardRenkeiJyoken__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>値</label>
    <type>TextArea</type>
</CustomField>

sfdx-source/SmartVisca/main/default/classes/SB_NameCard_NameCardRenkeiJyokenDTOTest.cls
/**
 *
 * SB_NameCard_NameCardRenkeiJyokenDTOTest
 * SB_NameCard_NameCardRenkeiJyokenDTOのテストクラス
 *
 *
 *
 *  Copyright (C) 2017 SunBridge Inc. All Rights Reserved.
 *
 *  @author mao
 *  @Version 1.20      2017.02.XX
 *
 **/
@isTest
private class SB_NameCard_NameCardRenkeiJyokenDTOTest {

  //NameCardRenkeiJyoken__c -> bin
  @isTest static void test_Bind() {
    NameCardRenkeiJyoken__c jyo = new NameCardRenkeiJyoken__c();
    jyo.Operator__c = 'test';
    jyo.NameCardName__c = 'Name';
    jyo.NameCardDataType__c = 'STRING';
    jyo.Value__c = 'testdata';
    SB_NameCard_NameCardRenkeiJyokenDTO dto = new SB_NameCard_NameCardRenkeiJyokenDTO();
    dto.bind(jyo);
    System.assertEquals(dto.Operator,'test');
    System.assertEquals(dto.NameCardName,'Name');
    System.assertEquals(dto.NameCardDataType,'STRING');
    System.assertEquals(dto.Value,'testdata');
  }

  //bin -> NameCardRenkeiJyoken__c
  @isTest static void test_DeBind() {
    NameCardRenkeiJyoken__c jyo = new NameCardRenkeiJyoken__c();
    jyo.Operator__c = 'test';
    jyo.NameCardName__c = 'Name';
    jyo.NameCardDataType__c = 'STRING';
    jyo.Value__c = 'testdata';
    SB_NameCard_NameCardRenkeiJyokenDTO dto = new SB_NameCard_NameCardRenkeiJyokenDTO();
    dto.bind(jyo);
    NameCardRenkeiJyoken__c dto2 = dto.debind();
    System.assertEquals(dto2.Operator__c,'test');
    System.assertEquals(dto2.NameCardName__c,'Name');
    System.assertEquals(dto2.NameCardDataType__c,'STRING');
    System.assertEquals(dto2.Value__c,'testdata');
  }

}