sfdx-source/SmartVisca/main/default/objects/JinjiIdo__c/JinjiIdo__c.object-meta.xml
<CustomObject>
    <description>オプション：人事異動の案内があるとここに保存されます。
Option:Stores personnel change information.</description>
    <label>人事異動情報</label>
    <nameField>
        <label>人事異動情報名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/SmartVisca/main/default/objects/JinjiIdo__c/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <label>会社名</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/JinjiIdo__c/fields/AnnounceDate__c.field-meta.xml
<CustomField>
    <fullName>AnnounceDate__c</fullName>
    <label>発令日</label>
    <type>Date</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/JinjiIdo__c/fields/ContactName__c.field-meta.xml
<CustomField>
    <fullName>ContactName__c</fullName>
    <label>氏名</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/JinjiIdo__c/fields/PrintedDate__c.field-meta.xml
<CustomField>
    <fullName>PrintedDate__c</fullName>
    <label>掲載日</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

sfdx-source/SmartVisca/main/default/classes/SB_NameCard_JinjiIdoEmailNoticeBatchTest.cls
/*
 * Copyright (c) 2014 SunBridge Inc.
 *
 * 日経テレコン人事異動情報 WSI API メール通知バッチ テストクラス
 *
 * @author fukui@sunbridge.com
 * @since 2014-11-28
 *
 * @Version 1 kou 2017.10.xx No Assert v1.21 for code scan
 */
@isTest
private class SB_NameCard_JinjiIdoEmailNoticeBatchTest {

    static testMethod void test() {
        JinjiIdo__c ji = new JinjiIdo__c();
        ji.name = '人事異動情報１';
        ji.ContactName__c = 'テスト姓名';
        ji.AccountName__c = '株式会社サンブリッジ';
        ji.PrintedDate__c = Date.today().addDays(-40);  // 掲載日
        ji.AnnounceDate__c = Date.today().addDays(-30); // 発令日
        insert ji;
        Test.startTest();
        // バッチ処理スケジュール
        String jobId = System.schedule('test_batch',
                        '0 0 0 31 12 ? 2024',
                        new SB_NameCard_JinjiIdoEmailNoticeBatch());
        Test.stopTest();

        System.assert(String.isNotBlank(jobId));
    }
}