sfdx-source/SmartVisca/main/default/objects/JinjiIdo__c/JinjiIdo__c.object-meta.xml
<CustomObject>
    <description>オプション：人事異動の案内があるとここに保存されます。
Option:Stores personnel change information.</description>
    <label>人事異動情報</label>
    <nameField>
        <label>人事異動情報名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/SmartVisca/main/default/objects/JinjiIdo__c/fields/NameCard__c.field-meta.xml
<CustomField>
    <fullName>NameCard__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>名刺</label>
    <referenceTo>NameCard__c</referenceTo>
    <relationshipLabel>人事異動情報</relationshipLabel>
    <relationshipName>NameCardJinjiIdos</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/JinjiIdoEmail__c/JinjiIdoEmail__c.object-meta.xml
<CustomObject>
    <description>オプション：人事異動情報の通知メールを登録
Option:Stores personnel change information alert mail.</description>
    <label>人事異動情報メール通知</label>
    <nameField>
        <label>人事異動情報メール通知名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/unpackaged/dev-config/main/default/objects/NameCard__c/NameCard__c.object-meta.xml
<CustomObject>
    <customHelpPage>SB_NameCard_UserGuide</customHelpPage>
    <description>スキャナから取り込んだ名刺情報がここに保存されます。
Business Card: Stores digitized business card information.</description>
    <label>名刺</label>
    <nameField>
        <label>氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/SmartVisca/main/default/objects/NameCardHistory__c/NameCardHistory__c.object-meta.xml
<CustomObject>
    <description>名刺オブジェクトへのステータス変更履歴を登録
Business Card History: Stores updating business card data status.</description>
    <label>名刺履歴</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>名刺履歴No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/SmartVisca/main/default/objects/NameCardHistory__c/fields/NameCard__c.field-meta.xml
<CustomField>
    <fullName>NameCard__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>名刺オブジェクトID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardRenkeiJyoken__c/NameCardRenkeiJyoken__c.object-meta.xml
<CustomObject>
    <label>名刺自動連携条件設定</label>
    <nameField>
        <displayFormat>RC-{000000}</displayFormat>
        <label>連携設定</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/SmartVisca/main/default/objects/NameCardRenkeiMapping__c/NameCardRenkeiMapping__c.object-meta.xml
<CustomObject>
    <label>名刺連携項目マッピング</label>
    <nameField>
        <displayFormat>RM-{000000}</displayFormat>
        <label>名刺連携項目マッピングNo</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/SmartVisca/main/default/objects/NameCardSettingValues__c/NameCardSettingValues__c.object-meta.xml
<CustomObject>
    <label>名刺設定値</label>
    <nameField>
        <displayFormat>NCSV-{00000}</displayFormat>
        <label>名刺設定値名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/SmartViscaf__SmartViscaConfig__c.object
<CustomObject>
    <fields>
        <fullName>RenkeiContactToCampaignMember__c</fullName>
        <defaultValue>false</defaultValue>
        <description>リード用自動連携:キャンペーンIDが指定されていたとき、（作成、あるいは更新したとき）リードに加え取引先責任者もキャンペーンメンバーにする。</description>
        <inlineHelpText>リード用自動連携:キャンペーンIDが指定されていたとき、（作成、あるいは更新したとき）リードに加え取引先責任者もキャンペーンメンバーにする。</inlineHelpText>
        <label>リード用自動連携:取引先責任者もキャンペーンメンバーにする</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RenkeiCreateContactOnAcountWithLead__c</fullName>
        <defaultValue>false</defaultValue>
        <description>リード用自動連携:リードと取引先が既存で取引先が特定できて取引先責任者レコードがない場合、取引先責任者を作成する。</description>
        <inlineHelpText>リード用自動連携:リードと取引先が既存で取引先が特定できて取引先責任者レコードがない場合、取引先責任者を作成する。</inlineHelpText>
        <label>リード用自動連携:リード、取引先既存で取引先責任者を作成する【移行済】</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RenkeiCreateContactOnAcountWithoutLead__c</fullName>
        <defaultValue>false</defaultValue>
        <description>リード用自動連携:該当するリードはなく、取引先が既存で取引先が特定できて取引先責任者レコードがない場合、取引先責任者を作成する。このときリードは作らない。</description>
        <inlineHelpText>リード用自動連携:該当するリードはなく、取引先が既存で取引先が特定できて取引先責任者レコードがない場合、取引先責任者を作成する。このときリードは作らない。</inlineHelpText>
        <label>リード用自動連携:リードなく、取引先既存で取引先責任者を作成する【移行済】</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RenkeiCreateLeadOnTooManyAccounts__c</fullName>
        <defaultValue>false</defaultValue>
        <description>リード用自動連携:名刺に合致する既存の取引先が複数あり特定できないとき、リードを作る。</description>
        <inlineHelpText>リード用自動連携:名刺に合致する既存の取引先が複数あり特定できないとき、リードを作る。</inlineHelpText>
        <label>リード用自動連携:既存取引先が複数あり特定できないとき、リードを作る【移行済】</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RenkeiUpdateAllLeadsOnCondition__c</fullName>
        <defaultValue>false</defaultValue>
        <description>リード用自動連携:（上書き設定時）該当するリード複数を更新する。オフの場合、該当するリードが複数あったときは更新しない。</description>
        <inlineHelpText>リード用自動連携:（上書き設定時）該当するリード複数を更新する。オフの場合、該当するリードが複数あったときは更新しない。</inlineHelpText>
        <label>リード用自動連携:条件に合致する既存リードは全て更新する【移行済】</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RenkeiUpdateToCampaignMember__c</fullName>
        <defaultValue>false</defaultValue>
        <description>リード用自動連携:キャンペーンIDが指定されていたとき、作成に加え更新でもキャンペーンメンバーにする。</description>
        <inlineHelpText>リード用自動連携:キャンペーンIDが指定されていたとき、作成に加え更新でもキャンペーンメンバーにする。</inlineHelpText>
        <label>リード用自動連携:更新でもキャンペーンメンバーにする</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SRegistQueryLeadFields1__c</fullName>
        <defaultValue>&quot;Company:2, Title:2, Email:2, PostalCode, State, City, Street&quot;</defaultValue>
        <description>Id,Name以外の画面に表示するリード項目の API名:数値 をカンマ区切りで指定してください。 
数値 は、 
・1はリストにのみ表示 
・2はリストとポップアップに表示 
・3はポップアップにのみ表示 
リスト、ポップアップともに記載順に表示します。</description>
        <inlineHelpText>Id,Name以外の画面に表示するリード項目の API名:数値 をカンマ区切りで指定してください。 
数値 は、 
・1はリストにのみ表示 
・2はリストとポップアップに表示 
・3はポップアップにのみ表示 
リスト、ポップアップともに記載順に表示します。</inlineHelpText>
        <label>Sリード登録時表示するリードの項目1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/SB_NameCardL_Util.cls
/**
 *
 *  SB_NameCardL_Util
 *  ユーティリティ クラス
 *
 *  @author sawano
 *  @Version 1    2017.12.xx
 *
 *  Lead拡張パッケージ用縮小バージョン
 *
 * Copyright (c) 2011-2018 SunBridge Inc.
 *
 **/
public with sharing class SB_NameCardL_Util {

  // 活動状況の選択肢を取得, キーは 'Completed' か 'NotStarted' のみ有効
  public static Map<String, String> taskStatusValues {
    get {
      if (taskStatusValues == null) {
        taskStatusValues = new Map<String, String>();
        List<TaskStatus> taskstatuses = [ SELECT IsClosed, IsDefault, MasterLabel, SortOrder FROM TaskStatus ORDER BY SortOrder ];
        for (TaskStatus ts : taskstatuses) {
          if (ts.isClosed && ! taskStatusValues.containsKey('Completed')) {
            taskStatusValues.put('Completed', ts.MasterLabel);
          } else if (ts.isDefault && ! taskStatusValues.containsKey('NotStarted')) {
             taskStatusValues.put('NotStarted', ts.MasterLabel);
          }
        }
        if (! taskStatusValues.containsKey('Completed')) {
          taskStatusValues.put('Completed', System.Label.SB_NCL_Completed);
        } else if (! taskStatusValues.containsKey('NotStarted')) {
          taskStatusValues.put('NotStarted', System.Label.SB_NCL_NotStarted);
        }
      }
      return taskStatusValues;
    }
  }

  //// SOQLで 部分一致検索 するときは、これを通した文字列を使う
  //public static String getStringForPartialMatch(String str) {
  //  if (String.isBlank(str)) {
  //    return str;
  //  }
  //  //アポストロフィーがある場合、escapeSingleQuotesメソッドがエスケープされるはずですが、
  //  //なぜかうまくエスケープできてないので、エスケープする前にアポストロフィーをbase64を使って暗号化して、エスケープ後に元に戻す
  //  String result;
  //  Blob b = Blob.valueOf(EncodingUtil.urlEncode(str, 'UTF-8'));
  //  String b64 = EncodingUtil.base64Encode(b);
  //  result = str.replaceAll('\'',b64);
  //  result = String.escapeSingleQuotes(result.replaceAll('＼', '_'));
  //  result = result.replaceAll(b64,'\'');
  //  return result;
  //}

  // 取引先・取引先責任者登録 の 取引先の表示項目設定
  private static final String REGIST_ACCOUNT_QUERYFIELD = 'BillingPostalCode, BillingState:2, BillingCity, BillingStreet, Site:2';
  // 取引先・取引先責任者登録 の 取引先責任者の表示項目設定
  private static final String REGIST_CONTACT_QUERYFIELD = 'Department:2, Title:2, Email:2, MailingPostalCode, MailingState, MailingCity, MailingStreet';
  // 取引先・取引先責任者登録 の 取引先責任者の表示項目設定
  private static final String REGIST_LEAD_QUERYFIELD = 'Company:2, Title:2, Email:2, PostalCode, State, City, Street';

  public static SmartViscaf__SmartViscaConfig__c smartViscaConfig {
    get {
      if (smartViscaConfig == null) {
        smartViscaConfig = SmartViscaf__SmartViscaConfig__c.getInstance(UserInfo.getUserId());   //  個人の設定
        if (smartViscaConfig.Id ==null) {
          smartViscaConfig =  SmartViscaf__SmartViscaConfig__c.getInstance(UserInfo.getProfileId());   //プロファイルの設定
        }
        if (smartViscaConfig.id == null) {
          smartViscaConfig = SmartViscaf__SmartViscaConfig__c.getOrgDefaults();    // 組織の設定
        }
        if (smartViscaConfig.id == null) {
        }
        // 統合版自動連携:リードなく、取引先既存で取引先責任者を作成する
        smartViscaConfig.RenkeiCreateContactOnAcountWithoutLead__c = smartViscaConfig.RenkeiCreateContactOnAcountWithoutLead__c == null ? false : smartViscaConfig.RenkeiCreateContactOnAcountWithoutLead__c;
        // 統合版自動連携:リード、取引先既存で取引先責任者を作成する
        smartViscaConfig.RenkeiCreateContactOnAcountWithLead__c = smartViscaConfig.RenkeiCreateContactOnAcountWithLead__c == null ? false : smartViscaConfig.RenkeiCreateContactOnAcountWithLead__c;
        // 統合版自動連携: 既存取引先が複数あり特定できないとき、リードを作る。
        smartViscaConfig.RenkeiCreateLeadOnTooManyAccounts__c = smartViscaConfig.RenkeiCreateLeadOnTooManyAccounts__c == null ? false : smartViscaConfig.RenkeiCreateLeadOnTooManyAccounts__c;
        // 統合版自動連携: 取引先責任者もキャンペーンメンバーにする。
        smartViscaConfig.RenkeiContactToCampaignMember__c = smartViscaConfig.RenkeiContactToCampaignMember__c == null ? false : smartViscaConfig.RenkeiContactToCampaignMember__c;
        // 統合版自動連携: 更新でもキャンペーンメンバーにする。
        smartViscaConfig.RenkeiUpdateToCampaignMember__c = smartViscaConfig.RenkeiUpdateToCampaignMember__c == null ? false : smartViscaConfig.RenkeiUpdateToCampaignMember__c;
        // 統合版自動連携:条件に合致する既存リードは全て更新する。
        smartViscaConfig.RenkeiUpdateAllLeadsOnCondition__c = smartViscaConfig.RenkeiUpdateAllLeadsOnCondition__c == null ? true : smartViscaConfig.RenkeiUpdateAllLeadsOnCondition__c;

        // LEX版 CRM登録* 個別 関連
        // CRMに登録 の 取引先の表示項目設定
        smartViscaConfig.SmartViscaf__SRegistQueryAccountFields1__c = String.isBlank(smartViscaConfig.SmartViscaf__SRegistQueryAccountFields1__c) ?
        REGIST_ACCOUNT_QUERYFIELD : smartViscaConfig.SmartViscaf__SRegistQueryAccountFields1__c;
        // CRMに登録 の 取引先責任者の表示項目設定
        smartViscaConfig.SmartViscaf__SRegistQueryContactFields1__c = String.isBlank(smartViscaConfig.SmartViscaf__SRegistQueryContactFields1__c) ?
        REGIST_CONTACT_QUERYFIELD : smartViscaConfig.SmartViscaf__SRegistQueryContactFields1__c;
        // CRMに登録 の リードの表示項目設定
        smartViscaConfig.SRegistQueryLeadFields1__c = String.isBlank(smartViscaConfig.SRegistQueryLeadFields1__c) ?
        REGIST_LEAD_QUERYFIELD : smartViscaConfig.SRegistQueryLeadFields1__c;

      }
      return smartViscaConfig;
    }
  }

  public static String getNamespacePrefix_x() { return String.isEmpty(namespacePrefix) ? '' : namespacePrefix+'__'; }
  public static String getNamespacePrefix() { return namespacePrefix; }
  private static String namespacePrefix {
    get {
      if (namespacePrefix ==null) {
        List<ApexClass> classes = [SELECT Name, NamespacePrefix FROM ApexClass WHERE Name='SB_NameCardL_Util'];
        if (classes.size() == 1) { // 別のパッケージで SB_NameCard_Utilを持ってる場合に対処 2018.08.xx
          namespacePrefix = classes[0].NamespacePrefix != null ? classes[0].NamespacePrefix : '';
        }
        else if (classes.size() > 1) {
           namespacePrefix = 'SmartViscal';
        }
        else {
          namespacePrefix = '';
        }
      }
      return namespacePrefix;
    }
    private set;
  }


  // キャンペーンの状況のデフォルト
  public static String getDefaultCampaignStatus() {
    String result;
    List<String> statuss = new List<String>();
    Schema.DescribeFieldResult F = Campaign.Status.getDescribe();
    List<Schema.PicklistEntry> P = F.getPicklistValues();
    for (Schema.PicklistEntry ent : P) {
      if (ent.isActive()) {
        statuss.add(ent.getLabel());
        System.debug('active item : ' + ent.getLabel());
      }
      else {
        System.debug('inactive item : ' + ent.getLabel());
      }
      if (ent.isDefaultValue()) {
        result = ent.getLabel();
        System.debug('Default item : ' + ent.getLabel());
      }
    }
    return result;
  }

  //オブジェクトでフォールトのレコードタイプIDを取得
  public static String getDefaultRecordType(SObjectType otype){
    String recordTypeId;
    List<Schema.RecordTypeInfo> rs =  otype.getDescribe().getRecordTypeInfos();
    for (RecordTypeInfo r : rs) {
        if (r.isDefaultRecordTypeMapping() && r.isAvailable() && !r.isMaster()) {
             recordTypeId = r.getRecordTypeId();
        }
    }
    return recordTypeId;
  }

  //レコードタイプを取得
  public static List<RecordTypeInfo> getRecordType(SObjectType otype){
    List<Schema.RecordTypeInfo> rs =  otype.getDescribe().getRecordTypeInfos();
    List<RecordTypeInfo> recordtypes = new List<RecordTypeInfo>();
    for (RecordTypeInfo r : rs) {
      if (r.isAvailable()) {
        recordtypes.add(r);
      }
    }
    //isMasterメソード使えるにはWinter'16　APIバージョン35.0以降でなければならない、
    //そのため、今最後のレコードタイプMasterをリストから削除します
    if (recordtypes.size()>0) {
      recordtypes.remove(recordtypes.size()-1);
    }
    return recordtypes;
  }

  //
  @TestVisible
  private static final Set<String> SV_OBJECT_NAMES = new Set<String> {
    'namecard__c',  // 名刺
    'namecardhistory__c', // 名刺履歴
    'namecardrenkeimapping__c', // 名刺連携項目マッピング
    'jinjiido__c',  // 人事異動情報
    'jinjiidoemail__c', // 人事異動情報メール通知
    'namecardbasicsetting',  // 名刺基本設定
    'namecardsettingvalues__c',  // 名刺設定値
    'namecardrenkeijyoken__c'  // 名刺自動連携条件設定
  };

  public static String getManagedObjectName(String oName) {
    String result = oName;
    if (SV_OBJECT_NAMES.contains(oName.toLowerCase())) {
      String ns = SB_NameCardL_Util.getNamespacePrefix_x();
      result = ns + oName;
    }
    return result;
  }

  // SOSL の予約語をエスケープする。 2016.10.xx
  private static final String SOSL_YOYAKUGO = '?&|!{}[]()^~*:"\'+-\\';
  public static String escapeSOSLYoyakugo(String text) {
    if (!text.containsAny(SOSL_YOYAKUGO)) {
      return text;
    }
    String result = text;
    result = result.replace('\\', '\\\\');
    result = result.replace('?', '\\?');
    result = result.replace('&', '\\&');
    result = result.replace('|', '\\|');
    result = result.replace('!', '\\!');
    result = result.replace('{', '\\{');
    result = result.replace('}', '\\}');
    result = result.replace('[', '\\[');
    result = result.replace(']', '\\]');
    result = result.replace('(', '\\(');
    result = result.replace(')', '\\)');
    result = result.replace('^', '\\^');
    result = result.replace('~', '\\~');
    result = result.replace('*', '\\*');
    result = result.replace(':', '\\:');
    result = result.replace('"', '\\"');
    result = result.replace('\'', '\\\'');
    result = result.replace('+', '\\+');
    result = result.replace('-', '\\-');
    System.debug(result);
    return result;
  }



}