sfdx-source/unpackaged/dev-config/main/default/objects/NameCard__c/NameCard__c.object-meta.xml
<CustomObject>
    <customHelpPage>SB_NameCard_UserGuide</customHelpPage>
    <description>スキャナから取り込んだ名刺情報がここに保存されます。
Business Card: Stores digitized business card information.</description>
    <label>名刺</label>
    <nameField>
        <label>氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/account__c.field-meta.xml
<CustomField>
    <fullName>account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>名刺</relationshipLabel>
    <relationshipName>nc_account</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/accountRegDateTime__c.field-meta.xml
<CustomField>
    <fullName>accountRegDateTime__c</fullName>
    <description>名刺を取引先と取引先責任者に登録した日時</description>
    <label>取引先取込日時</label>
    <type>DateTime</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/lead__c.field-meta.xml
<CustomField>
    <fullName>lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>リード</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>名刺</relationshipLabel>
    <relationshipName>nc_lead</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/leadRegDateTime__c.field-meta.xml
<CustomField>
    <fullName>leadRegDateTime__c</fullName>
    <description>名刺をリードに取込んだ日時</description>
    <label>リード取込日時</label>
    <type>DateTime</type>
</CustomField>

sfdx-source/SmartVisca/main/default/classes/SB_NameCard_UpdateRegDatetime.cls
/**
 *
 * 名刺の追加、更新時、項目「取引先」、「リード」に値がセットされていたら、取引先取込日時 リード取込日時に現在時刻をセットします。
 *		従来 SB_NameCard_BfInsUpdOnNameCard.trigger でやってた処理
 *
 * Copyright (C) 2012-2014 SunBridge Inc. All Rights Reserved.
 *
 *	@author sawano
 *	History :
 *		SB_NameCard_BfInsUpdOnNameCard.trigger の移植
 *	@Version 2		2014.4.2x
 **/
public with sharing class SB_NameCard_UpdateRegDatetime {

	public void run(NameCard__c[] newObjs, map<Id, NameCard__c> oldMap) {
		for (NameCard__c tmpNc : newObjs) {
			NameCard__c prvNc = oldMap == null ? null : oldMap.get(tmpNc.Id);
			if (tmpNc.account__c != null &&
				(prvNc ==null || prvNc.account__c != tmpNc.account__c)) { // 最新か、変更のあったとき
				tmpNc.accountRegDateTime__c = datetime.now();
			}
			if (tmpNc.lead__c != null &&
				(prvNc ==null || prvNc.lead__c != tmpNc.lead__c)) {	// 最新か、変更のあったとき
				tmpNc.leadRegDateTime__c = datetime.now();
			}
		}
	}
}