sfdx-source/unpackaged/dev-config/main/default/objects/NameCard__c/NameCard__c.object-meta.xml
<CustomObject>
    <customHelpPage>SB_NameCard_UserGuide</customHelpPage>
    <description>スキャナから取り込んだ名刺情報がここに保存されます。
Business Card: Stores digitized business card information.</description>
    <label>名刺</label>
    <nameField>
        <label>氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/card_id__c.field-meta.xml
<CustomField>
    <fullName>card_id__c</fullName>
    <label>名刺ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/company_name__c.field-meta.xml
<CustomField>
    <fullName>company_name__c</fullName>
    <label>会社名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/delivery_type__c.field-meta.xml
<CustomField>
    <fullName>delivery_type__c</fullName>
    <inlineHelpText>1: 一次納品
2: 最終納品</inlineHelpText>
    <label>納品タイプ</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/error__c.field-meta.xml
<CustomField>
    <fullName>error__c</fullName>
    <label>エラー情報</label>
    <type>TextArea</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/person_name_first__c.field-meta.xml
<CustomField>
    <fullName>person_name_first__c</fullName>
    <label>名</label>
    <length>127</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/person_name_last__c.field-meta.xml
<CustomField>
    <fullName>person_name_last__c</fullName>
    <label>姓</label>
    <length>127</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardHistory__c/NameCardHistory__c.object-meta.xml
<CustomObject>
    <description>名刺オブジェクトへのステータス変更履歴を登録
Business Card History: Stores updating business card data status.</description>
    <label>名刺履歴</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>名刺履歴No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/SmartVisca/main/default/objects/NameCardHistory__c/fields/card_id__c.field-meta.xml
<CustomField>
    <fullName>card_id__c</fullName>
    <label>名刺ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardHistory__c/fields/delete_time__c.field-meta.xml
<CustomField>
    <fullName>delete_time__c</fullName>
    <label>削除日時</label>
    <type>DateTime</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardHistory__c/fields/error_code__c.field-meta.xml
<CustomField>
    <fullName>error_code__c</fullName>
    <label>エラーコード</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardHistory__c/fields/NameCard__c.field-meta.xml
<CustomField>
    <fullName>NameCard__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>名刺オブジェクトID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardHistory__c/fields/primary_delivery_time__c.field-meta.xml
<CustomField>
    <fullName>primary_delivery_time__c</fullName>
    <label>一次納品日時</label>
    <type>DateTime</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardHistory__c/fields/secondary_delivery_time__c.field-meta.xml
<CustomField>
    <fullName>secondary_delivery_time__c</fullName>
    <label>二次納品日時</label>
    <type>DateTime</type>
</CustomField>

sfdx-source/SmartVisca/main/default/classes/SB_NameCard_HistoryTest.cls
/*	$Id: SB_NameCard_HistoryTest.cls 22 2014-07-02 05:32:59Z ume $	*/

/*
 * Copyright (c) 2014 SunBridge Inc.
 */

@isTest
private class SB_NameCard_HistoryTest
{
	private static testMethod void test()
	{
 		Test.startTest();
		SB_NameCard_TestDB db = new SB_NameCard_TestDB();
		db.initialize();

		// 名刺作成(一次納品)
		NameCard__c nc = new NameCard__c();
		nc.Name = '姓 名';
		nc.card_id__c = 'ABCDEFGH1234567890';
		nc.person_name_last__c = '姓';
		nc.person_name_first__c = '名';
		nc.company_name__c = '会社名';
		nc.delivery_type__c = '1';
		Database.insert(nc);

		nc = [SELECT Id, CreatedDate FROM NameCard__c WHERE Id = :nc.Id];
		NameCardHistory__c nch = [SELECT Id, primary_delivery_time__c, secondary_delivery_time__c, delete_time__c, error_code__c FROM NameCardHistory__c WHERE NameCard__c = :nc.Id];

		System.assertEquals(nc.CreatedDate, nch.primary_delivery_time__c, '一次納品日時');
		System.assertEquals(null, nch.secondary_delivery_time__c, '二次納品日時');
		System.assertEquals(null, nch.delete_time__c, '削除日時');
		System.assertEquals(null, nch.error_code__c, 'エラーコード');

		// 名刺更新(二次納品)
		nc.delivery_type__c = '2';
		Database.update(nc);

		nc = [SELECT Id, CreatedDate, LastModifiedDate FROM NameCard__c WHERE Id = :nc.Id];
		nch = [SELECT Id, primary_delivery_time__c, secondary_delivery_time__c, delete_time__c, error_code__c FROM NameCardHistory__c WHERE NameCard__c = :nc.Id];

		System.assertEquals(nc.CreatedDate, nch.primary_delivery_time__c, '一次納品日時');
		System.assertEquals(nc.LastModifiedDate, nch.secondary_delivery_time__c, '二次納品日時');
		System.assertEquals(null, nch.delete_time__c, '削除日時');
		System.assertEquals(null, nch.error_code__c, 'エラーコード');

		// 名刺更新(一次納品)
		nc.delivery_type__c = '1';
		Database.update(nc);

		nc = [SELECT Id, CreatedDate, LastModifiedDate FROM NameCard__c WHERE Id = :nc.Id];
		nch = [SELECT Id, primary_delivery_time__c, secondary_delivery_time__c, delete_time__c, error_code__c FROM NameCardHistory__c WHERE NameCard__c = :nc.Id];

		System.assertEquals(nc.LastModifiedDate, nch.primary_delivery_time__c, '一次納品日時');
		System.assertEquals(null, nch.delete_time__c, '削除日時');
		System.assertEquals(null, nch.error_code__c, 'エラーコード');

		// 名刺更新(二次納品 エラーコード1)
		nc.delivery_type__c = '2';
		nc.error__c = 'error_code: 1\nエラー\nエラー';
		Database.update(nc);

		nc = [SELECT Id, CreatedDate, LastModifiedDate FROM NameCard__c WHERE Id = :nc.Id];
		nch = [SELECT Id, primary_delivery_time__c, secondary_delivery_time__c, delete_time__c, error_code__c FROM NameCardHistory__c WHERE NameCard__c = :nc.Id];

		System.assertEquals(nc.LastModifiedDate, nch.secondary_delivery_time__c, '二次納品日時');
		System.assertEquals(null, nch.delete_time__c, '削除日時');
		System.assertEquals('1', nch.error_code__c, 'エラーコード');

		// 名刺削除
		Database.delete(nc.Id);

		nch = [SELECT Id, primary_delivery_time__c, secondary_delivery_time__c, delete_time__c, error_code__c FROM NameCardHistory__c WHERE NameCard__c = :nc.Id];

		System.assertEquals(nc.LastModifiedDate, nch.secondary_delivery_time__c, '二次納品日時');
		System.assertNotEquals(null, nch.delete_time__c, '削除日時');
		System.assertEquals('1', nch.error_code__c, 'エラーコード');

		// 名刺復元
		Database.undelete(nc.Id);

		nch = [SELECT Id, primary_delivery_time__c, secondary_delivery_time__c, delete_time__c, error_code__c FROM NameCardHistory__c WHERE NameCard__c = :nc.Id];

		System.assertEquals(nc.LastModifiedDate, nch.secondary_delivery_time__c, '二次納品日時');
		System.assertEquals(null, nch.delete_time__c, '削除日時');
		System.assertEquals('1', nch.error_code__c, 'エラーコード');

		// 名刺履歴削除
		Database.delete(nch.Id);

		// 名刺更新(一次納品)
		nc.delivery_type__c = '1';
		Database.update(nc);

		nc = [SELECT Id, CreatedDate, LastModifiedDate FROM NameCard__c WHERE Id = :nc.Id];
		nch = [SELECT Id, primary_delivery_time__c, secondary_delivery_time__c, delete_time__c, error_code__c FROM NameCardHistory__c WHERE NameCard__c = :nc.Id];

		System.assertEquals(nc.LastModifiedDate, nch.primary_delivery_time__c, '一次納品日時');
		System.assertEquals(null, nch.delete_time__c, '削除日時');
		System.assertEquals(null, nch.error_code__c, 'エラーコード');

		// 名刺履歴削除
		Database.delete(nch.Id);

		// 名刺更新(二次納品 エラーコード3)
		nc.delivery_type__c = '2';
		nc.error__c = 'error_code: 3\nエラー';
		Database.update(nc);

		nc = [SELECT Id, CreatedDate, LastModifiedDate FROM NameCard__c WHERE Id = :nc.Id];
		nch = [SELECT Id, primary_delivery_time__c, secondary_delivery_time__c, delete_time__c, error_code__c FROM NameCardHistory__c WHERE NameCard__c = :nc.Id];

		System.assertEquals(nc.LastModifiedDate, nch.secondary_delivery_time__c, '二次納品日時');
		System.assertEquals(null, nch.delete_time__c, '削除日時');
		System.assertEquals('3', nch.error_code__c, 'エラーコード');
	}
}