sfdx-source/unpackaged/dev-config/main/default/objects/NameCard__c/NameCard__c.object-meta.xml
<CustomObject>
    <customHelpPage>SB_NameCard_UserGuide</customHelpPage>
    <description>スキャナから取り込んだ名刺情報がここに保存されます。
Business Card: Stores digitized business card information.</description>
    <label>名刺</label>
    <nameField>
        <label>氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/email__c.field-meta.xml
<CustomField>
    <fullName>email__c</fullName>
    <label>メールアドレス</label>
    <type>Email</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/key__c.field-meta.xml
<CustomField>
    <fullName>key__c</fullName>
    <description>同じ名刺を特定するためのキー。氏名とメールアドレスを&amp;で接続したもの。</description>
    <externalId>true</externalId>
    <label>キー</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/person_name_first__c.field-meta.xml
<CustomField>
    <fullName>person_name_first__c</fullName>
    <label>名</label>
    <length>127</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/person_name_last__c.field-meta.xml
<CustomField>
    <fullName>person_name_last__c</fullName>
    <label>姓</label>
    <length>127</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/classes/SB_NameCard_SetExternalKeyTest.cls
/**
 *
 * 名刺オブジェクトのトリガ でやっている 外部キーをセットしているのをテスト
 *
 *	@author sawano
 *	@Version 2		2014.4.2x
 *
 */
@isTest
private class SB_NameCard_SetExternalKeyTest {

	public class SetExternalKeyTestDb extends SB_NameCard_TestDB {

	    public override void initialize() {
	        // SmartVisca設定
	        initializeSmartViscaConfig();
	        initializeUser();
	        if (listUser.isEmpty() == false)
	            insert listUser;
	        initializeNameCard();
	        if (listCard.isEmpty() == false)
	            insert listCard;
	        if (svConfig !=null) {
	        	if (svConfig.id == null) {
					insert svConfig;
	        	}
	        	else {
					update svConfig;
	        	}
	        }
	    }
	}

	private static testMethod void testSetExternalKey() {
		Test.startTest();
		SetExternalKeyTestDb db = new SetExternalKeyTestDb();
		db.initialize();

		list<NameCard__c> cards = [select Id, Name, key__c, person_name_last__c, person_name_first__c, email__c
				from  NameCard__c];
		for (NameCard__c nc : cards) {
			system.assertEquals(nc.person_name_last__c + ' ' + nc.person_name_first__c + '&' + nc.email__c, nc.key__c);
		}

      	Test.stopTest();
	}
}