sfdx-source/unpackaged/dev-config/main/default/objects/NameCard__c/NameCard__c.object-meta.xml
<CustomObject>
    <customHelpPage>SB_NameCard_UserGuide</customHelpPage>
    <description>スキャナから取り込んだ名刺情報がここに保存されます。
Business Card: Stores digitized business card information.</description>
    <label>名刺</label>
    <nameField>
        <label>氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/address__c.field-meta.xml
<CustomField>
    <fullName>address__c</fullName>
    <label>住所</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/address_bld__c.field-meta.xml
<CustomField>
    <fullName>address_bld__c</fullName>
    <label>建物名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/address_pref__c.field-meta.xml
<CustomField>
    <fullName>address_pref__c</fullName>
    <label>都道府県</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/company_name__c.field-meta.xml
<CustomField>
    <fullName>company_name__c</fullName>
    <label>会社名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/delivery_type__c.field-meta.xml
<CustomField>
    <fullName>delivery_type__c</fullName>
    <inlineHelpText>1: 一次納品
2: 最終納品</inlineHelpText>
    <label>納品タイプ</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/division__c.field-meta.xml
<CustomField>
    <fullName>division__c</fullName>
    <label>所属</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/email__c.field-meta.xml
<CustomField>
    <fullName>email__c</fullName>
    <label>メールアドレス</label>
    <type>Email</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/freehandmemo__c.field-meta.xml
<CustomField>
    <fullName>freehandmemo__c</fullName>
    <label>手書きメモ</label>
    <type>TextArea</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/list_name__c.field-meta.xml
<CustomField>
    <fullName>list_name__c</fullName>
    <label>リスト名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/memo__c.field-meta.xml
<CustomField>
    <fullName>memo__c</fullName>
    <description>スキャン後に入力したメモ</description>
    <label>メモ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/person_name_first__c.field-meta.xml
<CustomField>
    <fullName>person_name_first__c</fullName>
    <label>名</label>
    <length>127</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/person_name_last__c.field-meta.xml
<CustomField>
    <fullName>person_name_last__c</fullName>
    <label>姓</label>
    <length>127</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/tel1__c.field-meta.xml
<CustomField>
    <fullName>tel1__c</fullName>
    <label>電話番号</label>
    <type>Phone</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/title_name__c.field-meta.xml
<CustomField>
    <fullName>title_name__c</fullName>
    <label>役職</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/zip_code__c.field-meta.xml
<CustomField>
    <fullName>zip_code__c</fullName>
    <label>郵便番号</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/classes/SB_NC_DTOTest.cls
/**
 *
 * SB_NC_DTO
 *   各オブジェクトのレコードを 名前空間プレフィクスなしで扱えるようのクラス の既定 のテストクラス
 *
 * Copyright (C) 2017 SunBridge Inc. All Rights Reserved.
 *
 *  @author sawano
 *  @Version 1      2017.03.xx
 *  @Version 2      2017.10.xx  v1.21 for code scan Test Methods With No Assert
 *
 **/
@isTest
private class SB_NC_DTOTest
{

  @testSetup
  static void setupNameCards() {
    List<NameCard__c> listCard = new List<NameCard__c>();
    listCard.add(new NameCard__c(
      Name='名刺 太郎'
      , person_name_last__c= '名刺'
      , person_name_first__c='太郎'
      , email__c='taro@test.com'
      , company_name__c= 'テスト株式会社'
      , division__c = '本社'
      , title_name__c = '役職'
      , tel1__c= '03-3333-3333'
      , zip_code__c = '115-0022'
      , address_pref__c = '東京都'
      , address__c = '渋谷区'
      , address_bld__c = '恵比寿1−5−5'
      , list_name__c ='名刺リスト'
      , memo__c = 'メモ'
      , freehandmemo__c = '自由記述'
      , delivery_type__c='1'
    ));
    listCard.add(new NameCard__c(
      Name='名刺 二郎'
      , person_name_last__c= '名刺'
      , person_name_first__c='二郎'
      , email__c='jiro@test.com'
      , company_name__c= 'テスト株式会社'
      , division__c = '本社'
      , title_name__c = '役職'
      , tel1__c= '03-3333-3333'
      , zip_code__c = '115-0022'
      , address_pref__c = '東京都'
      , address__c = '渋谷区'
      , address_bld__c = '恵比寿1−5−5'
      , list_name__c ='名刺リスト'
      , memo__c = 'メモ'
      , freehandmemo__c = '自由記述'
      , delivery_type__c='1'
    ));
    System.assertEquals(2, listCard.size());  // 2017.10.xx  v1.21 for code scan Test Methods With No Assert
    insert listCard;
  }

  @isTest
  static void test_getInstanceSingle() {
    List<NameCard__c> cards = [SELECT ID, Name, person_name_last__c, person_name_first__c, email__c FROM NameCard__c];
    SB_NC_NameCardDTO dto = (SB_NC_NameCardDTO)SB_NC_DTO.getInstance(cards[0]);
    System.assertEquals(cards[0].Name, dto.name);
  }

  @isTest
  static void test_getInstanceList() {
    List<NameCard__c> cards = [SELECT ID, Name, person_name_last__c, person_name_first__c, email__c FROM NameCard__c];
    List<SB_NC_DTO> dtos = SB_NC_DTO.getInstance(cards);
    System.assertEquals(cards.size(), dtos.size());
  }

}