sfdx-source/unpackaged/dev-config/main/default/objects/NameCard__c/NameCard__c.object-meta.xml
<CustomObject>
    <customHelpPage>SB_NameCard_UserGuide</customHelpPage>
    <description>スキャナから取り込んだ名刺情報がここに保存されます。
Business Card: Stores digitized business card information.</description>
    <label>名刺</label>
    <nameField>
        <label>氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/delivery_type__c.field-meta.xml
<CustomField>
    <fullName>delivery_type__c</fullName>
    <inlineHelpText>1: 一次納品
2: 最終納品</inlineHelpText>
    <label>納品タイプ</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>氏名とメールアドレスが同じ名刺の内、最新のものへのリンク。最新のものは、この項目は null になる。最新かどうかの判断は「日付」(date__c)で行う。このリンクの設定は最終納品のときだけ行う。</description>
    <label>最新名刺</label>
    <referenceTo>NameCard__c</referenceTo>
    <relationshipLabel>古い名刺</relationshipLabel>
    <relationshipName>nc_parent</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/Saishin__c.field-meta.xml
<CustomField>
    <fullName>Saishin__c</fullName>
    <defaultValue>false</defaultValue>
    <label>この名刺が最新</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/tenshokugonomeishi__c.field-meta.xml
<CustomField>
    <fullName>tenshokugonomeishi__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>転職後の名刺</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>NameCard__c.delivery_type__c</field>
            <operation>equals</operation>
            <value>2</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>NameCard__c</referenceTo>
    <relationshipLabel>名刺 (転職前の名刺)</relationshipLabel>
    <relationshipName>meishiwSLt</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/tenshokuzumi__c.field-meta.xml
<CustomField>
    <fullName>tenshokuzumi__c</fullName>
    <defaultValue>false</defaultValue>
    <label>転職済み</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/classes/SB_NameCard_TenshokuExtention.cls
public with sharing class SB_NameCard_TenshokuExtention {

    public class SB_NameCard_TenshokuExtentionException extends Exception {}

    public NameCard__c nameCard = null;

    public SB_NameCard_TenshokuExtention ( ApexPages.StandardController controller) {
        this.nameCard = (NameCard__c)controller.getRecord();
        //LightningStyleSheetを対応するため、Lightningにはjsボタン画面に表示できないため、チェックはControllerに移動
        if (this.nameCard.Saishin__c == false) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, System.Label.SB_NC_CareerErrorNotLatest, ''));
        }
    }

    private static Integer callNumber = 0;

    private NameCard__c getSaishinReccursive( Id input) {
        Integer localCallNumber = callNumber++;
System.debug( '----- (' + localCallNumber + ') getSaishinReccursive start');

        NameCard__c ret = null;

        List<NameCard__c> nameCard = [SELECT Id, Name, Parent__c, Saishin__c FROM NameCard__c WHERE Id = :input AND delivery_type__c = '2' Limit 1];
System.debug( '----- (' + localCallNumber + ')');

        if ( nameCard.size() == 0) {
            return null;
        }
        else {
System.debug( '----- (' + localCallNumber + ') saishin__c=' + nameCard[0].Saishin__c);
            if ( nameCard[0].Saishin__c == true) {
System.debug( '----- (' + localCallNumber + ') 決定：' + nameCard[0].Name);
                ret = NameCard[0];
            }
            else {
System.debug( '----- (' + localCallNumber + ') 再帰へ');
                ret = getSaishinReccursive( nameCard[0].Parent__c);
            }
        }

System.debug( '----- (' + localCallNumber + ') getSaishinReccursive end');
        return ret;
    }

    public PageReference doSave() {

        //SB_FirstRunKeeper.SB_AftInsUpdOnNameCard = false;

        System.debug( '----- ' + nameCard.Name);
        System.debug( '----- ' + nameCard.tenshokugonomeishi__c);

        if ( nameCard.tenshokugonomeishi__c == null) {
            // 関連付けがとれた場合
            ApexPages.addMessage(new ApexPages.Message( ApexPages.Severity.ERROR, System.Label.SB_MSG_SelectNewCareer, ''));
            return null;
        }
        else if ( nameCard.tenshokugonomeishi__c == nameCard.Id) {
            // 自分自身と同じIDがセットされている
            ApexPages.addMessage(new ApexPages.Message( ApexPages.Severity.ERROR, System.Label.SB_MSG_NewCareerMustBeAnother, ''));
            return null;
        }
        else {
            // 関連付けが定義された場合

            // 自分自身を参照する名刺データを、転職後の名刺グループの最新のものに関連付ける

            // 自分自身を参照する名刺データを select
            List<NameCard__c> refferring = [SELECT Id, Name, Parent__c FROM NameCard__c WHERE Parent__c = :nameCard.Id AND delivery_type__c = '2'];

            // 転職後の名刺グループの最新名刺を取得
            NameCard__c newSaishin = getSaishinReccursive( nameCard.tenshokugonomeishi__c);

            if ( newSaishin == null) {
                ApexPages.addMessage(new ApexPages.Message( ApexPages.Severity.ERROR, System.Label.SB_MSG_NoLatestCardSelected, ''));
                return null;
            }
            // 2014.08.20 最新の名刺を転職後の名刺にするので、循環参照しないようにチェックします。
            if ( newSaishin.Id == nameCard.Id) {
                ApexPages.addMessage(new ApexPages.Message( ApexPages.Severity.ERROR, System.Label.SB_MSG_NewCareerCantBeOldOfSelf, ''));
                return null;
            }

System.debug( '----- 最新の名刺決定：' + newSaishin.Name);


            for ( NameCard__c local : refferring) {
System.debug( '----- local.Name=' + local.Name);
                local.Parent__c = newSaishin.id;
                local.tenshokuzumi__c = true;
            }

 //           update refferring;
            // 2014.4.2x CRUD/FLS 対応
            SB_NameCard_CrudFls.supdate(refferring, true);

            nameCard.Parent__c = newSaishin.id;
            nameCard.saishin__c = false;
            nameCard.tenshokuzumi__c = true;
//            update nameCard;
            // 2014.4.2x CRUD/FLS 対応
            list<NameCard__c> cards = new list<NameCard__c>();
            cards.add(nameCard);
            SB_NameCard_CrudFls.supdate(cards, true);

            return new ApexPages.StandardController(nameCard).view();
        }

    }

}