sfdx-source/unpackaged/dev-config/main/default/objects/NameCard__c/NameCard__c.object-meta.xml
<CustomObject>
    <customHelpPage>SB_NameCard_UserGuide</customHelpPage>
    <description>スキャナから取り込んだ名刺情報がここに保存されます。
Business Card: Stores digitized business card information.</description>
    <label>名刺</label>
    <nameField>
        <label>氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/address__c.field-meta.xml
<CustomField>
    <fullName>address__c</fullName>
    <label>住所</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/address_pref__c.field-meta.xml
<CustomField>
    <fullName>address_pref__c</fullName>
    <label>都道府県</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/company_name__c.field-meta.xml
<CustomField>
    <fullName>company_name__c</fullName>
    <label>会社名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/delivery_type__c.field-meta.xml
<CustomField>
    <fullName>delivery_type__c</fullName>
    <inlineHelpText>1: 一次納品
2: 最終納品</inlineHelpText>
    <label>納品タイプ</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/division__c.field-meta.xml
<CustomField>
    <fullName>division__c</fullName>
    <label>所属</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/email__c.field-meta.xml
<CustomField>
    <fullName>email__c</fullName>
    <label>メールアドレス</label>
    <type>Email</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/first_name__c.field-meta.xml
<CustomField>
    <fullName>first_name__c</fullName>
    <description>英語名刺の場合</description>
    <label>ファーストネーム</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/last_name__c.field-meta.xml
<CustomField>
    <fullName>last_name__c</fullName>
    <description>英語名刺の場合</description>
    <label>ラストネーム</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/zip_code__c.field-meta.xml
<CustomField>
    <fullName>zip_code__c</fullName>
    <label>郵便番号</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/NameCardBasicSetting__c.object-meta.xml
<CustomObject>
    <label>名刺基本設定</label>
    <nameField>
        <label>基本設定</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiActive__c.field-meta.xml
<CustomField>
    <fullName>RenkeiActive__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>名刺データが2次納品された時に取引先・取引先責任者を自動で作成したり更新したりすることができます。「SmartVisca連携設定」タブで連携する条件の設定をします。リード拡張パッケージがインストールされている場合、取引先・取引先責任者に加えてリードを作成・更新できます。</inlineHelpText>
    <label>自動連携:自動連携機能を有効化</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiLeadActive__c.field-meta.xml
<CustomField>
    <fullName>RenkeiLeadActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>自動連携におけるリード登録機能 を有効化する。リード登録機能 はリード拡張パッケージの機能だが、設定は基本パッケージ内に持つ</description>
    <label>自動連携:リード登録機能を有効化</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/ScanSelectCampaign__c.field-meta.xml
<CustomField>
    <fullName>ScanSelectCampaign__c</fullName>
    <defaultValue>false</defaultValue>
    <label>スキャン:キャンペーン選択を有効化</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/SmartViscaConfig__c/SmartViscaConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>SmartViscaの表示設定や、Triggerの設定を持ちます。</description>
    <label>SmartVisca設定</label>
</CustomObject>

sfdx-source/SmartVisca/main/default/objects/SmartViscaConfig__c/fields/TriggerLeadExRenkeiTriggerHandler__c.field-meta.xml
<CustomField>
    <fullName>TriggerLeadExRenkeiTriggerHandler__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Lead連携拡張パッケージの中にある 自動連携のトリガハンドラを呼ぶ</description>
    <inlineHelpText>サンブリッジサポートの指示があった場合のみ設定します。</inlineHelpText>
    <label>トリガでリード拡張パッケージの自動連携を使う</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/classes/SB_NameCardL_RenkeiTriggerHandlerT.cls
/**
 *
 *  SB_NameCardL_RenkeiTriggerHandlerT
 *   LEAD拡張パッケージの 連携用トリガハンドラを呼ぶテストクラス
 *
 *  Copyright (C) 2018 SunBridge Inc. All Rights Reserved.
 *
 *  @author sawano
 *  @Version 1.22      2018.03.xx
 *
 **/
@isTest
private class SB_NameCardL_RenkeiTriggerHandlerT
{

  public class TestDb extends SB_NC_TestDB {

    public override void initializeSmartViscaConfig() {
      svConfig = SmartViscaConfig__c.getOrgDefaults();
      svConfig.TriggerLeadExRenkeiTriggerHandler__c = true; // 2018.03.xx v1.22  Lead連携拡張パッケージの中にある 自動連携のトリガハンドラを呼ぶ
    }

    public override void initializeBasicSetting() {
      NameCardBasicSetting__c bs = SB_NC_PostInstallScript.createDefaultBasicSetting();
      bs.ScanSelectCampaign__c = false; // 名刺スキャン時のキャンペーン選択を有効化
      bs.RenkeiActive__c = true;        // 自動連携機能を有効化
      bs.RenkeiLeadActive__c = true;    // リード登録機能を有効化
      listBasicSetting.add(bs);
    }

    public override void initialize() {

      // SmartVisca設定
      initializeSmartViscaConfig();
      if (svConfig !=null) {
        upsert svConfig;
      }
      //
      initializeUser();
      if (listUser.isEmpty() == false) {
        insert listUser;
      }
      // 名刺基本設定
      initializeBasicSetting();
      if (!listBasicSetting.isEmpty()) {
        insert listBasicSetting;
      }
      // 名刺連携項目マッピング
      initializeMapping();
      if (!listMapping.isEmpty()) {
        insert listMapping;
      }
    }

  }   // public class TestDb extends SB_NC_TestDB

  @isTest
  static void test_LeadexRenkeiTrigerHandler_Insert() {
    TestDb db = new TestDb();
    db.initialize();

    Test.startTest();
    List<NameCard__c> listCard = new List<NameCard__c>();
    listCard.add(new NameCard__c(Name='テスト 一郎', company_name__c='株式会社テスト商事', division__c='本社',
                  zip_code__c='150-0022', address_pref__c='東京都', address__c='渋谷区恵比寿南1-5-5',
                  last_name__c='テスト', first_name__c='一郎', email__c='ichiro@test.com', delivery_type__c='2'));
    insert listCard;

    String nsLx = SB_NameCard_Util.getLeadExNamespacePrefix();
    SB_NameCard_TriggerHandlerAbstract handler = SB_NameCard_TriggerHandlerFactory.getInstance(nsLx, 'SB_NameCardL_RenkeiTriggerHandler');
    System.assertEquals(true, handler.didInsert());

    Test.stopTest();
  }

  @isTest
  static void test_LeadexRenkeiTrigerHandler_Update() {
    TestDb db = new TestDb();
    db.initialize();

    Test.startTest();
    List<NameCard__c> listCard = new List<NameCard__c>();
    listCard.add(new NameCard__c(Name='テスト 一郎', company_name__c='株式会社テスト商事', division__c='本社',
                  zip_code__c='150-0022', address_pref__c='東京都', address__c='渋谷区恵比寿南1-5-5',
                  last_name__c='テスト', first_name__c='一郎', email__c='ichiro@test.com', delivery_type__c='2'));
    insert listCard;

    listCard = [SELECT Id, Name FROM NameCard__c];
    update listCard;

    String nsLx = SB_NameCard_Util.getLeadExNamespacePrefix();
    SB_NameCard_TriggerHandlerAbstract handler = SB_NameCard_TriggerHandlerFactory.getInstance(nsLx, 'SB_NameCardL_RenkeiTriggerHandler');
    System.assertEquals(true, handler.didInsert());
    System.assertEquals(true, handler.didUpdate());

    Test.stopTest();
  }


}