sfdx-source/SmartVisca/main/default/objects/NameCardRenkeiMapping__c/NameCardRenkeiMapping__c.object-meta.xml
<CustomObject>
    <label>名刺連携項目マッピング</label>
    <nameField>
        <displayFormat>RM-{000000}</displayFormat>
        <label>名刺連携項目マッピングNo</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/SmartVisca/main/default/objects/NameCardRenkeiMapping__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>有効</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardRenkeiMapping__c/fields/NameCardName__c.field-meta.xml
<CustomField>
    <fullName>NameCardName__c</fullName>
    <label>名刺の項目(API名称)</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardRenkeiMapping__c/fields/TargetName__c.field-meta.xml
<CustomField>
    <fullName>TargetName__c</fullName>
    <label>対象の項目(API名称)</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/classes/SB_NameCard_NameCardRenkeiMappingDTOTest.cls
/**
 *
 * SB_NameCard_NameCardRenkeiMappingDTOTest
 * SB_NameCard_NameCardRenkeiMappingDTOのテストクラス
 *
 *
 *
 *  Copyright (C) 2017 SunBridge Inc. All Rights Reserved.
 *
 *  @author mao
 *  @Version 1.20      2017.02.XX
 *
 **/
@isTest
private class SB_NameCard_NameCardRenkeiMappingDTOTest {

  //NameCardRenkeiMapping__c -> bin
  @isTest static void test_Bind() {
    NameCardRenkeiMapping__c mapp = new NameCardRenkeiMapping__c();
    mapp.TargetName__c = 'tarname';
    mapp.NameCardName__c = 'ncname';
    mapp.IsActive__c = true;
    SB_NameCard_NameCardRenkeiMappingDTO dto = new SB_NameCard_NameCardRenkeiMappingDTO();
    dto.bind(mapp);
    System.assertEquals(dto.TargetName,'tarname');
    System.assertEquals(dto.NameCardName,'ncname');
    System.assertEquals(dto.IsActive,'true');
  }

  //bin -> NameCardRenkeiMapping__c
  @isTest static void test_DeBind() {
    NameCardRenkeiMapping__c mapp = new NameCardRenkeiMapping__c();
    mapp.TargetName__c = 'tarname';
    mapp.NameCardName__c = 'ncname';
    mapp.IsActive__c = true;
    SB_NameCard_NameCardRenkeiMappingDTO dto = new SB_NameCard_NameCardRenkeiMappingDTO();
    dto.bind(mapp);
    NameCardRenkeiMapping__c maap = dto.debind();
    System.assertEquals(maap.TargetName__c,'tarname');
    System.assertEquals(maap.NameCardName__c,'ncname');
    System.assertEquals(maap.IsActive__c,true);
  }

}