src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>NameCard__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>名刺</label>
        <referenceTo>SmartViscaf__NameCard__c</referenceTo>
        <relationshipLabel>リード</relationshipLabel>
        <relationshipName>NameCards</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

sfdx-source/unpackaged/dev-config/main/default/objects/NameCard__c/NameCard__c.object-meta.xml
<CustomObject>
    <customHelpPage>SB_NameCard_UserGuide</customHelpPage>
    <description>スキャナから取り込んだ名刺情報がここに保存されます。
Business Card: Stores digitized business card information.</description>
    <label>名刺</label>
    <nameField>
        <label>氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SmartViscaf__NameCard__c.object
<CustomObject>
    <fields>
        <fullName>campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>キャンペーン</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>名刺</relationshipLabel>
        <relationshipName>nc_campaign</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

sfdx-source/unpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__address__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__address__c</fullName>
    <label>住所</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__address_bld__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__address_bld__c</fullName>
    <label>建物名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/unpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__address_eng__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__address_eng__c</fullName>
    <description>英語名刺の場合</description>
    <label>英語住所</label>
    <type>TextArea</type>
</CustomField>

sfdx-source/unpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__address_pref__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__address_pref__c</fullName>
    <label>都道府県</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__card_exchange_date__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__card_exchange_date__c</fullName>
    <label>名刺交換日</label>
    <type>Date</type>
</CustomField>

sfdx-source/unpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__company_name__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__company_name__c</fullName>
    <label>会社名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/unpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__delivery_type__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__delivery_type__c</fullName>
    <inlineHelpText>1: 一次納品
2: 最終納品</inlineHelpText>
    <label>納品タイプ</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__email__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__email__c</fullName>
    <label>メールアドレス</label>
    <type>Email</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__fax1__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__fax1__c</fullName>
    <label>FAX番号</label>
    <type>Phone</type>
</CustomField>

sfdx-source/unpackaged - コピー/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__first_name__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__first_name__c</fullName>
    <description>英語名刺の場合</description>
    <label>ファーストネーム</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__freehandmemo__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__freehandmemo__c</fullName>
    <label>手書きメモ</label>
    <type>TextArea</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__last_name__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__last_name__c</fullName>
    <description>英語名刺の場合</description>
    <label>ラストネーム</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__lead__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>リード</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>名刺</relationshipLabel>
    <relationshipName>nc_lead</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__list_name__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__list_name__c</fullName>
    <label>リスト名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/unpackaged - コピー/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__memo__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__memo__c</fullName>
    <description>スキャン後に入力したメモ</description>
    <label>メモ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/unpackaged - コピー/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__mobile__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__mobile__c</fullName>
    <label>携帯電話番号</label>
    <type>Phone</type>
</CustomField>

sfdx-source/unpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__Parent__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>氏名とメールアドレスが同じ名刺の内、最新のものへのリンク。最新のものは、この項目は null になる。最新かどうかの判断は「日付」(date__c)で行う。このリンクの設定は最終納品のときだけ行う。</description>
    <label>最新名刺</label>
    <referenceTo>SmartViscaf__NameCard__c</referenceTo>
    <relationshipLabel>古い名刺</relationshipLabel>
    <relationshipName>nc_parent</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__person_name_first__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__person_name_first__c</fullName>
    <label>名</label>
    <length>127</length>
    <type>Text</type>
</CustomField>

sfdx-source/unpackaged - コピー/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__person_name_last__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__person_name_last__c</fullName>
    <label>姓</label>
    <length>127</length>
    <type>Text</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__tel1__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__tel1__c</fullName>
    <label>電話番号</label>
    <type>Phone</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__title_name__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__title_name__c</fullName>
    <label>役職</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__web_url1__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__web_url1__c</fullName>
    <label>URL</label>
    <type>Url</type>
</CustomField>

sfdx-source/unpackaged - コピー/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__zip_code__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__zip_code__c</fullName>
    <label>郵便番号</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

src/classes/SB_NameCard_LeadNameCardListController.cls
/*
 * (c) 2015 SunBridge Inc.
 *
 * リードを更新
 */

public with sharing class SB_NameCard_LeadNameCardListController
{

  public class NameCardRecord
  {
    public Integer index { get; set; }
    public SmartViscaf__NameCard__c nameCard { get; set; }

    public NameCardRecord(Integer index, SmartViscaf__NameCard__c nc)
    {
      this.index = index;
      this.nameCard = nc;
    }
  }

  public Boolean leadOverwrite { get; set; }
  public Integer nameCardRecordListIndex { get; set; }
  public List<NameCardRecord> nameCardRecordList { get; set; }
  public String overwriteLeadInfoLabel{get;set;}
  public String updateLeadLabel{get;set;}

  private Lead lead;

  public SB_NameCard_LeadNameCardListController(ApexPages.StandardController sc)
  {
    try {
      this.updateLeadLabel = System.Label.SB_NCLD_Text_UpdateLeadDEV;
      this.updateLeadLabel = this.updateLeadLabel.replace('&*Lead*&',System.Label.SB_NCLD_Text_Lead);
      this.updateLeadLabel = this.updateLeadLabel.replace('&*smallLead*&',System.Label.SB_NCLD_Text_SmallLead);
      this.overwriteLeadInfoLabel = System.Label.SB_NCLD_Label_OverwriteLeadInfoDEV;
      this.overwriteLeadInfoLabel = this.overwriteLeadInfoLabel.replace('&*Lead*&',System.Label.SB_NCLD_Text_Lead);
      this.overwriteLeadInfoLabel = this.overwriteLeadInfoLabel.replace('&*smallLead*&',System.Label.SB_NCLD_Text_SmallLead);
      this.leadOverwrite = SB_NameCard_LeadRegist.svConfig.overwrite();
      this.nameCardRecordListIndex = -1;
      this.nameCardRecordList = new List<NameCardRecord>();

      this.lead = getLead(sc.getId());
      List<SmartViscaf__NameCard__c> nameCardList = getNameCardList(this.lead, false);
      if (nameCardList != null && nameCardList.size() > 1000) {
          nameCardList = getNameCardList(this.lead, true);
      }

      if (nameCardList != null && nameCardList.size() <= 1000) {
        for (SmartViscaf__NameCard__c nc : nameCardList) {
          this.nameCardRecordList.add(new NameCardRecord(this.nameCardRecordList.size(), nc));
        }
      }
    } catch (Exception e) {
      ApexPages.addMessages(e);
    }
  }

  // リード
  private static Lead getLead(Id leadId)
  {
    if (leadId == null) return null;

    for (Lead lead : [SELECT Id, Name, Email, LastName, FirstName FROM Lead WHERE Id = :leadId]) {
      return lead;
    }
    return null;
  }

  // 名刺リスト
  private static List<SmartViscaf__NameCard__c> getNameCardList(Lead lead, Boolean latestonly)
  {
    if (lead == null) return null;

    List<String> whereList = new List<String>();
    String leadId, email, lastName, firstName;

    leadId = lead.Id;
    whereList.add('SmartViscaf__lead__c = :leadId');

    if (String.isNotBlank(lead.Email)) {
      email = lead.Email;
      whereList.add('SmartViscaf__email__c = :email');
    }
    if (String.isNotBlank(lead.LastName) && String.isNotBlank(lead.FirstName)) {
      lastName = lead.LastName;
      firstName = lead.FirstName;
      whereList.add('((SmartViscaf__person_name_last__c = :lastName OR SmartViscaf__last_name__c = :lastName)'
        + ' AND (SmartViscaf__person_name_first__c = :firstName OR SmartViscaf__first_name__c = :firstName))');
    }
    if (whereList.size() <= 0) return null;

    String whereStr = '';
    for (String s : whereList) whereStr += ' OR ' + s;
    whereStr = whereStr.removeStart(' OR ');
        if (latestonly) {
            whereStr = '(' + whereStr + ') AND SmartViscaf__delivery_type__c != \'1\' AND SmartViscaf__Parent__c = null';
        }


    String soql = 'SELECT Id, Name, OwnerId, Owner.Name, LastModifiedDate,'
      + ' SmartViscaf__zip_code__c, SmartViscaf__address_pref__c, SmartViscaf__address__c,'
      + ' SmartViscaf__address_bld__c, SmartViscaf__address_eng__c,'
      + ' SmartViscaf__company_name__c, SmartViscaf__web_url1__c, SmartViscaf__tel1__c, SmartViscaf__fax1__c, SmartViscaf__title_name__c,'
      + ' SmartViscaf__person_name_last__c, SmartViscaf__person_name_first__c, SmartViscaf__last_name__c, SmartViscaf__first_name__c,'
      + ' SmartViscaf__email__c, SmartViscaf__mobile__c, SmartViscaf__lead__c, campaign__c,'
      + ' SmartViscaf__list_name__c, SmartViscaf__memo__c, SmartViscaf__freehandmemo__c, SmartViscaf__card_exchange_date__c'
      + ' FROM SmartViscaf__NameCard__c'
      + ' WHERE ' + whereStr
      + ' ORDER BY SmartViscaf__card_exchange_date__c DESC NULLS LAST, SmartViscaf__company_name__c ASC NULLS LAST,'
      + ' SmartViscaf__address_pref__c ASC NULLS LAST, SmartViscaf__title_name__c ASC NULLS LAST, LastModifiedDate DESC LIMIT 1001';

    return Database.query(soql);
  }

  // 更新
  public PageReference save()
  {
    if (this.lead == null) return null;
    PageReference pageRef;
    Savepoint sp;

    try {
      if (this.nameCardRecordListIndex < 0 || this.nameCardRecordListIndex >= this.nameCardRecordList.size()) return null;
      NameCardRecord ncRec = this.nameCardRecordList.get(this.nameCardRecordListIndex);
      if (ncRec == null) return null;

      Lead updLead;
      if (this.leadOverwrite) {
        updLead = SB_NameCard_LeadRegist.getLead(this.lead.Id, ncRec.nameCard, null);
      } else {
        updLead = new Lead(Id=this.lead.Id, NameCard__c=ncRec.nameCard.Id);
      }

      sp = Database.setSavepoint();

      Database.DMLOptions leaddml = new Database.DMLOptions();

      leaddml.OptAllOrNone = false;

      SB_NameCard_LeadCrudFls.supdate(new List<Lead>{updLead}, leaddml);

      if (ncRec.nameCard.SmartViscaf__lead__c != updLead.Id) {


        Database.DMLOptions dml = new Database.DMLOptions();

        dml.OptAllOrNone = false;

        SB_NameCard_LeadCrudFls.supdate(new List<SmartViscaf__NameCard__c>{new SmartViscaf__NameCard__c(Id=ncRec.nameCard.Id, SmartViscaf__lead__c=updLead.Id)},dml);
      }
      pageRef = (new ApexPages.StandardController(updLead)).view();
    } catch (Exception e) {
      if (sp != null) Database.rollback(sp);
      ApexPages.addMessages(e);
    }
    return pageRef;
  }

  // キャンセル
  public PageReference cancel()
  {
    if (this.lead == null) return null;
    return (new ApexPages.StandardController(this.lead)).view();
  }
}