src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>NameCardFreehandmemo__c</fullName>
        <label>名刺手書きメモ</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>NameCardListName__c</fullName>
        <label>名刺リスト名</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NameCardMemo__c</fullName>
        <label>名刺メモ</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NameCard__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>名刺</label>
        <referenceTo>SmartViscaf__NameCard__c</referenceTo>
        <relationshipLabel>リード</relationshipLabel>
        <relationshipName>NameCards</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

sfdx-source/unpackaged/dev-config/main/default/objects/NameCard__c/NameCard__c.object-meta.xml
<CustomObject>
    <customHelpPage>SB_NameCard_UserGuide</customHelpPage>
    <description>スキャナから取り込んだ名刺情報がここに保存されます。
Business Card: Stores digitized business card information.</description>
    <label>名刺</label>
    <nameField>
        <label>氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SmartViscaf__NameCard__c.object
<CustomObject>
    <fields>
        <fullName>campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>キャンペーン</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>名刺</relationshipLabel>
        <relationshipName>nc_campaign</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

sfdx-source/unpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__account__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>名刺</relationshipLabel>
    <relationshipName>nc_account</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/unpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__address__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__address__c</fullName>
    <label>住所</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__address_bld__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__address_bld__c</fullName>
    <label>建物名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/unpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__address_eng__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__address_eng__c</fullName>
    <description>英語名刺の場合</description>
    <label>英語住所</label>
    <type>TextArea</type>
</CustomField>

sfdx-source/unpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__address_pref__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__address_pref__c</fullName>
    <label>都道府県</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__card_exchange_date__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__card_exchange_date__c</fullName>
    <label>名刺交換日</label>
    <type>Date</type>
</CustomField>

sfdx-source/unpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__company_name__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__company_name__c</fullName>
    <label>会社名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__contact__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>取引先責任者</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>名刺</relationshipLabel>
    <relationshipName>nc_contact</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__division__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__division__c</fullName>
    <label>所属</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__email__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__email__c</fullName>
    <label>メールアドレス</label>
    <type>Email</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__fax1__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__fax1__c</fullName>
    <label>FAX番号</label>
    <type>Phone</type>
</CustomField>

sfdx-source/unpackaged - コピー/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__first_name__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__first_name__c</fullName>
    <description>英語名刺の場合</description>
    <label>ファーストネーム</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__freehandmemo__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__freehandmemo__c</fullName>
    <label>手書きメモ</label>
    <type>TextArea</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__last_name__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__last_name__c</fullName>
    <description>英語名刺の場合</description>
    <label>ラストネーム</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__lead__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>リード</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>名刺</relationshipLabel>
    <relationshipName>nc_lead</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__list_name__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__list_name__c</fullName>
    <label>リスト名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/unpackaged - コピー/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__memo__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__memo__c</fullName>
    <description>スキャン後に入力したメモ</description>
    <label>メモ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/unpackaged - コピー/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__mobile__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__mobile__c</fullName>
    <label>携帯電話番号</label>
    <type>Phone</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__person_name_first__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__person_name_first__c</fullName>
    <label>名</label>
    <length>127</length>
    <type>Text</type>
</CustomField>

sfdx-source/unpackaged - コピー/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__person_name_last__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__person_name_last__c</fullName>
    <label>姓</label>
    <length>127</length>
    <type>Text</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__tel1__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__tel1__c</fullName>
    <label>電話番号</label>
    <type>Phone</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__title_name__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__title_name__c</fullName>
    <label>役職</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__web_url1__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__web_url1__c</fullName>
    <label>URL</label>
    <type>Url</type>
</CustomField>

sfdx-source/unpackaged - コピー/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__zip_code__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__zip_code__c</fullName>
    <label>郵便番号</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sfdx-source/unpackaged/dev-config/main/default/objects/SmartViscaf__NameCardBasicSetting__c/SmartViscaf__NameCardBasicSetting__c.object-meta.xml
<CustomObject>
    <label>名刺基本設定</label>
    <nameField>
        <label>基本設定</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCardBasicSetting__c/fields/SmartViscaf__RegistLeadNoToDo__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__RegistLeadNoToDo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>取引先登録:リードToDo登録しない</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/unpackaged/main/default/objects/SmartViscaf__NameCardBasicSetting__c/fields/SmartViscaf__RegistLeadToDoSubject__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__RegistLeadToDoSubject__c</fullName>
    <label>取引先登録:リードToDo件名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/unpackaged/main/default/objects/SmartViscaf__NameCardBasicSetting__c/fields/SmartViscaf__RegistNoToDo__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__RegistNoToDo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>取引先登録:ToDo登録しない</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCardBasicSetting__c/fields/SmartViscaf__RegistToDoSubject__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__RegistToDoSubject__c</fullName>
    <defaultValue>&apos;名刺交換&apos;</defaultValue>
    <label>取引先登録:ToDo件名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/SmartViscaf__SmartViscaConfig__c.object
<CustomObject>
    <fields>
        <fullName>LeadRegist_DispCompany__c</fullName>
        <defaultValue>false</defaultValue>
        <label>リードに登録 会社名表示</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LeadRegist_TodoSubject__c</fullName>
        <label>リードに登録 ToDo件名【移行済】</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

sfdx-source/SmartViscal/main/default/classes/SB_NameCard_LeadRegist.cls
/*
 * (c) 2016 Sunbridge Inc.
 *
 * リードに登録
 * 共通クラス
 *
 *  2016.11.09  コードスキャンで global なメソッドは with sharing が必要とのことなので、 with sharing  を付けた。
 *  @Version 1 2017/11/XX  SV_DEV-681 Lead一括登録での候補検索時の姓、名の文字列のエスケープは完全一致なので、不要では。
 *                         SV_DEV-747 リード拡張パッケージのカスタム設定：リードに登録 リードレコードタイプ表示の初期値がOFF
 * lx2.1 2020.01.xx SV_DEV-1092 2.0.2アップデート後にカスタム設定のリード関連デフォルト値が変更され、リードのTodo件名のデフォルト「名刺交換」が空白値になる。
 */

global with sharing class SB_NameCard_LeadRegist
{
    global static final Integer SEARCHTYPE_EMAIL = 1;
    global static final Integer SEARCHTYPE_NAME  = 2;

    global class LeadRegistException extends Exception {}


    // SmartVisca設定
    global class SvConfig
    {
        global Map<String, Boolean> disp { get; private set; }
        private Map<String, Boolean> confMap = new Map<String, Boolean>();
        //private String todoSubject = '名刺交換';
        private String todoSubject = System.Label.SB_NCLD_Text_BusinessCardExchange;
        private String todoSubjectL = System.Label.SB_NCLD_Text_BusinessCardExchange;
        private Boolean registTodo;
        private Boolean registTodoL;

        private SmartViscaf__NameCardBasicSetting__c baseSetting;

        global SmartViscaf__SmartViscaConfig__c config { get; private set; }

        global SvConfig()
        {
            SmartViscaf__SmartViscaConfig__c conf = SmartViscaf__SmartViscaConfig__c.getInstance(UserInfo.getUserId());
            if (conf.Id == null) conf = SmartViscaf__SmartViscaConfig__c.getInstance(UserInfo.getProfileId());
            if (conf.Id == null) conf = SmartViscaf__SmartViscaConfig__c.getOrgDefaults();
            baseSetting = SmartViscaf.SB_NameCard_BasicSetting.getNameCardBasicSetting();

            config = conf;

            // SV_DEV-747 リード拡張パッケージのカスタム設定：リードに登録 リードレコードタイプ表示の初期値がOFF
            List<String> keyList = new List<String> {'Company', 'State', 'Title', 'Email', 'LastModifiedDate', 'Owner', 'LeadRectype'};
            this.disp = new Map<String, Boolean>();
            this.setBoolMap(keyList, this.disp, conf, 'Disp');

            keyList = new List<String> {'Overwrite', 'RegistTodo', 'DefaultShowLeadListNoExsiting'};
            this.setBoolMap(keyList, this.confMap, conf, null);

            // SV_DEV-1092 SmartVisca基本設定から読み込むよう修正
            //if (conf.Id != null && conf.get('LeadRegist_DispCompany__c') != null) {
            //    this.todoSubject = conf.LeadRegist_TodoSubject__c; // defined in Lead Package
            //}
            if (baseSetting.SmartViscaf__RegistToDoSubject__c != null) {
              this.todoSubject = baseSetting.SmartViscaf__RegistToDoSubject__c;
            }
            if (baseSetting.SmartViscaf__RegistLeadToDoSubject__c != null) {
              this.todoSubjectL = baseSetting.SmartViscaf__RegistLeadToDoSubject__c;
            }
            registTodo = !baseSetting.SmartViscaf__RegistNoToDo__c;       //登録"しない"フラグなので読み替え
            registTodoL = !baseSetting.SmartViscaf__RegistLeadNoToDo__c;  //登録"しない"フラグなので読み替え
        }

        private void setBoolMap(List<String> keyList, Map<String, Boolean> bMap, SmartViscaf__SmartViscaConfig__c conf, String keyPrefix)
        {
            if (conf.Id == null) {
                for (String key : keyList) {
                    bMap.put(key, true);
                }
            } else {
                if (String.isBlank(keyPrefix)) keyPrefix = '';
                Boolean b;
                for (String key : keyList) {
                    b = (Boolean)conf.get('LeadRegist_'+keyPrefix+key+'__c');
                    if (b == null) b = true;
                    bMap.put(key, b);
                }
            }
        }

        // SV_DEV-747 リード拡張パッケージのカスタム設定：リードに登録 リードレコードタイプ表示の初期値がOFF
        global Boolean leadRectype()
        {
            System.debug(this.confMap);
            return this.disp.get('LeadRectype');
        }

        global Boolean overwrite()
        {
            return this.confMap.get('Overwrite');
        }

        global String todoSubject()
        {
            return this.todoSubject;
        }

        global String todoSubjectL()
        {
            return this.todoSubjectL;
        }

        global Boolean registTodo()
        {
            // SV_DEV-1092 SmartVisca基本設定から読み込むよう修正
            //return this.confMap.get('RegistTodo');
            return this.registTodo;
        }

        global Boolean registTodoL()
        {
            return this.registTodoL;
        }

        global Boolean defaultDisplayExistingLead()
        {
            return this.confMap.get('DefaultShowLeadListNoExsiting');
        }
    }

    // インスタンス化させない
    private SB_NameCard_LeadRegist() {}

    //ラベル変更
    global static String changeleadlabel(String str)
    {
        return '';
    }

    // SmartVisca設定
    global static SvConfig svConfig
    {
        get {
            return (svConfig == null) ? new SvConfig() : svConfig;
        }
    }

    // ToDoの状況値
    global static Map<String, String> todoStatusMap
    {
        get {
            if (todoStatusMap != null) return todoStatusMap;

            todoStatusMap = new Map<String, String>();

            for (TaskStatus ts : [SELECT MasterLabel, IsDefault, IsClosed FROM TaskStatus WHERE IsDefault = true OR IsClosed = true]) {
                if (ts.IsDefault) todoStatusMap.put('IsDefault', ts.MasterLabel);
                if (ts.IsClosed) todoStatusMap.put('IsClosed', ts.MasterLabel);
            }
            return todoStatusMap;
        }
    }

    // 検索条件
    global static List<SelectOption> getSearchTypeList()
    {
        List<SelectOption> opts = new List<SelectOption>();

        //opts.add(new SelectOption(String.valueOf(SEARCHTYPE_EMAIL), 'メールアドレス'));
        //opts.add(new SelectOption(String.valueOf(SEARCHTYPE_NAME),  '氏名'));
        opts.add(new SelectOption(String.valueOf(SEARCHTYPE_EMAIL), System.Label.SB_NCLD_Label_Email));
        opts.add(new SelectOption(String.valueOf(SEARCHTYPE_NAME),  System.Label.SB_NCLD_Label_Name));

        return opts;
    }

    // 名刺
    global static SmartViscaf__NameCard__c getNameCard(Id ncId)
    {
        List<SmartViscaf__NameCard__c> selectedNcList = new List<SmartViscaf__NameCard__c> { new SmartViscaf__NameCard__c(Id=ncId) };
        List<SmartViscaf__NameCard__c> ncList = getNameCardList(selectedNcList);
        if (ncList.size() <= 0) return null;
        return ncList[0];
    }

    // 名刺リスト
    global static List<SmartViscaf__NameCard__c> getNameCardList(List<SmartViscaf__NameCard__c> selectedNcList)
    {
        List<SmartViscaf__NameCard__c> ncList = new List<SmartViscaf__NameCard__c>();
        //SV_DEV-175 リード登録時にキャンペーン内での状況を選択 キャンペーンのStatusクエリ
        for (SmartViscaf__NameCard__c nc : [SELECT Id, Name, OwnerId, Owner.IsActive,SmartViscaf__account__c,
                SmartViscaf__zip_code__c, SmartViscaf__address_pref__c, SmartViscaf__address__c,
                SmartViscaf__address_bld__c, SmartViscaf__address_eng__c,
                SmartViscaf__company_name__c, SmartViscaf__web_url1__c, SmartViscaf__tel1__c, SmartViscaf__fax1__c,
                SmartViscaf__division__c, SmartViscaf__title_name__c,
                SmartViscaf__person_name_last__c, SmartViscaf__person_name_first__c, SmartViscaf__last_name__c, SmartViscaf__first_name__c,
                SmartViscaf__email__c, SmartViscaf__mobile__c, SmartViscaf__lead__c, campaign__c, SmartViscaf__contact__c,campaign__r.Status,
                SmartViscaf__list_name__c, SmartViscaf__memo__c, SmartViscaf__freehandmemo__c, SmartViscaf__card_exchange_date__c
                FROM SmartViscaf__NameCard__c WHERE Id IN :selectedNcList]) {
            ncList.add(nc);
        }
        return ncList;
    }

    // リードSOQL文 (SEARCHTYPE_EMAIL)
    global static void setEmailSoql(Map<Integer, String> soqlMap, List<Id> emailIdList, List<String> emailList, List<SmartViscaf__NameCard__c> ncList)
    {
        for (SmartViscaf__NameCard__c nc : ncList) {
            if (nc.SmartViscaf__lead__c != null)             emailIdList.add(nc.SmartViscaf__lead__c);
            if (String.isNotBlank(nc.SmartViscaf__email__c)) emailList.add(nc.SmartViscaf__email__c);
        }

        List<String> whereList = new List<String>();
        if (emailIdList.size() > 0) whereList.add('Id IN :emailIdList');
        if (emailList.size() > 0)   whereList.add('Email IN :emailList');

        soqlMap.put(SEARCHTYPE_EMAIL, getSoql(whereList));
    }

    //************************************************************************************************************
    //未使用。global なので消せないので定義だけ残す。
    // リードSOQL文 (SEARCHTYPE_NAME)
    global static void setNameSoql(Map<Integer, String> soqlMap, List<Id> nameIdList, Set<String> nameSet, List<SmartViscaf__NameCard__c> ncList)
    {
        /************************************************************************************************************/
        //String name;

        //for (SmartViscaf__NameCard__c nc : ncList) {
        //    if (nc.SmartViscaf__lead__c != null) nameIdList.add(nc.SmartViscaf__lead__c);

        //    if ((name = getPersonName(nc)) != null) {
        //        String str = EncodingUtil.urlEncode(name,'UTF-8');
        //        Blob b = Blob.valueOf(str);
        //        String b64 = EncodingUtil.base64Encode(b);
        //        name = name.replaceAll('\'', b64);
        //        name = String.escapeSingleQuotes(name.replaceAll('＼','_'));
        //        name = name.replaceAll(b64, '\'');
        //        nameSet.add(name);

        //        //if (name.startsWith(' '))    nameSet.add('%'+name); // 名のみ
        //        //else if (name.endsWith(' ')) nameSet.add(name+'%'); // 姓のみ
        //    }
        //}
        //List<String> whereList = new List<String>();
        //if (nameIdList.size() > 0)  whereList.add('Id IN :nameIdList');
        //if (nameSet.size() > 0) whereList.add('Name LIKE :nameSet');

        //soqlMap.put(SEARCHTYPE_NAME, getSoql(whereList));
    }

    global static void setLastFirstNameSoql(Map<Integer, String> soqlMap, List<Id> nameIdList, Set<String> nameSet,Set<String> lastnameSet,Set<String> firstnameSet, List<SmartViscaf__NameCard__c> ncList)
    {
        String lastName;
        String firstName;

        for (SmartViscaf__NameCard__c nc : ncList) {
            if (nc.SmartViscaf__lead__c != null) {
                nameIdList.add(nc.SmartViscaf__lead__c);
            }
            //SV_DEV-681
            //Lead一括登録での候補検索時の姓、名の文字列のエスケープは完全一致なので、不要では。
            if ((lastName = getPersonLastName(nc)) != null) {
                // String str = EncodingUtil.urlEncode(lastName,'UTF-8');
                // Blob b = Blob.valueOf(str);
                // String b64 = EncodingUtil.base64Encode(b);
                // lastName = lastName.replaceAll('\'', b64);
                // lastName = String.escapeSingleQuotes(lastName.replaceAll('＼','_'));
                // lastName = lastName.replaceAll(b64, '\'');
                lastnameSet.add(lastName);
                //if (name.startsWith(' '))    nameSet.add('%'+name); // 名のみ
                //else if (name.endsWith(' ')) nameSet.add(name+'%'); // 姓のみ
            }
            if ((firstName = getPersonFirstName(nc)) != null) {
                // String str = EncodingUtil.urlEncode(firstName,'UTF-8');
                // Blob b = Blob.valueOf(str);
                // String b64 = EncodingUtil.base64Encode(b);
                // firstName = firstName.replaceAll('\'', b64);
                // firstName = String.escapeSingleQuotes(firstName.replaceAll('＼','_'));
                // firstName = firstName.replaceAll(b64, '\'');
                firstnameSet.add(firstName);
                //if (name.startsWith(' '))    nameSet.add('%'+name); // 名のみ
                //else if (name.endsWith(' ')) nameSet.add(name+'%'); // 姓のみ
            }
        }

        List<String> whereList = new List<String>();
        if (nameIdList.size() > 0)  {
            whereList.add('Id IN :nameIdList');
        }
        String str = '';
        if (lastnameSet.size() > 0) {
            str += ' LastName = :lastnameSet ';
            if (firstnameSet.size() > 0){
                str = '(' + str + ' AND FirstName = :firstnameSet' + ')';
            }
        } else if (firstnameSet.size() > 0){
                str = 'FirstName = :firstnameSet';
        }
        if (String.isNotBlank(str)) {
            whereList.add(str);
        }
        System.debug(firstnameSet);
        System.debug(lastnameSet);
        System.debug(whereList.size());
        System.debug(getSoql(whereList));
        soqlMap.put(SEARCHTYPE_NAME, getSoql(whereList));
    }

    // リードSOQL文
    global static String getSoql(List<String> whereList)
    {
        if (whereList == null || whereList.size() <= 0) return null;

        String soqlWhere = '';
        for (String s : whereList) soqlWhere += ' OR ' + s;
        soqlWhere = ' WHERE isConverted = FALSE AND (' + soqlWhere.removeStart(' OR ') + ')';

        return 'SELECT Id, Company, State,LastName,FirstName, Title, Name, Email, LastModifiedDate, OwnerId, Owner.Name FROM Lead'
            + soqlWhere
            + ' ORDER BY Company ASC NULLS LAST, State ASC NULLS LAST, Title ASC NULLS LAST, Name ASC NULLS LAST, Email ASC NULLS LAST';
    }

        // 名刺の姓
    global static String getPersonLastName(SmartViscaf__NameCard__c nc)
    {
        Map<String, String> pnMap = SmartViscaf.SB_NameCard_Util.getPersonName(nc);

        if (String.isBlank(pnMap.get('last_name'))) {
           return null;
        }
        return pnMap.get('last_name');
    }

       // 名刺の名
    global static String getPersonFirstName(SmartViscaf__NameCard__c nc)
    {
        Map<String, String> pnMap = SmartViscaf.SB_NameCard_Util.getPersonName(nc);

        if (String.isBlank(pnMap.get('first_name'))) {
            return null;
        }
        return pnMap.get('first_name'); // 姓名
    }

    // 名刺の姓名
    global static String getPersonName(SmartViscaf__NameCard__c nc)
    {
        Map<String, String> pnMap = SmartViscaf.SB_NameCard_Util.getPersonName(nc);

        if (String.isBlank(pnMap.get('last_name'))) {
            if (String.isBlank(pnMap.get('first_name'))) return null;
            return pnMap.get('first_name'); // 名のみ
        }
        if (String.isBlank(pnMap.get('first_name'))) {
            return pnMap.get('last_name'); // 姓のみ
        }

        return pnMap.get('last_name')+' '+pnMap.get('first_name'); // 姓名

    }

    // リード recordtype設定追加
    global static Lead getLead(Id leadId, SmartViscaf__NameCard__c nc, Id ownerId, Id recordtype)
    {
        Lead lead1;
        if (String.isNotBlank(recordtype)) {
            lead1 = (Lead)Lead.sObjectType.newSObject(recordtype, false);
            lead1.put('RecordTypeId',recordtype);
        }
        else {
            lead1 = (Lead)Lead.sObjectType.newSObject(null, false);
        }
        lead1.id = leadId;

        lead1.PostalCode = nc.SmartViscaf__zip_code__c;
        lead1.State = nc.SmartViscaf__address_pref__c;

        Map<String, String> adMap = SmartViscaf.SB_NameCard_Util.getAddress(nc);
        lead1.City = adMap.get('city');
        lead1.Street = adMap.get('street');

        lead1.Company = nc.SmartViscaf__company_name__c;
        lead1.Website = nc.SmartViscaf__web_url1__c;
        lead1.Phone = nc.SmartViscaf__tel1__c;
        lead1.Fax = nc.SmartViscaf__fax1__c;
        lead1.Title = nc.SmartViscaf__title_name__c;

        Map<String, String> pnMap = SmartViscaf.SB_NameCard_Util.getPersonName(nc);
        lead1.LastName = pnMap.get('last_name');
        lead1.FirstName = pnMap.get('first_name');

        lead1.Email = nc.SmartViscaf__email__c;
        lead1.MobilePhone = nc.SmartViscaf__mobile__c;

        lead1.NameCard__c = nc.Id;
        lead1.NameCardListName__c = nc.SmartViscaf__list_name__c;
        lead1.NameCardMemo__c = nc.SmartViscaf__memo__c;
        lead1.NameCardFreehandmemo__c = nc.SmartViscaf__freehandmemo__c;
        if (ownerId != null) lead1.OwnerId = ownerId;

        return lead1;
    }

    // SV_DEV-568 リード拡張パッケージ v1.11 追加、更新 package.xml
    //GlobalクラスのGlobalメソッドが削除されていたため、古いglobalメッソドを残します
    global static Lead getLead(Id leadId, SmartViscaf__NameCard__c nc, Id ownerId)
    {
        //レコードタイプを対応したため、パラメータを追加する必要です
        //global static Lead getLead(Id leadId, SmartViscaf__NameCard__c nc, Id ownerId, Id recordtype) 
        //↑メソッドを追加このメソッドを廃棄します、globalのため削除できません
        return null;
        //Lead lead = new Lead(Id=leadId);

        //lead.PostalCode = nc.SmartViscaf__zip_code__c;
        //lead.State = nc.SmartViscaf__address_pref__c;

        //Map<String, String> adMap = SmartViscaf.SB_NameCard_Util.getAddress(nc);
        //lead.City = adMap.get('city');
        //lead.Street = adMap.get('street');

        //lead.Company = nc.SmartViscaf__company_name__c;
        //lead.Website = nc.SmartViscaf__web_url1__c;
        //lead.Phone = nc.SmartViscaf__tel1__c;
        //lead.Fax = nc.SmartViscaf__fax1__c;
        //lead.Title = nc.SmartViscaf__title_name__c;

        //Map<String, String> pnMap = SmartViscaf.SB_NameCard_Util.getPersonName(nc);
        //lead.LastName = pnMap.get('last_name');
        //lead.FirstName = pnMap.get('first_name');

        //lead.Email = nc.SmartViscaf__email__c;
        //lead.MobilePhone = nc.SmartViscaf__mobile__c;

        //lead.NameCard__c = nc.Id;
        //lead.NameCardListName__c = nc.SmartViscaf__list_name__c;
        //lead.NameCardMemo__c = nc.SmartViscaf__memo__c;
        //lead.NameCardFreehandmemo__c = nc.SmartViscaf__freehandmemo__c;
        //if (ownerId != null) lead.OwnerId = ownerId;

        //return lead;
    }

    // ToDo
    global static Task getTodo(Id leadId, Id ownerId, String subject, Date cardExchangeDate)
    {
        Task todo = new Task(WhoId=leadId, Subject=subject, ActivityDate=cardExchangeDate, OwnerId=ownerId);

        if (todo.ActivityDate == null || todo.ActivityDate <= Date.today()) {
            todo.Status = todoStatusMap.get('IsClosed'); // 完了
        } else {
            todo.Status = todoStatusMap.get('IsDefault'); // 未着手
        }
        return todo;
    }
     // ToDoコメント付き
    global static Task getTodo(Id leadId, Id ownerId, String subject, Date cardExchangeDate,String description)
    {
        Task todo = new Task(WhoId=leadId, Subject=subject, ActivityDate=cardExchangeDate, OwnerId=ownerId,Description = description);

        if (todo.ActivityDate == null || todo.ActivityDate <= Date.today()) {
            todo.Status = todoStatusMap.get('IsClosed'); // 完了
        } else {
            todo.Status = todoStatusMap.get('IsDefault'); // 未着手
        }
        return todo;
    }
}