sfdx-source/SmartVisca/main/default/objects/Account/fields/NameCard__c.field-meta.xml
<CustomField>
    <fullName>NameCard__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>名刺</label>
    <referenceTo>NameCard__c</referenceTo>
    <relationshipLabel>取引先</relationshipLabel>
    <relationshipName>AccountNameCards</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/Contact/fields/NameCard__c.field-meta.xml
<CustomField>
    <fullName>NameCard__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>名刺</label>
    <referenceTo>NameCard__c</referenceTo>
    <relationshipLabel>取引先責任者</relationshipLabel>
    <relationshipName>ContactNameCards</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>NameCard__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>名刺</label>
        <referenceTo>SmartViscaf__NameCard__c</referenceTo>
        <relationshipLabel>リード</relationshipLabel>
        <relationshipName>NameCards</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

sfdx-source/unpackaged/dev-config/main/default/objects/NameCard__c/NameCard__c.object-meta.xml
<CustomObject>
    <customHelpPage>SB_NameCard_UserGuide</customHelpPage>
    <description>スキャナから取り込んだ名刺情報がここに保存されます。
Business Card: Stores digitized business card information.</description>
    <label>名刺</label>
    <nameField>
        <label>氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SmartViscaf__NameCard__c.object
<CustomObject>
    <fields>
        <fullName>campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>キャンペーン</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>名刺</relationshipLabel>
        <relationshipName>nc_campaign</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

sfdx-source/unpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__account__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>名刺</relationshipLabel>
    <relationshipName>nc_account</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/unpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__company_name__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__company_name__c</fullName>
    <label>会社名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__contact__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>取引先責任者</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>名刺</relationshipLabel>
    <relationshipName>nc_contact</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/unpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__delivery_type__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__delivery_type__c</fullName>
    <inlineHelpText>1: 一次納品
2: 最終納品</inlineHelpText>
    <label>納品タイプ</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__division__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__division__c</fullName>
    <label>所属</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__email__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__email__c</fullName>
    <label>メールアドレス</label>
    <type>Email</type>
</CustomField>

sfdx-source/unpackaged - コピー/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__first_name__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__first_name__c</fullName>
    <description>英語名刺の場合</description>
    <label>ファーストネーム</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__last_name__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__last_name__c</fullName>
    <description>英語名刺の場合</description>
    <label>ラストネーム</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__lead__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>リード</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>名刺</relationshipLabel>
    <relationshipName>nc_lead</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__person_name_first__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__person_name_first__c</fullName>
    <label>名</label>
    <length>127</length>
    <type>Text</type>
</CustomField>

sfdx-source/unpackaged - コピー/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__person_name_last__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__person_name_last__c</fullName>
    <label>姓</label>
    <length>127</length>
    <type>Text</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__title_name__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__title_name__c</fullName>
    <label>役職</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/unpackaged/dev-config/main/default/objects/SmartViscaf__NameCardBasicSetting__c/SmartViscaf__NameCardBasicSetting__c.object-meta.xml
<CustomObject>
    <label>名刺基本設定</label>
    <nameField>
        <label>基本設定</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

sfdx-source/unpackaged - コピー/main/default/objects/SmartViscaf__NameCardBasicSetting__c/fields/SmartViscaf__RenkeiAccountOverwrite__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__RenkeiAccountOverwrite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>自動連携:既存の取引先を上書きする</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/unpackaged - コピー/main/default/objects/SmartViscaf__NameCardBasicSetting__c/fields/SmartViscaf__RenkeiActive__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__RenkeiActive__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>名刺データが2次納品された時に取引先・取引先責任者を自動で作成したり更新したりすることができます。「SmartVisca連携設定」タブで連携する条件の設定をします。リード拡張パッケージがインストールされている場合、取引先・取引先責任者に加えてリードを作成・更新できます。</inlineHelpText>
    <label>自動連携:自動連携機能を有効化</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/unpackaged - コピー/main/default/objects/SmartViscaf__NameCardBasicSetting__c/fields/SmartViscaf__RenkeiActiveCampaignMember__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__RenkeiActiveCampaignMember__c</fullName>
    <defaultValue>false</defaultValue>
    <description>自動連携で作成・更新した人をキャンペーンメンバーにする。</description>
    <label>自動連携:スキャン時選択したキャンペーンのメンバーにする</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/unpackaged/main/default/objects/SmartViscaf__NameCardBasicSetting__c/fields/SmartViscaf__RenkeiCampaignStatus__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__RenkeiCampaignStatus__c</fullName>
    <label>自動連携:キャンペーンの状況</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/unpackaged/main/default/objects/SmartViscaf__NameCardBasicSetting__c/fields/SmartViscaf__RenkeiContactOverwrite__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__RenkeiContactOverwrite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>自動連携:既存の取引先責任者を上書きする</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/unpackaged - コピー/main/default/objects/SmartViscaf__NameCardBasicSetting__c/fields/SmartViscaf__RenkeiCreateContactOnAcountWithLead__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__RenkeiCreateContactOnAcountWithLead__c</fullName>
    <defaultValue>false</defaultValue>
    <label>自動連携:リード、取引先既存で取引先責任者を作成する</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCardBasicSetting__c/fields/SmartViscaf__RenkeiCreateContactOnAcountWithoutLead__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__RenkeiCreateContactOnAcountWithoutLead__c</fullName>
    <defaultValue>false</defaultValue>
    <label>自動連携:リードなく、取引先既存で取引先責任者を作成する</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCardBasicSetting__c/fields/SmartViscaf__RenkeiCreateLeadOnTooManyAccounts__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__RenkeiCreateLeadOnTooManyAccounts__c</fullName>
    <defaultValue>false</defaultValue>
    <label>自動連携:既存取引先が複数あり特定できないとき、リードを作る</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCardBasicSetting__c/fields/SmartViscaf__RenkeiLeadActive__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__RenkeiLeadActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>自動連携におけるリード登録機能 を有効化する。リード登録機能 はリード拡張パッケージの機能だが、設定は基本パッケージ内に持つ</description>
    <label>自動連携:リード登録機能を有効化</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCardBasicSetting__c/fields/SmartViscaf__RenkeiLeadOverwrite__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__RenkeiLeadOverwrite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>自動連携:既存のリードを上書きする</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/unpackaged/main/default/objects/SmartViscaf__NameCardBasicSetting__c/fields/SmartViscaf__RenkeiUpdateAllLeadsOnCondition__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__RenkeiUpdateAllLeadsOnCondition__c</fullName>
    <defaultValue>false</defaultValue>
    <label>自動連携:条件に合致する既存リードは全て更新する</label>
    <type>Checkbox</type>
</CustomField>

src/objects/SmartViscaf__SmartViscaConfig__c.object
<CustomObject>
    <fields>
        <fullName>RenkeiContactToCampaignMember__c</fullName>
        <defaultValue>false</defaultValue>
        <description>リード用自動連携:キャンペーンIDが指定されていたとき、（作成、あるいは更新したとき）リードに加え取引先責任者もキャンペーンメンバーにする。</description>
        <inlineHelpText>リード用自動連携:キャンペーンIDが指定されていたとき、（作成、あるいは更新したとき）リードに加え取引先責任者もキャンペーンメンバーにする。</inlineHelpText>
        <label>リード用自動連携:取引先責任者もキャンペーンメンバーにする</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RenkeiCreateContactOnAcountWithLead__c</fullName>
        <defaultValue>false</defaultValue>
        <description>リード用自動連携:リードと取引先が既存で取引先が特定できて取引先責任者レコードがない場合、取引先責任者を作成する。</description>
        <inlineHelpText>リード用自動連携:リードと取引先が既存で取引先が特定できて取引先責任者レコードがない場合、取引先責任者を作成する。</inlineHelpText>
        <label>リード用自動連携:リード、取引先既存で取引先責任者を作成する【移行済】</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RenkeiCreateContactOnAcountWithoutLead__c</fullName>
        <defaultValue>false</defaultValue>
        <description>リード用自動連携:該当するリードはなく、取引先が既存で取引先が特定できて取引先責任者レコードがない場合、取引先責任者を作成する。このときリードは作らない。</description>
        <inlineHelpText>リード用自動連携:該当するリードはなく、取引先が既存で取引先が特定できて取引先責任者レコードがない場合、取引先責任者を作成する。このときリードは作らない。</inlineHelpText>
        <label>リード用自動連携:リードなく、取引先既存で取引先責任者を作成する【移行済】</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RenkeiCreateLeadOnTooManyAccounts__c</fullName>
        <defaultValue>false</defaultValue>
        <description>リード用自動連携:名刺に合致する既存の取引先が複数あり特定できないとき、リードを作る。</description>
        <inlineHelpText>リード用自動連携:名刺に合致する既存の取引先が複数あり特定できないとき、リードを作る。</inlineHelpText>
        <label>リード用自動連携:既存取引先が複数あり特定できないとき、リードを作る【移行済】</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RenkeiUpdateAllLeadsOnCondition__c</fullName>
        <defaultValue>false</defaultValue>
        <description>リード用自動連携:（上書き設定時）該当するリード複数を更新する。オフの場合、該当するリードが複数あったときは更新しない。</description>
        <inlineHelpText>リード用自動連携:（上書き設定時）該当するリード複数を更新する。オフの場合、該当するリードが複数あったときは更新しない。</inlineHelpText>
        <label>リード用自動連携:条件に合致する既存リードは全て更新する【移行済】</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RenkeiUpdateToCampaignMember__c</fullName>
        <defaultValue>false</defaultValue>
        <description>リード用自動連携:キャンペーンIDが指定されていたとき、作成に加え更新でもキャンペーンメンバーにする。</description>
        <inlineHelpText>リード用自動連携:キャンペーンIDが指定されていたとき、作成に加え更新でもキャンペーンメンバーにする。</inlineHelpText>
        <label>リード用自動連携:更新でもキャンペーンメンバーにする</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

sfdx-source/SmartViscal/main/default/classes/SB_NameCardL_RegistQueryStrategyTest.cls
/**
 *
 *  SB_NameCardL_RegistQueryStrategyTest
 *  SB_NameCardL_RegistQueryStrategyテストクラス
 *
 * Copyright (C) 2018 SunBridge Inc. All Rights Reserved.
 *
 *  @author sawano
 *  @Version 1      2018.4.xx
 *  @Version 2.1    2020.07.xx SV_DEV-1970 カスタム設定からSmartVisca基本設定に移行対応
 *
 **/
@isTest
private class SB_NameCardL_RegistQueryStrategyTest
{

  public virtual class TestDb extends SB_NCL_TestDB {

    public override void initializeSmartViscaConfig() {
      svConfig = SmartViscaf__SmartViscaConfig__c.getOrgDefaults();
      svConfig.SmartViscaf__TriggerLeadExRenkeiTriggerHandler__c = true; // 2018.03.xx v1.22  Lead連携拡張パッケージの中にある 自動連携のトリガハンドラを呼ぶ
      // Lead 拡張パッケージ v2.0 からの項目
      svConfig.RenkeiCreateContactOnAcountWithoutLead__c = true; // デフォルト false 統合版自動連携:リードなく、取引先既存で取引先責任者を作成する
      svConfig.RenkeiCreateContactOnAcountWithLead__c = true;  // デフォルト false 統合版自動連携:リード、取引先既存で取引先責任者を作成する
      svConfig.RenkeiCreateLeadOnTooManyAccounts__c = false;  // デフォルト false 統合版自動連携: 既存取引先が複数あり特定できないとき、リードを作る。
      svConfig.RenkeiContactToCampaignMember__c = false;  // デフォルト false 統合版自動連携: 取引先責任者もキャンペーンメンバーにする。
      svConfig.RenkeiUpdateToCampaignMember__c = false; // デフォルト false 統合版自動連携: 更新でもキャンペーンメンバーにする。
      svConfig.RenkeiUpdateAllLeadsOnCondition__c = true; // デフォルト true 統合版自動連携:条件に合致する既存リードは全て更新する。
    }

    // 名刺基本設定
    public override void initializeBasicSetting() {
      SmartViscaf__NameCardBasicSetting__c bs = SmartViscaf.SB_NC_PostInstallScript.createDefaultBasicSetting();
      bs.SmartViscaf__RenkeiActive__c = true;      // 自動連携機能有効
      bs.SmartViscaf__RenkeiLeadActive__c = true; // リード連携を有効化
      bs.SmartViscaf__RenkeiActiveCampaignMember__c = false; // キャンペンメンバー
      //bs.SmartViscaf__RenkeiCampaignStatus__c = SB_NameCardL_Util.getDefaultCampaignStatus(); // キャンペーンメンバーの状況
      bs.SmartViscaf__RenkeiAccountOverwrite__c = true;   // 既存の取引先を上書き
      bs.SmartViscaf__RenkeiContactOverwrite__c = true;   // 既存の取引先責任者を上書き
      bs.SmartViscaf__RenkeiLeadOverwrite__c = true;   // 既存のリードを上書き
      // SV_DEV-1970 カスタム設定からSmartVisca基本設定に移行
      bs.SmartViscaf__RenkeiCreateContactOnAcountWithoutLead__c = true; // デフォルト false 統合版自動連携:リードなく、取引先既存で取引先責任者を作成する
      bs.SmartViscaf__RenkeiCreateContactOnAcountWithLead__c = true;  // デフォルト false 統合版自動連携:リード、取引先既存で取引先責任者を作成する
      bs.SmartViscaf__RenkeiCreateLeadOnTooManyAccounts__c = false;  // デフォルト false 統合版自動連携: 既存取引先が複数あり特定できないとき、リードを作る。
      bs.SmartViscaf__RenkeiUpdateAllLeadsOnCondition__c = true; // デフォルト true 統合版自動連携:条件に合致する既存リードは全て更新する。
      listBasicSetting.add(bs);
    }

    // アカウント
    public override void initializeAccount() {
      listAccount.add(new Account(Name='サンブリッジ株式会社', Site='開発部'));
      listAccount.add(new Account(Name='目黒商事株式会社', Site='営業部'));
    }

    ////　コンタクト
    //public override void initializeContact() {
    //  listContact.add(new Contact(AccountId=listAccount[0].Id, FirstName='太郎', LastName='恵比寿', Title='課長', Email='user01@sunbridge.com'));
    //  listContact.add(new Contact(AccountId=listAccount[1].Id, FirstName='次郎', LastName='不動前', Title='部長', Email='user01@meguro.co.jp'));
    //}

    public override void initializeLead() {
      listLead.add(new Lead(Company='サンブリッジ株式会社', FirstName='太郎', LastName='恵比寿', Title='課長', Email='user01@sunbridge.com'));
      listLead.add(new Lead(Company='目黒商事株式会社', FirstName='次郎', LastName='不動前', Title='部長', Email='user01@meguro.co.jp'));
    }

    //public void initializeCampaignMember() {
    //  listCampaignMember.add(new CampaignMember(CampaignId=listCampaign[0].Id, LeadId=listLead[0].Id, Status = SB_NameCardL_Util.getDefaultCampaignStatus()));
    //  listCampaignMember.add(new CampaignMember(CampaignId=listCampaign[0].Id, LeadId=listLead[1].Id, Status = SB_NameCardL_Util.getDefaultCampaignStatus()));
    //}

    //  名刺を追加
    public void initializeNameCard(String delivery_type) {
      listCard.add(new SmartViscaf__NameCard__c(
              Name = '恵比寿 太郎'
              , SmartViscaf__person_name_last__c = '恵比寿'
              , SmartViscaf__person_name_first__c = '太郎'
              , SmartViscaf__last_name__c = null
              , SmartViscaf__first_name__c = null
              , SmartViscaf__email__c = 'user01@sunbridge.com'
              , SmartViscaf__company_name__c= 'サンブリッジ株式会社'
              , SmartViscaf__division__c = '開発部'
              , SmartViscaf__title_name__c = '課長'
              //, SmartViscaf__account__c = listAccount[0].Id
              //, SmartViscaf__contact__c = listContact[0].Id
              //, SmartViscaf__lead__c = listLead[0].Id
              //, campaign__c = listCampaign[0].Id
              , SmartViscaf__delivery_type__c = delivery_type));
      listCard.add(new SmartViscaf__NameCard__c(
              Name = '不動前 次郎'
              , SmartViscaf__person_name_last__c = '不動前'
              , SmartViscaf__person_name_first__c = '次郎'
              , SmartViscaf__last_name__c = null
              , SmartViscaf__first_name__c = null
              , SmartViscaf__email__c = 'user01@meguro.co.jp'
              , SmartViscaf__company_name__c= '目黒商事株式会社'
              , SmartViscaf__division__c = '営業部'
              , SmartViscaf__title_name__c = '部長'
              //, SmartViscaf__account__c = listAccount[1].Id
              //, SmartViscaf__contact__c = listContact[1].Id
              //, SmartViscaf__lead__c = listLead[1].Id
              //, campaign__c = listCampaign[0].Id
              , SmartViscaf__delivery_type__c = delivery_type));
    }

    // 初期データ作成  他に影響のないものだけ
    public override void initialize() {
      // SmartVisca設定
      initializeSmartViscaConfig();
      if (svConfig !=null) {
        upsert svConfig;
      }
      //　ユーザ
      initializeUser();
      if (listUser.isEmpty() == false)
        insert listUser;
      // 名刺基本設定
      initializeBasicSetting();
      if (!listBasicSetting.isEmpty()) {
        insert listBasicSetting;
      }
      // 名刺連携項目マッピング
      initializeMapping();
      if (!listMapping.isEmpty()) {
        insert listMapping;
      }
      // アカウント
      initializeAccount();
      if (listAccount.isEmpty() == false) {
        insert listAccount;
      }
      // リード
      initializeLead();
      if (listLead.isEmpty() == false) {
        insert listLead;
      }

      // 名刺
      initializeNameCard('1');
      if (listCard.isEmpty() == false) {
        insert listCard;
      }
    }
  } // class TestDb

  @isTest
  static void test_query() {
    TestDb db = new TestDb();
    db.initialize();
    List<SmartViscaf__NameCard__c> cards = Database.query('SELECT Id, Name, SmartViscaf__email__c, SmartViscaf__delivery_type__c FROM SmartViscaf__NameCard__c');
    for (SmartViscaf__NameCard__c c : cards) {
      c.SmartViscaf__delivery_type__c = '2';
    }
    update cards;



    System.assertEquals(2, [SELECT Id, Name, SmartViscaf__account__c, SmartViscaf__contact__c, SmartViscaf__lead__c FROM SmartViscaf__NameCard__c
              WHERE SmartViscaf__account__c != null AND SmartViscaf__contact__c != null AND SmartViscaf__lead__c != null].size());

    System.assertEquals(2, [SELECT Id, Name FROM Account WHERE SmartViscaf__NameCard__c != null].size());
    System.assertEquals(2, [SELECT Id, Name FROM Contact WHERE SmartViscaf__NameCard__c != null].size());
    System.assertEquals(2, [SELECT Id, Name FROM Lead WHERE NameCard__c != null].size());

    Test.startTest();
    SB_NameCardL_RegistQueryStrategy.AccountQueryStrategy qs_a = new SB_NameCardL_RegistQueryStrategy.AccountQueryStrategy();


    SB_NameCardL_RegistQueryOption qo = new SB_NameCardL_RegistQueryOption();
    qo.queryState = true;
    qo.queryCity = true;
    qo.queryStreet = true;
    qo.queryZip = true;
    qo.queryPhone = true;
    qo.queryCompany = true;
    qo.queryDept = true;
    qo.queryUrl = true;
    qo.queryLastName = true;
    qo.queryFirstName = true;
    qo.queryEMail = true;
    qo.queryTitle = true;
    qo.queryMobile = true;

    Test.stopTest();
  }

  @isTest
  static void testLeadHojinkakuParse() {
    
    TestDb db = new TestDb();
    db.initialize();
    List<SmartViscaf__NameCard__c> cards = Database.query('SELECT Id, SmartViscaf__company_name__c FROM SmartViscaf__NameCard__c');
    for (SmartViscaf__NameCard__c c : cards) {
      c.SmartViscaf__company_name__c = '㈱' + c.SmartViscaf__company_name__c.remove('株式会社');
      c.SmartViscaf__delivery_type__c = '2';
    }

    Test.startTest();
    update cards;
    Test.stopTest();

    System.assertEquals(2, [SELECT Id, Name, SmartViscaf__account__c, SmartViscaf__contact__c, SmartViscaf__lead__c FROM SmartViscaf__NameCard__c
              WHERE SmartViscaf__account__c != null AND SmartViscaf__contact__c != null AND SmartViscaf__lead__c != null].size());
    System.assertEquals(2, [SELECT Id, Name FROM Account WHERE SmartViscaf__NameCard__c != null].size());
    System.assertEquals(2, [SELECT Id, Name FROM Contact WHERE SmartViscaf__NameCard__c != null].size());
    System.assertEquals(2, [SELECT Id, Name FROM Lead WHERE NameCard__c != null].size());

  }
}