sfdx-source/SmartVisca/main/default/objects/Account/fields/NameCard__c.field-meta.xml
<CustomField>
    <fullName>NameCard__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>名刺</label>
    <referenceTo>NameCard__c</referenceTo>
    <relationshipLabel>取引先</relationshipLabel>
    <relationshipName>AccountNameCards</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/Contact/fields/NameCard__c.field-meta.xml
<CustomField>
    <fullName>NameCard__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>名刺</label>
    <referenceTo>NameCard__c</referenceTo>
    <relationshipLabel>取引先責任者</relationshipLabel>
    <relationshipName>ContactNameCards</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/unpackaged/dev-config/main/default/objects/NameCard__c/NameCard__c.object-meta.xml
<CustomObject>
    <customHelpPage>SB_NameCard_UserGuide</customHelpPage>
    <description>スキャナから取り込んだ名刺情報がここに保存されます。
Business Card: Stores digitized business card information.</description>
    <label>名刺</label>
    <nameField>
        <label>氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/address__c.field-meta.xml
<CustomField>
    <fullName>address__c</fullName>
    <label>住所</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/address_pref__c.field-meta.xml
<CustomField>
    <fullName>address_pref__c</fullName>
    <label>都道府県</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/company_name__c.field-meta.xml
<CustomField>
    <fullName>company_name__c</fullName>
    <label>会社名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/division__c.field-meta.xml
<CustomField>
    <fullName>division__c</fullName>
    <label>所属</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/email__c.field-meta.xml
<CustomField>
    <fullName>email__c</fullName>
    <label>メールアドレス</label>
    <type>Email</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/fax1__c.field-meta.xml
<CustomField>
    <fullName>fax1__c</fullName>
    <label>FAX番号</label>
    <type>Phone</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/first_name__c.field-meta.xml
<CustomField>
    <fullName>first_name__c</fullName>
    <description>英語名刺の場合</description>
    <label>ファーストネーム</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/last_name__c.field-meta.xml
<CustomField>
    <fullName>last_name__c</fullName>
    <description>英語名刺の場合</description>
    <label>ラストネーム</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/mobile__c.field-meta.xml
<CustomField>
    <fullName>mobile__c</fullName>
    <label>携帯電話番号</label>
    <type>Phone</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/person_name_first__c.field-meta.xml
<CustomField>
    <fullName>person_name_first__c</fullName>
    <label>名</label>
    <length>127</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/person_name_last__c.field-meta.xml
<CustomField>
    <fullName>person_name_last__c</fullName>
    <label>姓</label>
    <length>127</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/tel1__c.field-meta.xml
<CustomField>
    <fullName>tel1__c</fullName>
    <label>電話番号</label>
    <type>Phone</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/tel2__c.field-meta.xml
<CustomField>
    <fullName>tel2__c</fullName>
    <label>電話番号2</label>
    <type>Phone</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/title_name__c.field-meta.xml
<CustomField>
    <fullName>title_name__c</fullName>
    <label>役職</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/web_url1__c.field-meta.xml
<CustomField>
    <fullName>web_url1__c</fullName>
    <label>URL</label>
    <type>Url</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/web_url2__c.field-meta.xml
<CustomField>
    <fullName>web_url2__c</fullName>
    <label>URL2</label>
    <type>Url</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/zip_code__c.field-meta.xml
<CustomField>
    <fullName>zip_code__c</fullName>
    <label>郵便番号</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/NameCardBasicSetting__c.object-meta.xml
<CustomObject>
    <label>名刺基本設定</label>
    <nameField>
        <label>基本設定</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RegistAccountNotOverWrite__c.field-meta.xml
<CustomField>
    <fullName>RegistAccountNotOverWrite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>取引先登録:取引先を名刺情報で上書きしない</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RegistContactNotOverWrite__c.field-meta.xml
<CustomField>
    <fullName>RegistContactNotOverWrite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>取引先登録:取引先責任者を名刺情報で上書きしない</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RegistDispAccountRectype__c.field-meta.xml
<CustomField>
    <fullName>RegistDispAccountRectype__c</fullName>
    <defaultValue>true</defaultValue>
    <label>取引先登録:取引先レコードタイプ選択を表示する</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RegistDispContactRectype__c.field-meta.xml
<CustomField>
    <fullName>RegistDispContactRectype__c</fullName>
    <defaultValue>true</defaultValue>
    <label>取引先登録:取引先責任者レコードタイプ選択を表示する</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RegistDispOverWriteCheckbox__c.field-meta.xml
<CustomField>
    <fullName>RegistDispOverWriteCheckbox__c</fullName>
    <defaultValue>true</defaultValue>
    <description>v.1.21から、オブジェクトごとに項目を設けた。未使用</description>
    <label>取引先登録:「上書きする」チェックボックスを表示する</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RegistNoToDo__c.field-meta.xml
<CustomField>
    <fullName>RegistNoToDo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>取引先登録:ToDo登録しない</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RegistToDoSubject__c.field-meta.xml
<CustomField>
    <fullName>RegistToDoSubject__c</fullName>
    <defaultValue>&apos;名刺交換&apos;</defaultValue>
    <label>取引先登録:ToDo件名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccount_Street__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccount_Street__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:町名・番地</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountAddressPref__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountAddressPref__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:都道府県</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountCity__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountCity__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:市区郡</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountCompany__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountCompany__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:取引先名</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountNOExistCreateNew__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountNOExistCreateNew__c</fullName>
    <defaultValue>true</defaultValue>
    <description>自動連携での取引先のクエリの結果既存の取引先がなければ新規作成する</description>
    <label>自動連携:既存の取引先がなければ新規作成する</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountOverwrite__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountOverwrite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>自動連携:既存の取引先を上書きする</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountPhone__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountPhone__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:電話</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountQueryRecordTypeIds__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountQueryRecordTypeIds__c</fullName>
    <description>自動連携で既存の取引先を検索するときの対象とするレコードタイプ。</description>
    <label>自動連携:自動連携で検索対象の取引先レコードタイプ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountRecordTypes__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountRecordTypes__c</fullName>
    <label>自動連携:取引先レコードタイプ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountSite__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountSite__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:取引先 部門</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountSitePartialMatch__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountSitePartialMatch__c</fullName>
    <defaultValue>false</defaultValue>
    <label>自動連携:部署は部分一致検索</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountURL__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountURL__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:Web サイト</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountZipCode__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountZipCode__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:郵便番号</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiActive__c.field-meta.xml
<CustomField>
    <fullName>RenkeiActive__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>名刺データが2次納品された時に取引先・取引先責任者を自動で作成したり更新したりすることができます。「SmartVisca連携設定」タブで連携する条件の設定をします。リード拡張パッケージがインストールされている場合、取引先・取引先責任者に加えてリードを作成・更新できます。</inlineHelpText>
    <label>自動連携:自動連携機能を有効化</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiContactFirstName__c.field-meta.xml
<CustomField>
    <fullName>RenkeiContactFirstName__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:名</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiContactLastName__c.field-meta.xml
<CustomField>
    <fullName>RenkeiContactLastName__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:姓</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiContactMail__c.field-meta.xml
<CustomField>
    <fullName>RenkeiContactMail__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:メールアドレス</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiContactNOExistCreateNew__c.field-meta.xml
<CustomField>
    <fullName>RenkeiContactNOExistCreateNew__c</fullName>
    <defaultValue>false</defaultValue>
    <description>自動連携での取引先をひもづけて、その取引先に名刺に相当する取引先責任者がなければ作成する。</description>
    <inlineHelpText>自動連携での取引先をひもづけて、その取引先に名刺に相当する取引先責任者がなければ作成する。</inlineHelpText>
    <label>自動連携:既存の取引先責任者がなければ新規作成する</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiContactOverwrite__c.field-meta.xml
<CustomField>
    <fullName>RenkeiContactOverwrite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>自動連携:既存の取引先責任者を上書きする</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiContactQueryRecordTypeIds__c.field-meta.xml
<CustomField>
    <fullName>RenkeiContactQueryRecordTypeIds__c</fullName>
    <description>自動連携で既存の取引先責任者を検索するときの対象とするレコードタイプ。</description>
    <label>自動連携:自動連携で検索対象の取引先責任者レコードタイプ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiContactRecordTypes__c.field-meta.xml
<CustomField>
    <fullName>RenkeiContactRecordTypes__c</fullName>
    <label>自動連携:取引先責任者レコードタイプ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiExcludeHojinkaku__c.field-meta.xml
<CustomField>
    <fullName>RenkeiExcludeHojinkaku__c</fullName>
    <defaultValue>true</defaultValue>
    <description>自動連携で既存取引先の検索で、会社名は法人格を除いて中間一致検索する</description>
    <label>自動連携:取引先名は法人格を除いて検索</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiExcludeHojinkakuPartial__c.field-meta.xml
<CustomField>
    <fullName>RenkeiExcludeHojinkakuPartial__c</fullName>
    <defaultValue>false</defaultValue>
    <label>自動連携:取引先名は法人格を除いて部分一致検索</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiSpecificItems__c.field-meta.xml
<CustomField>
    <fullName>RenkeiSpecificItems__c</fullName>
    <inlineHelpText>他の条件に加え、取込時にセットしたメモ（手書きメモではありません）の内容と、『指定項目』の文字列が一致した場合に同一の取引先とみなします。</inlineHelpText>
    <label>自動連携:指定項目</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/SaishinInheritValues__c.field-meta.xml
<CustomField>
    <fullName>SaishinInheritValues__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>同じ人の名刺（同一の姓、名、メールアドレス）が複数ある場合、２次納品のとき、名刺交換日をもとに最新の名刺を判定します。最新の名刺に変更があった場合、新しい最新の名刺に、お客様が名刺オブジェクトに追加したカスタム項目の値を引継ぐことが可能です。この機能は、追加したカスタム項目がない場合、選択できません。</inlineHelpText>
    <label>最新の名刺が値を引継ぐ機能:有効化</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/classes/SB_NameCard_RenkeiTargetsPickerTest.cls
/**
 *
 * SB_NameCard_RenkeiTargetsPickerTest
 *  自動連携機能で、対象のアカウント、コンタクト、リードなどを抽出する Helperクラス SB_NameCard_RenkeiTargetsPicker のテストクラス
 *
 * Copyright (C) 2017 SunBridge Inc. All Rights Reserved.
 *
 *  @author sawano
 *  @Version 1      2017.02.xx
 *
 **/
 @isTest
 private class SB_NameCard_RenkeiTargetsPickerTest
 {

  // アカウント、コンタクトの絞込はシンプルな条件でテストするよう
  public virtual class TestDb extends SB_NC_TestDB {

    public virtual override void initializeBasicSetting() {
      NameCardBasicSetting__c bs = SB_NC_PostInstallScript.createDefaultBasicSetting();
      //bs.RenkeiContactFirstName__c = false; // コンタクト 名
      bs.RenkeiAccountOverwrite__c = true;  // 既存の取引先を上書き
      bs.RenkeiContactOverwrite__c = true;   // 既存の取引先責任者を上書き
      //NameCardBasicSetting__c bs = new NameCardBasicSetting__c(
      //  RenkeiActive__c = false,      // 自動連携機能有効
      //  RenkeiAccountAddressPref__c = false,   // アカウント 都道府県
      //  RenkeiAccount_Street__c = false,   // アカウント 町名・番地
      //  RenkeiAccountZipCode__c = false,   // アカウント 郵便番号
      //  RenkeiAccountCity__c = false,      // アカウント 市区郡
      //  RenkeiAccountURL__c = false,       // アカウント URL
      //  RenkeiAccountCompany__c = true,   // アカウント 会社名
      //  RenkeiAccountPhone__c = false,     // アカウント 電話番号
      //  RenkeiSpecificItems__c = null,        // アカウント 特定項目
      //  RenkeiAccountSite__c = false,        // アカウント 部署名
      //  RenkeiExcludeHojinkakuPartial__c = true,      // 自動連携:会社名は法人格を除いて部分一致
      //  RenkeiExcludeHojinkaku__c = false,      // 自動連携:会社名は法人格を除いて完全一致
      //  RenkeiAccountSitePartialMatch__c = true,      // 自動連携:部署は中間一致検索
      //  RenkeiContactLastName__c = true,  // コンタクト 姓
      //  RenkeiContactFirstName__c = false, // コンタクト 名
      //  RenkeiContactMail__c = true,      // コンタクト メールアドレス
      //  RenkeiAccountQueryRecordTypeIds__c = null,    // 検索対象のレコードタイプタイプID カンマ区切り で羅列
      //  RenkeiContactQueryRecordTypeIds__c = null,  // 自動連携で検索対象の取引先責任者レコードタイプ
      //  RenkeiAccountOverwrite__c = true,   // 既存の取引先を上書き
      //  RenkeiContactOverwrite__c = true,   // 既存の取引先責任者を上書き
      //  RenkeiAccountNOExistCreateNew__c = true,  //既存の取引先がなければ新規作成する
      //  RenkeiContactNOExistCreateNew__c = true,  // 既存の取引先責任者がなければ新規作成する
      //  RenkeiAccountRecordTypes__c = null,     // 作成するアカウント の レコードタイプID １つ
      //  RenkeiContactRecordTypes__c = null,      // 作成するコンタクト の レコードタイプID １つ
      //  SaishinInheritValues__c = false,          //最新名刺は値を引継ぐ
      //  RegistToDoSubject__c = Label.SB_NC_ExchangeCard, // 取引先・取引先任者に登録 ToDo件名
      //  RegistNoToDo__c =  false, // 取引先・取引先任者に登録 ToDo登録しない
      //  RegistDispOverWriteCheckbox__c = true, // 取引先・取引先任者に登録 「上書きする」チェックボックスを表示する
      //  RegistDispAccountRectype__c = true, // 取引先・取引先任者に登録 取引先レコードタイプ選択を表示する
      //  RegistAccountNotOverWrite__c = false, // 取引先・取引先任者に登録 取引先を名刺情報で上書きしない
      //  RegistDispContactRectype__c = true, // 取引先・取引先任者に登録 取引先責任者レコードタイプ選択を表示する
      //  RegistContactNotOverWrite__c = false // 取引先・取引先任者に登録 取引先責任者を名刺情報で上書きしない
      //);
      listBasicSetting.add(bs);
    }

    public override void initialize() {
      initializeUser();
      if (listUser.isEmpty() == false)
        insert listUser;
      // 名刺基本設定
      initializeBasicSetting();
      if (!listBasicSetting.isEmpty()) {
        insert listBasicSetting;
      }
      //// 名刺連携項目マッピング
      //initializeMapping();
      //if (!listMapping.isEmpty()) {
      //  insert listMapping;
      //}
      // 名刺関係
      initializeKaisha();     // 会社を揃えておく
      initializeEmployee();   // 会社ごとに名刺の人を揃えておく
      // 名刺
      initializeNameCard();
      if (listCard.isEmpty() == false) {
        insert listCard;
      }
      // 取引先
      initializeAccount();  // 揃えた会社について、取引先を作る。
      if (mapAccount.isEmpty() == false) {
        insert mapAccount.values();
      }
      // 取引先責任者
      initializeContact();
      if (!listContact.isEmpty()) {
        insert listContact;
      }
    }
  } // TestDb

  // アカウント、コンタクトの絞込は精細な条件でテストするよう
  public class TestDbQueryStrict extends TestDb {

    public override void initializeBasicSetting() {
      //NameCardBasicSetting__c bs = SB_NC_PostInstallScript.createDefaultBasicSetting();
      NameCardBasicSetting__c bs = SB_NC_PostInstallScript.createDefaultBasicSetting();
      bs.RenkeiAccountAddressPref__c = true;   // アカウント 都道府県
      bs.RenkeiAccount_Street__c = true;   // アカウント 町名・番地
      bs.RenkeiAccountZipCode__c = true;   // アカウント 郵便番号
      bs.RenkeiAccountCity__c = true;      // アカウント 市区郡
      bs.RenkeiAccountURL__c = true;       // アカウント URL
      bs.RenkeiAccountCompany__c = true;   // アカウント 会社名
      bs.RenkeiAccountPhone__c = true;     // アカウント 電話番号
      bs.RenkeiAccountSite__c = true;        // アカウント 部署名
      //bs.RenkeiContactFirstName__c = false; // コンタクト 名
      bs.RenkeiAccountOverwrite__c = true;   // 既存の取引先を上書き
      bs.RenkeiContactOverwrite__c = true;   // 既存の取引先責任者を上書き

      //NameCardBasicSetting__c bs = new NameCardBasicSetting__c(
      //  RenkeiActive__c = false,      // 自動連携機能有効
      //  RenkeiAccountAddressPref__c = true,   // アカウント 都道府県
      //  RenkeiAccount_Street__c = true,   // アカウント 町名・番地
      //  RenkeiAccountZipCode__c = true,   // アカウント 郵便番号
      //  RenkeiAccountCity__c = true,      // アカウント 市区郡
      //  RenkeiAccountURL__c = true,       // アカウント URL
      //  RenkeiAccountCompany__c = true,   // アカウント 会社名
      //  RenkeiAccountPhone__c = true,     // アカウント 電話番号
      //  RenkeiSpecificItems__c = null,        // アカウント 特定項目
      //  RenkeiAccountSite__c = true,        // アカウント 部署名
      //  RenkeiExcludeHojinkakuPartial__c = true,      // 自動連携:会社名は法人格を除いて部分一致
      //  RenkeiExcludeHojinkaku__c = false,      // 自動連携:会社名は法人格を除いて完全一致
      //  RenkeiAccountSitePartialMatch__c = false,      // 自動連携:部署は中間一致検索
      //  RenkeiContactLastName__c = true,  // コンタクト 姓
      //  RenkeiContactFirstName__c = false, // コンタクト 名
      //  RenkeiContactMail__c = true,      // コンタクト メールアドレス
      //  RenkeiAccountQueryRecordTypeIds__c = null,    // 検索対象のレコードタイプタイプID カンマ区切り で羅列
      //  RenkeiContactQueryRecordTypeIds__c = null,  // 自動連携で検索対象の取引先責任者レコードタイプ
      //  RenkeiAccountOverwrite__c = true,   // 既存の取引先を上書き
      //  RenkeiContactOverwrite__c = true,   // 既存の取引先責任者を上書き
      //  RenkeiAccountNOExistCreateNew__c = true,  //既存の取引先がなければ新規作成する
      //  RenkeiContactNOExistCreateNew__c = true,  // 既存の取引先責任者がなければ新規作成する
      //  RenkeiAccountRecordTypes__c = null,     // 作成するアカウント の レコードタイプID １つ
      //  RenkeiContactRecordTypes__c = null,      // 作成するコンタクト の レコードタイプID １つ
      //  SaishinInheritValues__c = false,          //最新名刺は値を引継ぐ
      //  RegistToDoSubject__c = Label.SB_NC_ExchangeCard, // 取引先・取引先任者に登録 ToDo件名
      //  RegistNoToDo__c =  false, // 取引先・取引先任者に登録 ToDo登録しない
      //  RegistDispOverWriteCheckbox__c = true, // 取引先・取引先任者に登録 「上書きする」チェックボックスを表示する
      //  RegistDispAccountRectype__c = true, // 取引先・取引先任者に登録 取引先レコードタイプ選択を表示する
      //  RegistAccountNotOverWrite__c = false, // 取引先・取引先任者に登録 取引先を名刺情報で上書きしない
      //  RegistDispContactRectype__c = true, // 取引先・取引先任者に登録 取引先責任者レコードタイプ選択を表示する
      //  RegistContactNotOverWrite__c = false // 取引先・取引先任者に登録 取引先責任者を名刺情報で上書きしない
      //);
      listBasicSetting.add(bs);
    }
  } // class TestDbQueryStrict


  // アカウント、コンタクトの絞込は名刺メモとの対比がある条件でテストするよう
  public class TestDbQueryExtension extends TestDb {

    public override void initializeNameCard() {
      for (Employee emp :listEmp) {
        // 所有者の異なる名刺を作成
        for (User u : listUser) {
          listCard.add(
            new NameCard__c(
              name= emp.name
              , person_name_last__c= emp.sei
              , person_name_first__c= emp.mei
              , last_name__c= emp.sei.replace('苗字', 'Myoji')
              , first_name__c= emp.mei.replace('名', 'Na')
              , email__c= emp.mail
              , company_name__c= emp.kaisha.name
              , division__c = '本社'
              , title_name__c = '役職'+emp.num.format()
              , tel1__c= emp.kaisha.phone
              , tel2__c= emp.kaisha.phone
              , fax1__c= '0344444444'
              , mobile__c = '09099999999'
              , web_url1__c = 'http://www.'+emp.kaisha.domain
              , web_url2__c = 'http://www.'+emp.kaisha.domain
              , zip_code__c = emp.kaisha.zip
              , address_pref__c = emp.kaisha.pref
              , address__c = emp.kaisha.address
              , address_bld__c = emp.kaisha.bld
              , memo__c = emp.kaisha.name // 会社名に変更
              , freehandmemo__c = '自由記述 : ' + emp.kaisha.name +' '+ emp.num.format()
              , delivery_type__c='1'
              , OwnerId = u.Id
          ));
        }
      }
    }

    public override void initializeBasicSetting() {
      NameCardBasicSetting__c bs = SB_NC_PostInstallScript.createDefaultBasicSetting();
      bs.RenkeiSpecificItems__c = 'Name';        // アカウント 特定項目
      //bs.RenkeiContactFirstName__c = false; // コンタクト 名
      bs.RenkeiAccountOverwrite__c = true;   // 既存の取引先を上書き
      bs.RenkeiContactOverwrite__c = true;   // 既存の取引先責任者を上書き

      //NameCardBasicSetting__c bs = new NameCardBasicSetting__c(
      //  RenkeiActive__c = false,      // 自動連携機能有効
      //  RenkeiAccountAddressPref__c = false,   // アカウント 都道府県
      //  RenkeiAccount_Street__c = false,   // アカウント 町名・番地
      //  RenkeiAccountZipCode__c = false,   // アカウント 郵便番号
      //  RenkeiAccountCity__c = false,      // アカウント 市区郡
      //  RenkeiAccountURL__c = false,       // アカウント URL
      //  RenkeiAccountCompany__c = true,   // アカウント 会社名
      //  RenkeiAccountPhone__c = false,     // アカウント 電話番号
      //  RenkeiSpecificItems__c = 'Name',        // アカウント 特定項目
      //  RenkeiAccountSite__c = false,        // アカウント 部署名
      //  RenkeiExcludeHojinkakuPartial__c = true,      // 自動連携:会社名は法人格を除いて部分一致
      //  RenkeiExcludeHojinkaku__c = false,      // 自動連携:会社名は法人格を除いて完全一致
      //  RenkeiAccountSitePartialMatch__c = true,      // 自動連携:部署は中間一致検索
      //  RenkeiContactLastName__c = true,  // コンタクト 姓
      //  RenkeiContactFirstName__c = false, // コンタクト 名
      //  RenkeiContactMail__c = true,      // コンタクト メールアドレス
      //  RenkeiAccountQueryRecordTypeIds__c = null,    // 検索対象のレコードタイプタイプID カンマ区切り で羅列
      //  RenkeiContactQueryRecordTypeIds__c = null,  // 自動連携で検索対象の取引先責任者レコードタイプ
      //  RenkeiAccountOverwrite__c = true,   // 既存の取引先を上書き
      //  RenkeiContactOverwrite__c = true,   // 既存の取引先責任者を上書き
      //  RenkeiAccountNOExistCreateNew__c = true,  //既存の取引先がなければ新規作成する
      //  RenkeiContactNOExistCreateNew__c = true,  // 既存の取引先責任者がなければ新規作成する
      //  RenkeiAccountRecordTypes__c = null,     // 作成するアカウント の レコードタイプID １つ
      //  RenkeiContactRecordTypes__c = null,      // 作成するコンタクト の レコードタイプID １つ
      //  SaishinInheritValues__c = false,          //最新名刺は値を引継ぐ
      //  RegistToDoSubject__c = Label.SB_NC_ExchangeCard, // 取引先・取引先任者に登録 ToDo件名
      //  RegistNoToDo__c =  false, // 取引先・取引先任者に登録 ToDo登録しない
      //  RegistDispOverWriteCheckbox__c = true, // 取引先・取引先任者に登録 「上書きする」チェックボックスを表示する
      //  RegistDispAccountRectype__c = true, // 取引先・取引先任者に登録 取引先レコードタイプ選択を表示する
      //  RegistAccountNotOverWrite__c = false, // 取引先・取引先任者に登録 取引先を名刺情報で上書きしない
      //  RegistDispContactRectype__c = true, // 取引先・取引先任者に登録 取引先責任者レコードタイプ選択を表示する
      //  RegistContactNotOverWrite__c = false // 取引先・取引先任者に登録 取引先責任者を名刺情報で上書きしない
      //);
      listBasicSetting.add(bs);
    }

  } // class TestDbQueryExtension

  // アカウント、コンタクトの絞込はレコードタイプも条件にしてテストするよう ただし失敗する。
  public class TestDbQueryRecordType extends TestDb {
    public override void initializeBasicSetting() {
      Map<Id, Schema.RecordTypeInfo> accountRectypes = Account.sObjectType.getDescribe().getRecordTypeInfosById();
      String accountRectypeId = null;
      for (Id id : accountRectypes.keySet()) {
        if (accountRectypes.get(id).isAvailable() && !accountRectypes.get(id).isMaster()) { // 2019.05.xx 利用可能なレコードタイプなら
          accountRectypeId = id;
          break;
        }
      }
      Map<Id, Schema.RecordTypeInfo> contactRectypes = Contact.sObjectType.getDescribe().getRecordTypeInfosById();
      String contactRectypeId = null;
      for (Id id : contactRectypes.keySet()) {
        if (contactRectypes.get(id).isAvailable() && !contactRectypes.get(id).isMaster()) { // 2019.05.xx 利用可能なレコードタイプなら
          contactRectypeId = id;
          break;
        }
      }

      NameCardBasicSetting__c bs = SB_NC_PostInstallScript.createDefaultBasicSetting();
      //bs.RenkeiContactFirstName__c = false; // コンタクト 名
      bs.RenkeiAccountQueryRecordTypeIds__c = accountRectypeId;    // 検索対象のレコードタイプタイプID カンマ区切り で羅列
      bs.RenkeiContactQueryRecordTypeIds__c = contactRectypeId;  // 自動連携で検索対象の取引先責任者レコードタイプ
      bs.RenkeiAccountOverwrite__c = true;   // 既存の取引先を上書き
      bs.RenkeiContactOverwrite__c = true;   // 既存の取引先責任者を上書き

      //NameCardBasicSetting__c bs = new NameCardBasicSetting__c(
      //  RenkeiActive__c = false,      // 自動連携機能有効
      //  RenkeiAccountAddressPref__c = false,   // アカウント 都道府県
      //  RenkeiAccount_Street__c = false,   // アカウント 町名・番地
      //  RenkeiAccountZipCode__c = false,   // アカウント 郵便番号
      //  RenkeiAccountCity__c = false,      // アカウント 市区郡
      //  RenkeiAccountURL__c = false,       // アカウント URL
      //  RenkeiAccountCompany__c = true,   // アカウント 会社名
      //  RenkeiAccountPhone__c = false,     // アカウント 電話番号
      //  RenkeiSpecificItems__c = null,        // アカウント 特定項目
      //  RenkeiAccountSite__c = false,        // アカウント 部署名
      //  RenkeiExcludeHojinkakuPartial__c = true,      // 自動連携:会社名は法人格を除いて部分一致
      //  RenkeiExcludeHojinkaku__c = false,      // 自動連携:会社名は法人格を除いて完全一致
      //  RenkeiAccountSitePartialMatch__c = true,      // 自動連携:部署は中間一致検索
      //  RenkeiContactLastName__c = true,  // コンタクト 姓
      //  RenkeiContactFirstName__c = false, // コンタクト 名
      //  RenkeiContactMail__c = true,      // コンタクト メールアドレス
      //  RenkeiAccountQueryRecordTypeIds__c = accountRectypeId,    // 検索対象のレコードタイプタイプID カンマ区切り で羅列
      //  RenkeiContactQueryRecordTypeIds__c = contactRectypeId,  // 自動連携で検索対象の取引先責任者レコードタイプ
      //  RenkeiAccountOverwrite__c = true,   // 既存の取引先を上書き
      //  RenkeiContactOverwrite__c = true,   // 既存の取引先責任者を上書き
      //  RenkeiAccountNOExistCreateNew__c = true,  //既存の取引先がなければ新規作成する
      //  RenkeiContactNOExistCreateNew__c = true,  // 既存の取引先責任者がなければ新規作成する
      //  RenkeiAccountRecordTypes__c = null,     // 作成するアカウント の レコードタイプID １つ
      //  RenkeiContactRecordTypes__c = null,      // 作成するコンタクト の レコードタイプID １つ
      //  SaishinInheritValues__c = false,          //最新名刺は値を引継ぐ
      //  RegistToDoSubject__c = Label.SB_NC_ExchangeCard, // 取引先・取引先任者に登録 ToDo件名
      //  RegistNoToDo__c =  false, // 取引先・取引先任者に登録 ToDo登録しない
      //  RegistDispOverWriteCheckbox__c = true, // 取引先・取引先任者に登録 「上書きする」チェックボックスを表示する
      //  RegistDispAccountRectype__c = true, // 取引先・取引先任者に登録 取引先レコードタイプ選択を表示する
      //  RegistAccountNotOverWrite__c = false, // 取引先・取引先任者に登録 取引先を名刺情報で上書きしない
      //  RegistDispContactRectype__c = true, // 取引先・取引先任者に登録 取引先責任者レコードタイプ選択を表示する
      //  RegistContactNotOverWrite__c = false // 取引先・取引先任者に登録 取引先責任者を名刺情報で上書きしない
      //);
      listBasicSetting.add(bs);
    }

  } // class TestDbQueryRecordType


  private static final String NMAECARD_FIELDS = 'Id, Name, name_kana__c, person_name_last__c, person_name_first__c, last_name__c, first_name__c' +
  ', company_name__c, company_name_kana__c, division__c, division_name__c, title_name__c' +
  ', zip_code__c, address_pref__c, address__c, address_bld__c, address_eng__c, Saishin__c' +
  ', card_exchange_date__c, list_name__c, OwnerId, Owner.Name, Parent__c, tenshokugonomeishi__c, account__c, contact__c' +
  ', freehandmemo__c, memo__c, web_url1__c, web_url2__c, email__c, tel1__c, tel2__c, mobile__c, fax1__c, fax2__c' +
  ', image_id__c, bk_image_id__c, width__c, height__c, bk_width__c, bk_height__c' +
  ', isNotOverwrite__c, isNotOverContactwrite__c';

  //@isTest
  //static void test_getCradId2Targets()
  //{
  //  TestDb db = new TestDb();
  //  db.initialize();

  //  Test.startTest();
  //  Map<Id, Account> acnts = new Map<Id, Account> ([SELECT Id, Name FROM Account]);
  //  Map<Id, Contact> conts = new Map<Id, Contact> ([SELECT Id, Name, AccountId FROM Contact]);
  //  List<NameCard__c> cards = Database.query('SELECT ' + NMAECARD_FIELDS + ' FROM NameCard__c LIMIT 1');

  //  Map<Id, List<SB_NameCard_RenkeiTargetsPicker.Target>> cardId2Accounts = SB_NameCard_RenkeiTargetsPicker.getCradId2Targets(cards, Account.sObjectType);

  //  for (Id id : cardId2Accounts.keySet()) {
  //    List<SB_NameCard_RegistCardHolder.AccountTarget> ts = (List<SB_NameCard_RegistCardHolder.AccountTarget>)cardId2Accounts.get(id);
  //    System.assert(ts != null && !ts.isEmpty());
  //    for (SB_NameCard_RegistCardHolder.AccountTarget t : ts) {
  //      System.debug(t.targetId + ': ' + t.childIds.size());
  //    }
  //    System.assertEquals(1, ts.size());
  //    System.assertEquals(1, ts[0].childIds.size());
  //  }
  //  Test.stopTest();
  //}

  //@isTest
  //static void test_getCradId2TargetsQueryStrict()
  //{
  //  TestDbQueryStrict db = new TestDbQueryStrict();
  //  db.initialize();

  //  Test.startTest();
  //  Map<Id, Account> acnts = new Map<Id, Account> ([SELECT Id, Name FROM Account]);
  //  Map<Id, Contact> conts = new Map<Id, Contact> ([SELECT Id, Name, AccountId FROM Contact]);
  //  List<NameCard__c> cards = Database.query('SELECT ' + NMAECARD_FIELDS + ' FROM NameCard__c LIMIT 1');

  //  Map<Id, List<SB_NameCard_RenkeiTargetsPicker.Target>> cardId2Accounts = SB_NameCard_RenkeiTargetsPicker.getCradId2Targets(cards, Account.sObjectType);

  //  for (Id id : cardId2Accounts.keySet()) {
  //    List<SB_NameCard_RegistCardHolder.AccountTarget> ts = (List<SB_NameCard_RegistCardHolder.AccountTarget>)cardId2Accounts.get(id);
  //    System.assert(ts != null && !ts.isEmpty());
  //    for (SB_NameCard_RegistCardHolder.AccountTarget t : ts) {
  //      System.debug(t.targetId + ': ' + t.childIds.size());
  //    }
  //    System.assertEquals(1, ts.size());
  //    System.assertEquals(1, ts[0].childIds.size());
  //  }
  //  Test.stopTest();
  //}


  //@isTest
  //static void test_getCradId2TargetsQueryExtension()
  //{
  //  TestDbQueryExtension db = new TestDbQueryExtension();
  //  db.initialize();

  //  Test.startTest();
  //  Map<Id, Account> acnts = new Map<Id, Account> ([SELECT Id, Name FROM Account]);
  //  Map<Id, Contact> conts = new Map<Id, Contact> ([SELECT Id, Name, AccountId FROM Contact]);
  //  List<NameCard__c> cards = Database.query('SELECT ' + NMAECARD_FIELDS + ' FROM NameCard__c LIMIT 1');

  //  Map<Id, List<SB_NameCard_RenkeiTargetsPicker.Target>> cardId2Accounts = SB_NameCard_RenkeiTargetsPicker.getCradId2Targets(cards, Account.sObjectType);

  //  for (Id id : cardId2Accounts.keySet()) {
  //    List<SB_NameCard_RegistCardHolder.AccountTarget> ts = (List<SB_NameCard_RegistCardHolder.AccountTarget>)cardId2Accounts.get(id);
  //    System.assert(ts != null && !ts.isEmpty());
  //    for (SB_NameCard_RegistCardHolder.AccountTarget t : ts) {
  //      System.debug(t.targetId + ': ' + t.childIds.size());
  //    }
  //    System.assertEquals(1, ts.size());
  //    System.assertEquals(1, ts[0].childIds.size());
  //  }
  //  Test.stopTest();
  //}


  //@isTest
  //static void test_getCradId2TargetsCreateQueryRecordType()
  //{
  //  TestDbQueryRecordType db = new TestDbQueryRecordType();
  //  db.initialize();

  //  Test.startTest();
  //  SB_NameCard_RenkeiTargetsPicker.AccountsCardHolderBuilder builder = new SB_NameCard_RenkeiTargetsPicker.AccountsCardHolderBuilder();
  //  String soql = builder.createQuery();
  //  System.assert(String.isNotBlank(soql));
  //  //Map<Id, Account> acnts = new Map<Id, Account> ([SELECT Id, Name FROM Account]);
  //  //Map<Id, Contact> conts = new Map<Id, Contact> ([SELECT Id, Name, AccountId FROM Contact]);
  //  //List<NameCard__c> cards = Database.query('SELECT ' + NMAECARD_FIELDS + ' FROM NameCard__c LIMIT 1');

  //  //Map<Id, List<SB_NameCard_RenkeiTargetsPicker.Target>> cardId2Accounts = SB_NameCard_RenkeiTargetsPicker.getCradId2Targets(cards, Account.sObjectType);

  //  //System.assert(true, cardId2Accounts.isEmpty());
  //  Test.stopTest();
  //}

  @isTest
  static void test_getCradId2Targets()
  {
    TestDb db = new TestDb();
    db.initialize();

    Test.startTest();
    Map<Id, Account> acnts = new Map<Id, Account> ([SELECT Id, Name FROM Account]);
    Map<Id, Contact> conts = new Map<Id, Contact> ([SELECT Id, Name, AccountId FROM Contact]);
    List<NameCard__c> cards = Database.query('SELECT ' + NMAECARD_FIELDS + ' FROM NameCard__c LIMIT 1');

    List<SB_NameCard_RegistCardHolder.AccountCardHolder> accountCardHolder
          = (List<SB_NameCard_RegistCardHolder.AccountCardHolder>)SB_NameCard_RenkeiTargetsPicker.createCardHolders(cards, Account.sObjectType);

    for (SB_NameCard_RegistCardHolder.AccountCardHolder holder : accountCardHolder) {
      System.assert(holder.targets != null && !holder.targets.isEmpty());
      for (SB_NameCard_RegistCardHolder.AccountTarget t : holder.targets) {
        System.debug(t.targetId + ': ' + t.childIds.size());
      }
      System.assertEquals(1, holder.targets.size());
      System.assertEquals(1, holder.targets[0].childIds.size());
    }
    Test.stopTest();
  }

  @isTest
  static void test_getCradId2CardHolderQueryStrict()
  {
    TestDbQueryStrict db = new TestDbQueryStrict();
    db.initialize();

    Test.startTest();
    Map<Id, Account> acnts = new Map<Id, Account> ([SELECT Id, Name FROM Account]);
    Map<Id, Contact> conts = new Map<Id, Contact> ([SELECT Id, Name, AccountId FROM Contact]);
    List<NameCard__c> cards = Database.query('SELECT ' + NMAECARD_FIELDS + ' FROM NameCard__c');    // LIMIT 1 でなくてととおる

    List<SB_NameCard_RegistCardHolder.AccountCardHolder> accountCardHolder
          = (List<SB_NameCard_RegistCardHolder.AccountCardHolder>)SB_NameCard_RenkeiTargetsPicker.createCardHolders(cards, Account.sObjectType);

    for (SB_NameCard_RegistCardHolder.AccountCardHolder holder : accountCardHolder) {
      System.assert(holder.targets != null && !holder.targets.isEmpty());
      for (SB_NameCard_RegistCardHolder.AccountTarget t : holder.targets) {
        System.debug(t.targetId + ': ' + t.childIds.size());
      }
      System.assertEquals(1, holder.targets.size());
      System.assertEquals(1, holder.targets[0].childIds.size());
    }
    Test.stopTest();
  }

  @isTest
  static void test_getCradId2CardHolderQueryExtension()
  {
    TestDbQueryExtension db = new TestDbQueryExtension();
    db.initialize();

    Test.startTest();
    Map<Id, Account> acnts = new Map<Id, Account> ([SELECT Id, Name FROM Account]);
    Map<Id, Contact> conts = new Map<Id, Contact> ([SELECT Id, Name, AccountId FROM Contact]);
    List<NameCard__c> cards = Database.query('SELECT ' + NMAECARD_FIELDS + ' FROM NameCard__c LIMIT 1');

    List<SB_NameCard_RegistCardHolder.AccountCardHolder> accountCardHolder
          = (List<SB_NameCard_RegistCardHolder.AccountCardHolder>)SB_NameCard_RenkeiTargetsPicker.createCardHolders(cards, Account.sObjectType);

    for (SB_NameCard_RegistCardHolder.AccountCardHolder holder : accountCardHolder) {
      System.assert(holder.targets != null && !holder.targets.isEmpty());
      for (SB_NameCard_RegistCardHolder.AccountTarget t : holder.targets) {
        System.debug(t.targetId + ': ' + t.childIds.size());
      }
      System.assertEquals(1, holder.targets.size());
      System.assertEquals(1, holder.targets[0].childIds.size());
    }
    Test.stopTest();
  }


  @isTest
  static void test_getCradId2CardHolderCreateQueryRecordType()
  {
    TestDbQueryRecordType db = new TestDbQueryRecordType();
    db.initialize();

    Test.startTest();
    SB_NameCard_RenkeiTargetsPicker.AccountsCardHolderBuilder builder = new SB_NameCard_RenkeiTargetsPicker.AccountsCardHolderBuilder();
    String soql = builder.createQuery();
    System.assert(String.isNotBlank(soql));
    //Map<Id, Account> acnts = new Map<Id, Account> ([SELECT Id, Name FROM Account]);
    //Map<Id, Contact> conts = new Map<Id, Contact> ([SELECT Id, Name, AccountId FROM Contact]);
    //List<NameCard__c> cards = Database.query('SELECT ' + NMAECARD_FIELDS + ' FROM NameCard__c LIMIT 1');

    //Map<Id, SB_NameCard_RenkeiTargetsPicker.CardHolder> cardId2Accounts = SB_NameCard_RenkeiTargetsPicker.createCardHolders(cards, Account.sObjectType);

    //System.assert(true, cardId2Accounts.isEmpty());
    Test.stopTest();
  }

}