sfdx-source/SmartVisca/main/default/objects/Account/fields/NameCard__c.field-meta.xml
<CustomField>
    <fullName>NameCard__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>名刺</label>
    <referenceTo>NameCard__c</referenceTo>
    <relationshipLabel>取引先</relationshipLabel>
    <relationshipName>AccountNameCards</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/Contact/fields/NameCard__c.field-meta.xml
<CustomField>
    <fullName>NameCard__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>名刺</label>
    <referenceTo>NameCard__c</referenceTo>
    <relationshipLabel>取引先責任者</relationshipLabel>
    <relationshipName>ContactNameCards</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/JinjiIdo__c/JinjiIdo__c.object-meta.xml
<CustomObject>
    <description>オプション：人事異動の案内があるとここに保存されます。
Option:Stores personnel change information.</description>
    <label>人事異動情報</label>
    <nameField>
        <label>人事異動情報名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/SmartVisca/main/default/objects/JinjiIdo__c/fields/NameCard__c.field-meta.xml
<CustomField>
    <fullName>NameCard__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>名刺</label>
    <referenceTo>NameCard__c</referenceTo>
    <relationshipLabel>人事異動情報</relationshipLabel>
    <relationshipName>NameCardJinjiIdos</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/JinjiIdo__c/fields/NewTitle__c.field-meta.xml
<CustomField>
    <fullName>NewTitle__c</fullName>
    <label>新職名</label>
    <type>TextArea</type>
</CustomField>

sfdx-source/unpackaged/dev-config/main/default/objects/NameCard__c/NameCard__c.object-meta.xml
<CustomObject>
    <customHelpPage>SB_NameCard_UserGuide</customHelpPage>
    <description>スキャナから取り込んだ名刺情報がここに保存されます。
Business Card: Stores digitized business card information.</description>
    <label>名刺</label>
    <nameField>
        <label>氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/contact__c.field-meta.xml
<CustomField>
    <fullName>contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>取引先責任者</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>名刺</relationshipLabel>
    <relationshipName>nc_contact</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/SmartVisca/main/default/classes/SB_NameCard_TitleUpdaterController.cls
/*  $Id$    */

/*
 * Copyright (c) 2014-2015 SunBridge Inc.
 *
 * 日経テレコン人事異動情報 役職更新
 * @Version 1 kou 2017.10.xx  FLS  v1.21 for code scan
 */

public with sharing class SB_NameCard_TitleUpdaterController {

    public String targetId { get; private set;}
    public String parentId { get; private set;}
    public JinjiIdo__c targetRecord { get; private set;}
    public String newTitle { get; set;}
    public String contactlabel{get;set;}

    public String returnURL { get; private set;}
    public Boolean isError { get; private set;}
    
    public String reflectToTitle{get;set;}//表示ラベル
    public String replaceContactTitle{get;set;}

    /** VFページ用のコンストラクタです。 */
    public SB_NameCard_TitleUpdaterController( ApexPages.StandardController controller) {
        //SV_DEV-605 によってgetGlobalDescribeを使わないようにする
        this.contactlabel = Contact.sObjectType.getDescribe().getLabel();
        //SV_DEV-605 changeLabelメソッド使わない
        //ラベル:取引先責任者の役職に反映
        this.reflectToTitle = String.format(System.Label.SB_NC_ReflectToTitleDEV,new String[]{contactlabel});
        //ラベル:取引先責任者の役職を新職名で更新
        this.replaceContactTitle = String.format(System.Label.SB_NC_ReplaceContactTitleDEV,new String[]{contactlabel});

        this.targetId = controller.getId();
        this.isError = false;
    }

    public PageReference cancel() {
        return new PageReference('/' + this.targetId);
    }

    public void init() {
        System.debug( '-----:init start');

        // idが選ばれているか？
        if ( this.targetId == null) {
            ApexPages.addMessage( new ApexPages.Message(ApexPages.Severity.ERROR, System.Label.SB_MSG_SelectPersonnelChangeInfo));
            this.returnURL = '/home/home.jsp';
            this.isError = true;
            return;
        }

        // 人事異動情報を select
        try {
            this.targetRecord = [SELECT NameCard__r.contact__c, NameCard__r.contact__r.Name, NameCard__r.contact__r.Account.Name, NameCard__r.contact__r.Title, NewTitle__c FROM JinjiIdo__c WHERE Id = :this.targetId];

            if (this.targetRecord.NameCard__r.contact__c == null) {
                String str = String.format(System.Label.SB_MSG_ContactNotSetDEV,new String[]{Contact.sObjectType.getDescribe().getLabel()});

                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, str));
            } else {
                this.parentId = this.targetRecord.NameCard__r.contact__c;
                this.returnURL = '/' + this.targetId;
                this.newTitle = this.targetRecord.NewTitle__c;
            }
        }
        catch ( Exception e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, System.Label.SB_MSG_CantGetPersonnelChangeInfo + '\n' + e.getMessage()));
            this.isError = true;
            return;
        }
    }

    public PageReference updateContact() {

        PageReference p = null;

        if (this.targetRecord.NameCard__r.contact__c == null) {
            String str = String.format(System.Label.SB_MSG_ContactNotSetDEV,new String[]{Contact.sObjectType.getDescribe().getLabel()});

            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, str));
        } else {
            Savepoint sp = null;

            // contactを更新
            Contact contact = new Contact( id=this.targetRecord.NameCard__r.contact__c);
            contact.Title = this.newTitle;

            try {
                sp = Database.setSavepoint();
                SB_NameCard_CrudFls.supdate(new Contact[]{contact}, true); //  kou 2017.10.xx  FLS Update  v1.21 for code scan
                p = new PageReference('/' + this.parentId);
            }
            catch ( Exception e) {
                Database.rollback(sp);
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, System.Label.SB_MSG_CantUpdateTitle + '\n' + e.getMessage()));
                this.isError = true;
                return null;
            }
        }

        return p;
    }
}