sfdx-source/SmartVisca/main/default/objects/Account/fields/NameCard__c.field-meta.xml
<CustomField>
    <fullName>NameCard__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>名刺</label>
    <referenceTo>NameCard__c</referenceTo>
    <relationshipLabel>取引先</relationshipLabel>
    <relationshipName>AccountNameCards</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/Contact/fields/NameCard__c.field-meta.xml
<CustomField>
    <fullName>NameCard__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>名刺</label>
    <referenceTo>NameCard__c</referenceTo>
    <relationshipLabel>取引先責任者</relationshipLabel>
    <relationshipName>ContactNameCards</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/unpackaged/dev-config/main/default/objects/NameCard__c/NameCard__c.object-meta.xml
<CustomObject>
    <customHelpPage>SB_NameCard_UserGuide</customHelpPage>
    <description>スキャナから取り込んだ名刺情報がここに保存されます。
Business Card: Stores digitized business card information.</description>
    <label>名刺</label>
    <nameField>
        <label>氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/address__c.field-meta.xml
<CustomField>
    <fullName>address__c</fullName>
    <label>住所</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/address_bld__c.field-meta.xml
<CustomField>
    <fullName>address_bld__c</fullName>
    <label>建物名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/address_eng__c.field-meta.xml
<CustomField>
    <fullName>address_eng__c</fullName>
    <description>英語名刺の場合</description>
    <label>英語住所</label>
    <type>TextArea</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/address_pref__c.field-meta.xml
<CustomField>
    <fullName>address_pref__c</fullName>
    <label>都道府県</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/company_name__c.field-meta.xml
<CustomField>
    <fullName>company_name__c</fullName>
    <label>会社名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/first_name__c.field-meta.xml
<CustomField>
    <fullName>first_name__c</fullName>
    <description>英語名刺の場合</description>
    <label>ファーストネーム</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/last_name__c.field-meta.xml
<CustomField>
    <fullName>last_name__c</fullName>
    <description>英語名刺の場合</description>
    <label>ラストネーム</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/person_name_first__c.field-meta.xml
<CustomField>
    <fullName>person_name_first__c</fullName>
    <label>名</label>
    <length>127</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/person_name_last__c.field-meta.xml
<CustomField>
    <fullName>person_name_last__c</fullName>
    <label>姓</label>
    <length>127</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardRenkeiMapping__c/NameCardRenkeiMapping__c.object-meta.xml
<CustomObject>
    <label>名刺連携項目マッピング</label>
    <nameField>
        <displayFormat>RM-{000000}</displayFormat>
        <label>名刺連携項目マッピングNo</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/SmartVisca/main/default/objects/NameCardRenkeiMapping__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>有効</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardRenkeiMapping__c/fields/NameCardName__c.field-meta.xml
<CustomField>
    <fullName>NameCardName__c</fullName>
    <label>名刺の項目(API名称)</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardRenkeiMapping__c/fields/TargetName__c.field-meta.xml
<CustomField>
    <fullName>TargetName__c</fullName>
    <label>対象の項目(API名称)</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardRenkeiMapping__c/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

sfdx-source/SmartVisca/main/default/classes/SB_NameCard_RenkeiMapperTest.cls
/**
 *
 *  SB_NameCard_RenkeiMapperTest
 *   SB_NameCard_RenkeiMapperのテストクラス
 *
 *
 *  Copyright (C) 2016 SunBridge Inc. All Rights Reserved.
 *
 *  @author sawano
 *  @Version 1      2016.xx.xx
 *
 **/
@isTest
private class SB_NameCard_RenkeiMapperTest {


  public class TestDb extends SB_NC_TestDB {

  }

  @testSetup
  static void setupDB() {
    TestDb db = new TestDb();
    db.initialize();
  }

  private static String getQueryFields(Map<String, Set<String>> mappings) {
    String result = '';
    Set<String> fields = new Set<String>(mappings.keySet());
    fields.add('Id');
    fields.add('Name');
    // 会社名
    fields.add('company_name__c');
    // 住所用の項目
    fields.add('address_pref__c');
    fields.add('address__c');
    fields.add('address_eng__c');
    fields.add('address_bld__c');
    // 姓名用の項目
    fields.add('person_name_last__c');
    fields.add('person_name_first__c');
    fields.add('last_name__c');
    fields.add('first_name__c');
    //removeAddressLabel(fields);
    fields.remove('city');
    fields.remove('street');
    fields.remove('pref_address_bld');
    fields.remove('address_bld');
    fields.remove('street_nobld');
    fields.remove('last_name');
    fields.remove('first_name');
    for (String f : fields) {
      result += f + ', ';
    }
    return result.removeEnd(', ');
  }

  // 新規アカウントのテスト
  @isTest
  static void testCreateRecordAccount() {
    String fields = getQueryFields(SB_NC_TestDB.SV_TO_ACCOUNT);
    String query = 'SELECT ' + fields + ' FROM NameCard__c LIMIT 10';
    List<NameCard__c> cards = Database.query(query);

    SB_NameCard_RenkeiMapper mapper = SB_NameCard_RenkeiMapper.getInstance('Account', true);
    mapper = SB_NameCard_RenkeiMapper.getInstance('Account', true);     // 既存のインスタンス取得のコードを動かすため
    Id recorTypeId = null;
    SObject obj;
    if (mapper.haveNameSource(cards[0])) {
      obj = mapper.createRecord(cards[0], recorTypeId);
    }

    List<NameCardRenkeiMapping__c> mappings = [SELECT Id, Name, NameCardName__c, TargetName__c FROM NameCardRenkeiMapping__c WHERE RecordType.Name = 'Account' AND IsActive__c = true];
    for (NameCardRenkeiMapping__c mapping : mappings) {
      if (mapping.NameCardName__c.endsWithIgnoreCase('__c')) {    // city とかは除外
        System.assertEquals(cards[0].get(mapping.NameCardName__c), obj.get(mapping.TargetName__c));
      }
    }
    Database.DMLOptions dml = new Database.DMLOptions();
    dml.DuplicateRuleHeader.allowSave = true;
    dml.DuplicateRuleHeader.runAsCurrentUser = true;
    Database.SaveResult sr = Database.insert(obj, dml);
    if (sr.isSuccess()) {
      System.debug(obj.Id);
      Account acnt = [SELECT Id, Name FROM Account WHERE Id = :obj.Id LIMIT 1];
      System.assertNotEquals(NULL, acnt);
    }
  }

  // アカウント更新のテスト
  @isTest
  static void testUpdateRecordAccount() {
    String fields = getQueryFields(SB_NC_TestDB.SV_TO_ACCOUNT);
    String query = 'SELECT ' + fields + ' FROM NameCard__c LIMIT 10';
    List<NameCard__c> cards = Database.query(query);

    SB_NameCard_RenkeiMapper mapper = SB_NameCard_RenkeiMapper.getInstance('Account', true);
    mapper = SB_NameCard_RenkeiMapper.getInstance('Account', true);     // 既存のインスタンス取得のコードを動かすため
    List<Account> acnts = [SELECT Id, Name FROM Account LIMIT 10];
    SObject obj = mapper.updateRecord(cards[0], acnts[0].Id);

    List<NameCardRenkeiMapping__c> mappings = [SELECT Id, Name, NameCardName__c, TargetName__c FROM NameCardRenkeiMapping__c WHERE RecordType.Name = 'Account' AND IsActive__c = true];
    for (NameCardRenkeiMapping__c mapping : mappings) {
      if (mapping.NameCardName__c.endsWithIgnoreCase('__c') && mapping.TargetName__c != 'Name') {    // city とかは除外
        System.assertEquals(cards[0].get(mapping.NameCardName__c), obj.get(mapping.TargetName__c));
      }
    }
    Database.DMLOptions dml = new Database.DMLOptions();
    dml.DuplicateRuleHeader.allowSave = true;
    dml.DuplicateRuleHeader.runAsCurrentUser = true;
    Database.SaveResult sr = Database.update(obj, dml);
    if (sr.isSuccess()) {
      System.debug(obj.Id);
      Account acnt = [SELECT Id, Name FROM Account WHERE Id = :obj.Id LIMIT 1];
      System.assertNotEquals(NULL, acnt);
    }
  }

  // 新規コンタクトのテスト
  @isTest
  static void testCreateRecordContact() {
    String fields = getQueryFields(SB_NC_TestDB.SV_TO_CONTACT);
    String query = 'SELECT ' + fields + ' FROM NameCard__c LIMIT 10';
    List<NameCard__c> cards = Database.query(query);

    SB_NameCard_RenkeiMapper mapper = SB_NameCard_RenkeiMapper.getInstance('Account', true);    // Account 用もあって
    mapper = SB_NameCard_RenkeiMapper.getInstance('Contact', true);      // Contact 用も作る
    Id recorTypeId = null;
    SObject obj;
    if (mapper.haveNameSource(cards[0])) {
      obj = mapper.createRecord(cards[0], recorTypeId);
    }

    List<NameCardRenkeiMapping__c> mappings = [SELECT Id, Name, NameCardName__c, TargetName__c FROM NameCardRenkeiMapping__c WHERE RecordType.Name = 'Contact' AND IsActive__c = true];
    for (NameCardRenkeiMapping__c mapping : mappings) {
      if (mapping.NameCardName__c.endsWithIgnoreCase('__c')) {    // city とかは除外
        System.assertEquals(cards[0].get(mapping.NameCardName__c), obj.get(mapping.TargetName__c));
      }
    }

    //  親のアカウント
    List<Account> acnts = [SELECT Id, Name FROM Account LIMIT 10];
    obj.put('AccountId', acnts[0].Id);
    Database.DMLOptions dml = new Database.DMLOptions();
    dml.DuplicateRuleHeader.allowSave = true;
    dml.DuplicateRuleHeader.runAsCurrentUser = true;
    Database.SaveResult sr = Database.insert(obj, dml);
    if (sr.isSuccess()) {
      System.debug(obj.Id);
      Contact acnt = [SELECT Id, Name FROM Contact WHERE Id = :obj.Id LIMIT 1];
      System.assertNotEquals(NULL, acnt);
    }
  }

  @isTest
  static void testAddressBuilder() {
    String fields = getQueryFields(SB_NC_TestDB.SV_TO_ACCOUNT);
    String query = 'SELECT ' + fields + ' FROM NameCard__c LIMIT 10';
    List<NameCard__c> cards = Database.query(query);
    Map<String, String> addressMap = SB_NameCard_Util.getAddress(cards[0]);
    SB_NameCard_RenkeiMapper.AddressBuilder builder;
    builder = new SB_NameCard_RenkeiMapper.StreetNoBldBuilder();
    String street_nobld = builder.create(cards[0], addressMap);
    System.assert(String.isNotBlank(street_nobld));
    builder = new SB_NameCard_RenkeiMapper.PrefAddressBldBuilder();
    String fullAddress = builder.create(cards[0], addressMap);
    System.assert(String.isNotBlank(fullAddress));
    builder = new SB_NameCard_RenkeiMapper.AddressBldBuilder();
    String addressBld = builder.create(cards[0], addressMap);
    System.assert(String.isNotBlank(addressBld));
  }

  // FieldBuilderFromPickList のテスト
  // 名刺標準では選択リストはないので、Account を使って
  // 2018.03.xx V1.22  SV_DEV-809 名刺の選択リスト（カスタム項目）のマッピングが選択リストに設定した値のAPI名でマッピングされる。
  @isTest
  static void test_FieldBuilderFromPickList() {
    Account source = new Account(Name='テスト株式会社', Ownership='Public', Industry='Agriculture', AccountSource='Web');
    DescribeFieldResult dfrOwnership = Account.sObjectType.getDescribe().fields.getMap().get('Ownership').getDescribe();
    DescribeFieldResult dfrIndustry = Account.sObjectType.getDescribe().fields.getMap().get('Industry').getDescribe();
    DescribeFieldResult dfrAccountSource = Account.sObjectType.getDescribe().fields.getMap().get('AccountSource').getDescribe();
    SB_NameCard_RenkeiMapper.FieldBuilderFromPickList builderOwnership = new SB_NameCard_RenkeiMapper.FieldBuilderFromPickList('Ownership', dfrOwnership, dfrOwnership.getPicklistValues());
    SB_NameCard_RenkeiMapper.FieldBuilderFromPickList builderIndustry = new SB_NameCard_RenkeiMapper.FieldBuilderFromPickList('Industry', dfrIndustry, dfrIndustry.getPicklistValues());
    SB_NameCard_RenkeiMapper.FieldBuilderFromPickList builderAccountSource = new SB_NameCard_RenkeiMapper.FieldBuilderFromPickList('AccountSource', dfrAccountSource, dfrAccountSource.getPicklistValues());
    Account dest = new Account(Name='テスト株式会社2');
    builderOwnership.create(source, dest);
    builderIndustry.create(source, dest);
    builderAccountSource.create(source, dest);
    System.assertEquals(source.Ownership, dest.Ownership);
    System.assertEquals(source.Industry, dest.Industry);
    System.assertEquals(source.AccountSource, dest.AccountSource);
  }


}