sfdx-source/SmartVisca/main/default/objects/Account/fields/NameCard__c.field-meta.xml
<CustomField>
    <fullName>NameCard__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>名刺</label>
    <referenceTo>NameCard__c</referenceTo>
    <relationshipLabel>取引先</relationshipLabel>
    <relationshipName>AccountNameCards</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/Contact/fields/NameCard__c.field-meta.xml
<CustomField>
    <fullName>NameCard__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>名刺</label>
    <referenceTo>NameCard__c</referenceTo>
    <relationshipLabel>取引先責任者</relationshipLabel>
    <relationshipName>ContactNameCards</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/unpackaged/dev-config/main/default/objects/NameCard__c/NameCard__c.object-meta.xml
<CustomObject>
    <customHelpPage>SB_NameCard_UserGuide</customHelpPage>
    <description>スキャナから取り込んだ名刺情報がここに保存されます。
Business Card: Stores digitized business card information.</description>
    <label>名刺</label>
    <nameField>
        <label>氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/address__c.field-meta.xml
<CustomField>
    <fullName>address__c</fullName>
    <label>住所</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/address_pref__c.field-meta.xml
<CustomField>
    <fullName>address_pref__c</fullName>
    <label>都道府県</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/company_name__c.field-meta.xml
<CustomField>
    <fullName>company_name__c</fullName>
    <label>会社名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/delivery_type__c.field-meta.xml
<CustomField>
    <fullName>delivery_type__c</fullName>
    <inlineHelpText>1: 一次納品
2: 最終納品</inlineHelpText>
    <label>納品タイプ</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/division__c.field-meta.xml
<CustomField>
    <fullName>division__c</fullName>
    <label>所属</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/email__c.field-meta.xml
<CustomField>
    <fullName>email__c</fullName>
    <label>メールアドレス</label>
    <type>Email</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/first_name__c.field-meta.xml
<CustomField>
    <fullName>first_name__c</fullName>
    <description>英語名刺の場合</description>
    <label>ファーストネーム</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/last_name__c.field-meta.xml
<CustomField>
    <fullName>last_name__c</fullName>
    <description>英語名刺の場合</description>
    <label>ラストネーム</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/tel1__c.field-meta.xml
<CustomField>
    <fullName>tel1__c</fullName>
    <label>電話番号</label>
    <type>Phone</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/tel2__c.field-meta.xml
<CustomField>
    <fullName>tel2__c</fullName>
    <label>電話番号2</label>
    <type>Phone</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/zip_code__c.field-meta.xml
<CustomField>
    <fullName>zip_code__c</fullName>
    <label>郵便番号</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/NameCardBasicSetting__c.object-meta.xml
<CustomObject>
    <label>名刺基本設定</label>
    <nameField>
        <label>基本設定</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/HojinkakuEquationLongAndAbbr__c.field-meta.xml
<CustomField>
    <fullName>HojinkakuEquationLongAndAbbr__c</fullName>
    <defaultValue>false</defaultValue>
    <label>法人格の略称を正称の表記とみなして会社名を比較する</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccount_Street__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccount_Street__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:町名・番地</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountAddressPref__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountAddressPref__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:都道府県</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountCity__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountCity__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:市区郡</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountCompany__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountCompany__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:取引先名</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountNOExistCreateNew__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountNOExistCreateNew__c</fullName>
    <defaultValue>true</defaultValue>
    <description>自動連携での取引先のクエリの結果既存の取引先がなければ新規作成する</description>
    <label>自動連携:既存の取引先がなければ新規作成する</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountOverwrite__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountOverwrite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>自動連携:既存の取引先を上書きする</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountPhone__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountPhone__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:電話</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountSite__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountSite__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:取引先 部門</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountSitePartialMatch__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountSitePartialMatch__c</fullName>
    <defaultValue>false</defaultValue>
    <label>自動連携:部署は部分一致検索</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountURL__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountURL__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:Web サイト</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountZipCode__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountZipCode__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:郵便番号</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiActive__c.field-meta.xml
<CustomField>
    <fullName>RenkeiActive__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>名刺データが2次納品された時に取引先・取引先責任者を自動で作成したり更新したりすることができます。「SmartVisca連携設定」タブで連携する条件の設定をします。リード拡張パッケージがインストールされている場合、取引先・取引先責任者に加えてリードを作成・更新できます。</inlineHelpText>
    <label>自動連携:自動連携機能を有効化</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiContactFirstName__c.field-meta.xml
<CustomField>
    <fullName>RenkeiContactFirstName__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:名</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiContactLastName__c.field-meta.xml
<CustomField>
    <fullName>RenkeiContactLastName__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:姓</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiContactMail__c.field-meta.xml
<CustomField>
    <fullName>RenkeiContactMail__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:メールアドレス</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiContactNOExistCreateNew__c.field-meta.xml
<CustomField>
    <fullName>RenkeiContactNOExistCreateNew__c</fullName>
    <defaultValue>false</defaultValue>
    <description>自動連携での取引先をひもづけて、その取引先に名刺に相当する取引先責任者がなければ作成する。</description>
    <inlineHelpText>自動連携での取引先をひもづけて、その取引先に名刺に相当する取引先責任者がなければ作成する。</inlineHelpText>
    <label>自動連携:既存の取引先責任者がなければ新規作成する</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiContactOverwrite__c.field-meta.xml
<CustomField>
    <fullName>RenkeiContactOverwrite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>自動連携:既存の取引先責任者を上書きする</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiExcludeHojinkaku__c.field-meta.xml
<CustomField>
    <fullName>RenkeiExcludeHojinkaku__c</fullName>
    <defaultValue>true</defaultValue>
    <description>自動連携で既存取引先の検索で、会社名は法人格を除いて中間一致検索する</description>
    <label>自動連携:取引先名は法人格を除いて検索</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiExcludeHojinkakuPartial__c.field-meta.xml
<CustomField>
    <fullName>RenkeiExcludeHojinkakuPartial__c</fullName>
    <defaultValue>false</defaultValue>
    <label>自動連携:取引先名は法人格を除いて部分一致検索</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiInheritEvent__c.field-meta.xml
<CustomField>
    <fullName>RenkeiInheritEvent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>自動連携:名刺の活動履歴を引き継ぐ</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiSpecificItems__c.field-meta.xml
<CustomField>
    <fullName>RenkeiSpecificItems__c</fullName>
    <inlineHelpText>他の条件に加え、取込時にセットしたメモ（手書きメモではありません）の内容と、『指定項目』の文字列が一致した場合に同一の取引先とみなします。</inlineHelpText>
    <label>自動連携:指定項目</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/SmartViscaConfig__c/SmartViscaConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>SmartViscaの表示設定や、Triggerの設定を持ちます。</description>
    <label>SmartVisca設定</label>
</CustomObject>

sfdx-source/SmartVisca/main/default/objects/SmartViscaConfig__c/fields/AutoConvAccountSearchNotUsePhone2__c.field-meta.xml
<CustomField>
    <fullName>AutoConvAccountSearchNotUsePhone2__c</fullName>
    <defaultValue>false</defaultValue>
    <description>自動連携でアカウントの候補を探す処理で、名刺の電話番号2を取引先の電話番号と照合しません。</description>
    <label>自動連携: 電話番号2 は取引先候補の条件に使わない</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/SmartViscaConfig__c/fields/SFilterSearchResult__c.field-meta.xml
<CustomField>
    <fullName>SFilterSearchResult__c</fullName>
    <defaultValue>false</defaultValue>
    <description>で文字列指定の グローバル検索で、入力した文字列を以下の項目値と照合し、検索結果を絞ります。 
会社名、氏名、メールアドレス、電話番号1、電話番号2、携帯番号</description>
    <label>S検索結果を特定の項目値で絞り込む</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/SmartViscaConfig__c/fields/TriggerCreateFeedOnName__c.field-meta.xml
<CustomField>
    <fullName>TriggerCreateFeedOnName__c</fullName>
    <defaultValue>true</defaultValue>
    <description>名刺の追加時、既存の名刺の最新名刺を更新するので、そのとき、既存名刺の所有者にフィードで、通知します。</description>
    <label>トリガで同じ人と名刺交換したらフィードで知らせる</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/SmartViscaConfig__c/fields/TriggerHistoryIsActive__c.field-meta.xml
<CustomField>
    <fullName>TriggerHistoryIsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>トリガで名刺の履歴オブジェクトに1次納品、2次納品の履歴を保存します。</description>
    <label>トリガで名刺履歴を保存する</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/SmartViscaConfig__c/fields/TriggerLeadExRenkeiTriggerHandler__c.field-meta.xml
<CustomField>
    <fullName>TriggerLeadExRenkeiTriggerHandler__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Lead連携拡張パッケージの中にある 自動連携のトリガハンドラを呼ぶ</description>
    <inlineHelpText>サンブリッジサポートの指示があった場合のみ設定します。</inlineHelpText>
    <label>トリガでリード拡張パッケージの自動連携を使う</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/SmartViscaConfig__c/fields/TriggerMergeNameCards__c.field-meta.xml
<CustomField>
    <fullName>TriggerMergeNameCards__c</fullName>
    <defaultValue>true</defaultValue>
    <description>名刺を追加、更新、削除、復活したとき、名刺を名寄します。</description>
    <label>トリガで名刺データを名寄せする</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/SmartViscaConfig__c/fields/TriggerRegDateTime__c.field-meta.xml
<CustomField>
    <fullName>TriggerRegDateTime__c</fullName>
    <defaultValue>true</defaultValue>
    <description>名刺の追加、更新時、項目「取引先」、「リード」に値がセットされていたら、取引先取込日時 リード取込日時に現在時刻をセットします。</description>
    <label>トリガで取込日時をセットする</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/SmartViscaConfig__c/fields/TriggerRenkeiTriggerHandler__c.field-meta.xml
<CustomField>
    <fullName>TriggerRenkeiTriggerHandler__c</fullName>
    <defaultValue>true</defaultValue>
    <description>自動連携のトリガハンドラを呼ぶ</description>
    <inlineHelpText>サンブリッジサポートの指示があった場合のみ設定します。</inlineHelpText>
    <label>トリガで自動連携を行う</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/classes/SB_NameCard_RenkeiTriggerHelperTest5.cls
/**
 *
 * SB_NameCard_RenkeiTriggerHelperTest5
 *
 * v2.4 での 自動連携の改良のテスト 1
 *
 * SV_DEV-1638 自動連携の取引先検索で取引先名完全一致の取引先があればあいまい検索一致の取引先があっても重複にしないようにする
 *
 * SV_DEV-1647 法人格の正式名称と略称をマッチさせる（登録・自動連携）
 *
 * SV_DEV-893 【自動連携】1次納品段階で登録した活動履歴を取引先・取引先責任者に引き継ぎたい
 *
 * Copyright (C) 2019 SunBridge Inc. All Rights Reserved.
 *
 *  @author sawano
 *  @Version 1      2019.05.xx v2.4
 *
 **/
@isTest
private class SB_NameCard_RenkeiTriggerHelperTest5 {

  // 自動連携で電話番号2を使用するカスタム設定
  private class TestDb extends SB_NC_TestDB {

    // 会社名は(法人格含め)完全一致で自動連携の設定
    public override void initializeBasicSetting() {
      NameCardBasicSetting__c bs = SB_NC_PostInstallScript.createDefaultBasicSetting();
      bs.RenkeiActive__c = true;      // 自動連携機能有効
      bs.RenkeiAccountOverwrite__c = true;  // 既存の取引先を上書き
      bs.RenkeiContactOverwrite__c = true;   // 既存の取引先責任者を上書き
      bs.RenkeiAccountNOExistCreateNew__c = true;  //既存の取引先がなければ新規作成する
      bs.RenkeiContactNOExistCreateNew__c = true;  // 既存の取引先責任者がなければ新規作成する
      bs.RenkeiAccountCompany__c = true;   // アカウント 会社名
      bs.RenkeiAccountSite__c = false;        // アカウント 部署名
      bs.RenkeiAccountAddressPref__c = false;   // アカウント 都道府県
      bs.RenkeiAccount_Street__c = false;   // アカウント 町名・番地
      bs.RenkeiAccountZipCode__c = false;   // アカウント 郵便番号
      bs.RenkeiAccountCity__c = false;      // アカウント 市区郡
      bs.RenkeiAccountURL__c = false;       // アカウント URL
      bs.RenkeiAccountPhone__c = false;     // アカウント 電話番号 ※
      //bs.RenkeiSpecificItems__c = null;        // アカウント 特定項目
      bs.RenkeiExcludeHojinkakuPartial__c = false;      // 自動連携:会社名は法人格を除いて部分一致
      bs.RenkeiExcludeHojinkaku__c = false;      // 自動連携:会社名は法人格を除いて完全一致
      bs.RenkeiAccountSitePartialMatch__c = true;      // 自動連携:部署は中間一致検索
      //bs.RenkeiContactMail__c = true;      // コンタクト メールアドレス
      //bs.RenkeiContactLastName__c = true;  // コンタクト ラストネーム
      //bs.RenkeiContactFirstName__c = false; // コンタクト ファーストネーム

      listBasicSetting.add(bs);
    }
    // SmartVisca設定　
    // トリガを有効・無効
    // 自動連携: 電話番号2 は取引先候補の条件に使わない FALSE
    public virtual override void initializeSmartViscaConfig() {
      svConfig = SmartViscaConfig__c.getOrgDefaults();
      svConfig.TriggerRegDateTime__c = true;
      svConfig.TriggerCreateFeedOnName__c = false;
      svConfig.TriggerMergeNameCards__c = false;
      svConfig.TriggerHistoryIsActive__c = false;
      svConfig.TriggerRenkeiTriggerHandler__c = true; // v2.1 トリガで自動連携を行う
      svConfig.TriggerLeadExRenkeiTriggerHandler__c = false; // v2.1 トリガでリード拡張パッケージの自動連携を使う
      svConfig.SFilterSearchResult__c = false; // v2.2 S検索結果を特定の項目値で絞り込む
      svConfig.AutoConvAccountSearchNotUsePhone2__c = false;   // v2.2 自動連携: 電話番号2 は取引先候補の条件に使わない
    }

    public override void initialize() {
      // initializeUser();
      // if (listUser.isEmpty() == false) {
      //   insert listUser;
      // }
      // SmartVisca設定
      initializeSmartViscaConfig();
      if (svConfig !=null) {
        upsert svConfig;
      }
      // 名刺基本設定
      initializeBasicSetting();
      if (!listBasicSetting.isEmpty()) {
        insert listBasicSetting;
      }
      // 名刺連携項目マッピング
      initializeMapping();
      if (!listMapping.isEmpty()) {
        insert listMapping;
      }
    }
  } // TestDb


  @testSetup
  static void setupDB() {
    TestDb db = new TestDb();
    db.initialize();
  }

  // SV_DEV-1647 法人格の正式名称と略称をマッチさせる（登録・自動連携）
  @isTest
  static void test_Renkei_KabusikiKaisha_Variants() {
    // 会社名完全一致にする。
    NameCardBasicSetting__c bs = [SELECT Id, RenkeiExcludeHojinkakuPartial__c, RenkeiExcludeHojinkaku__c FROM NameCardBasicSetting__c LIMIT 1];
    bs.RenkeiExcludeHojinkakuPartial__c = false;      // 自動連携:会社名は法人格を除いて部分一致
    bs.RenkeiExcludeHojinkaku__c = false;      // 自動連携:会社名は法人格を除いて完全一致
    bs.HojinkakuEquationLongAndAbbr__c = true; // 	法人格の略称を正称の表記とみなして会社名を比較する
    update bs;

    List<Account> acnts = new List<Account>();
    acnts.add(new Account(Name='㈱テスト商事'));
    acnts.add(new Account(Name='株式会社 サンプル物産'));
    acnts.add(new Account(Name='有限会社テスト商事'));
    insert acnts;

    System.assertEquals(null, [SELECT Id, Name, Site, Phone, BillingState, ShippingState FROM Account WHERE Name = '㈱テスト商事' LIMIT 1].Site);
    System.assertEquals(null, [SELECT Id, Name, Site, Phone, BillingState, ShippingState FROM Account WHERE Name = '株式会社 サンプル物産' LIMIT 1].Site);
    System.assertEquals(null, [SELECT Id, Name, Site, Phone, BillingState, ShippingState FROM Account WHERE Name = '有限会社テスト商事' LIMIT 1].Site);

    Test.startTest();
    // 名刺 挿入
    List<NameCard__c> listCard = new List<NameCard__c>();
    listCard.add(new NameCard__c(Name='テスト 一郎', company_name__c='株式会社テスト商事', division__c='本社',
                    zip_code__c='150-0022', address_pref__c='東京都', address__c='渋谷区恵比寿南1-5-5',
                    tel1__c = '03-3333-3333', tel2__c = '03-4444-4444', // 電話番号
                    last_name__c='テスト', first_name__c='一郎', email__c='ichiro@test.com', delivery_type__c='2'));
    listCard.add(new NameCard__c(Name='テスト 一郎', company_name__c='（株）　サンプル物産', division__c='本社',
                    zip_code__c='150-0022', address_pref__c='東京都', address__c='渋谷区恵比寿南1-5-5',
                    tel1__c = '03-5555-5555', tel2__c = '03-6666-6666', // 電話番号
                    last_name__c='テスト', first_name__c='一郎', email__c='ichiro@sample.com', delivery_type__c='2'));

    insert listCard;
    Test.stopTest();

    System.assertEquals('本社', [SELECT Id, Name, Site, Phone, BillingState, ShippingState FROM Account WHERE Name = '㈱テスト商事' LIMIT 1].Site);
    System.assertEquals('本社', [SELECT Id, Name, Site, Phone, BillingState, ShippingState FROM Account WHERE Name = '株式会社 サンプル物産' LIMIT 1].Site);
    System.assertEquals(null, [SELECT Id, Name, Site, Phone, BillingState, ShippingState FROM Account WHERE Name = '有限会社テスト商事' LIMIT 1].Site);
  }

  // SV_DEV-1647 法人格の正式名称と略称をマッチさせる（登録・自動連携）
  //  正式名称と略称の２つある
  @isTest
  static void test_Renkei_KabusikiKaisha_Variants_duplicate() {
    // 会社名完全一致にする。
    NameCardBasicSetting__c bs = [SELECT Id, RenkeiExcludeHojinkakuPartial__c, RenkeiExcludeHojinkaku__c FROM NameCardBasicSetting__c LIMIT 1];
    bs.RenkeiExcludeHojinkakuPartial__c = false;      // 自動連携:会社名は法人格を除いて部分一致
    bs.RenkeiExcludeHojinkaku__c = false;      // 自動連携:会社名は法人格を除いて完全一致
    bs.HojinkakuEquationLongAndAbbr__c = true; // 	法人格の略称を正称の表記とみなして会社名を比較する
    update bs;

    List<Account> acnts = new List<Account>();
    acnts.add(new Account(Name='㈱テスト商事'));
    acnts.add(new Account(Name='株式会社テスト商事'));
    acnts.add(new Account(Name='株式会社 サンプル物産'));
    acnts.add(new Account(Name='有限会社テスト商事'));
    insert acnts;

    System.assertEquals(null, [SELECT Id, Name, Site, Phone, BillingState, ShippingState FROM Account WHERE Name = '㈱テスト商事' LIMIT 1].Site);
    System.assertEquals(null, [SELECT Id, Name, Site, Phone, BillingState, ShippingState FROM Account WHERE Name = '株式会社テスト商事' LIMIT 1].Site);
    System.assertEquals(null, [SELECT Id, Name, Site, Phone, BillingState, ShippingState FROM Account WHERE Name = '株式会社 サンプル物産' LIMIT 1].Site);
    System.assertEquals(null, [SELECT Id, Name, Site, Phone, BillingState, ShippingState FROM Account WHERE Name = '有限会社テスト商事' LIMIT 1].Site);

    Test.startTest();
    // 名刺 挿入
    List<NameCard__c> listCard = new List<NameCard__c>();
    listCard.add(new NameCard__c(Name='テスト 一郎', company_name__c='株式会社テスト商事', division__c='本社',
                    zip_code__c='150-0022', address_pref__c='東京都', address__c='渋谷区恵比寿南1-5-5',
                    tel1__c = '03-3333-3333', tel2__c = '03-4444-4444', // 電話番号
                    last_name__c='テスト', first_name__c='一郎', email__c='ichiro@test.com', delivery_type__c='2'));
    listCard.add(new NameCard__c(Name='テスト 一郎', company_name__c='（株）　サンプル物産', division__c='本社',
                    zip_code__c='150-0022', address_pref__c='東京都', address__c='渋谷区恵比寿南1-5-5',
                    tel1__c = '03-5555-5555', tel2__c = '03-6666-6666', // 電話番号
                    last_name__c='テスト', first_name__c='一郎', email__c='ichiro@sample.com', delivery_type__c='2'));

    insert listCard;
    Test.stopTest();

    System.assertEquals(null, [SELECT Id, Name, Site, Phone, BillingState, ShippingState FROM Account WHERE Name = '㈱テスト商事' LIMIT 1].Site);
    System.assertEquals(null, [SELECT Id, Name, Site, Phone, BillingState, ShippingState FROM Account WHERE Name = '株式会社テスト商事' LIMIT 1].Site);
    System.assertEquals('本社', [SELECT Id, Name, Site, Phone, BillingState, ShippingState FROM Account WHERE Name = '株式会社 サンプル物産' LIMIT 1].Site);
    System.assertEquals(null, [SELECT Id, Name, Site, Phone, BillingState, ShippingState FROM Account WHERE Name = '有限会社テスト商事' LIMIT 1].Site);
  }

  // SV_DEV-1638 自動連携の取引先検索で取引先名完全一致の取引先があればあいまい検索一致の取引先があっても重複にしないようにする
  // 中間一致で複数該当するが、完全一致が１つ
  @isTest
  static void test_Renkei_ManyAccounts_FullMatchOne() {
    // 会社名は法人格を除いて部分一致
    NameCardBasicSetting__c bs = [SELECT Id, RenkeiExcludeHojinkakuPartial__c, RenkeiExcludeHojinkaku__c FROM NameCardBasicSetting__c LIMIT 1];
    bs.RenkeiExcludeHojinkakuPartial__c = true;      // 自動連携:会社名は法人格を除いて部分一致
    bs.RenkeiExcludeHojinkaku__c = false;      // 自動連携:会社名は法人格を除いて完全一致
    update bs;

    List<Account> acnts = new List<Account>();
    acnts.add(new Account(Name='㈱テスト商事'));
    acnts.add(new Account(Name='株式会社 テスト商事運輸'));
    acnts.add(new Account(Name='有限会社 テスト商事'));
    insert acnts;
    System.assertEquals(null, [SELECT Id, Name, Site, Phone, BillingState, ShippingState FROM Account WHERE Name = '㈱テスト商事' LIMIT 1].Site);
    System.assertEquals(null, [SELECT Id, Name, Site, Phone, BillingState, ShippingState FROM Account WHERE Name = '株式会社 テスト商事運輸' LIMIT 1].Site);
    System.assertEquals(null, [SELECT Id, Name, Site, Phone, BillingState, ShippingState FROM Account WHERE Name = '有限会社 テスト商事' LIMIT 1].Site);

    Test.startTest();
    // 名刺 挿入
    List<NameCard__c> listCard = new List<NameCard__c>();
    listCard.add(new NameCard__c(Name='テスト 一郎', company_name__c='株式会社テスト商事', division__c='本社',
                    zip_code__c='150-0022', address_pref__c='東京都', address__c='渋谷区恵比寿南1-5-5',
                    tel1__c = '03-3333-3333', tel2__c = '03-4444-4444', // 電話番号
                    last_name__c='テスト', first_name__c='一郎', email__c='ichiro@test.com', delivery_type__c='2'));

    insert listCard;
    Test.stopTest();

    System.assertEquals('本社', [SELECT Id, Name, Site, Phone, BillingState, ShippingState FROM Account WHERE Name = '㈱テスト商事' LIMIT 1].Site);
    System.assertEquals(null, [SELECT Id, Name, Site, Phone, BillingState, ShippingState FROM Account WHERE Name = '株式会社 テスト商事運輸' LIMIT 1].Site);
    System.assertEquals(null, [SELECT Id, Name, Site, Phone, BillingState, ShippingState FROM Account WHERE Name = '有限会社 テスト商事' LIMIT 1].Site);

  }

  // SV_DEV-1638 自動連携の取引先検索で取引先名完全一致の取引先があればあいまい検索一致の取引先があっても重複にしないようにする
  // 中間一致で複数該当するが、完全一致が２つ
  @isTest
  static void test_Renkei_ManyAccounts_FullMatchTwo() {
    // 会社名は法人格を除いて部分一致
    NameCardBasicSetting__c bs = [SELECT Id, RenkeiExcludeHojinkakuPartial__c, RenkeiExcludeHojinkaku__c FROM NameCardBasicSetting__c LIMIT 1];
    bs.RenkeiExcludeHojinkakuPartial__c = true;      // 自動連携:会社名は法人格を除いて部分一致
    bs.RenkeiExcludeHojinkaku__c = false;      // 自動連携:会社名は法人格を除いて完全一致
    update bs;

    List<Account> acnts = new List<Account>();
    acnts.add(new Account(Name='㈱テスト商事'));
    acnts.add(new Account(Name='株式会社テスト商事'));
    acnts.add(new Account(Name='株式会社 テスト商事運輸'));
    acnts.add(new Account(Name='有限会社 テスト商事'));
    insert acnts;
    System.assertEquals(null, [SELECT Id, Name, Site, Phone, BillingState, ShippingState FROM Account WHERE Name = '㈱テスト商事' LIMIT 1].Site);
    System.assertEquals(null, [SELECT Id, Name, Site, Phone, BillingState, ShippingState FROM Account WHERE Name = '株式会社テスト商事' LIMIT 1].Site);
    System.assertEquals(null, [SELECT Id, Name, Site, Phone, BillingState, ShippingState FROM Account WHERE Name = '株式会社 テスト商事運輸' LIMIT 1].Site);
    System.assertEquals(null, [SELECT Id, Name, Site, Phone, BillingState, ShippingState FROM Account WHERE Name = '有限会社 テスト商事' LIMIT 1].Site);

    Test.startTest();
    // 名刺 挿入
    List<NameCard__c> listCard = new List<NameCard__c>();
    listCard.add(new NameCard__c(Name='テスト 一郎', company_name__c='株式会社テスト商事', division__c='本社',
                    zip_code__c='150-0022', address_pref__c='東京都', address__c='渋谷区恵比寿南1-5-5',
                    tel1__c = '03-3333-3333', tel2__c = '03-4444-4444', // 電話番号
                    last_name__c='テスト', first_name__c='一郎', email__c='ichiro@test.com', delivery_type__c='2'));

    insert listCard;
    Test.stopTest();

    System.assertEquals(null, [SELECT Id, Name, Site, Phone, BillingState, ShippingState FROM Account WHERE Name = '㈱テスト商事' LIMIT 1].Site);
    System.assertEquals(null, [SELECT Id, Name, Site, Phone, BillingState, ShippingState FROM Account WHERE Name = '株式会社テスト商事' LIMIT 1].Site);
    System.assertEquals(null, [SELECT Id, Name, Site, Phone, BillingState, ShippingState FROM Account WHERE Name = '株式会社 テスト商事運輸' LIMIT 1].Site);
    System.assertEquals(null, [SELECT Id, Name, Site, Phone, BillingState, ShippingState FROM Account WHERE Name = '有限会社 テスト商事' LIMIT 1].Site);

  }

  // SV_DEV-1638 自動連携の取引先検索で取引先名完全一致の取引先があればあいまい検索一致の取引先があっても重複にしないようにする
  // 中間一致で複数該当するが、完全一致がなし
  @isTest
  static void test_Renkei_ManyAccounts_FullMatchNo() {
    // 会社名は法人格を除いて部分一致
    NameCardBasicSetting__c bs = [SELECT Id, RenkeiExcludeHojinkakuPartial__c, RenkeiExcludeHojinkaku__c FROM NameCardBasicSetting__c LIMIT 1];
    bs.RenkeiExcludeHojinkakuPartial__c = true;      // 自動連携:会社名は法人格を除いて部分一致
    bs.RenkeiExcludeHojinkaku__c = false;      // 自動連携:会社名は法人格を除いて完全一致
    update bs;

    List<Account> acnts = new List<Account>();
    acnts.add(new Account(Name='テスト商事株式会社'));
    acnts.add(new Account(Name='株式会社 テスト商事運輸'));
    acnts.add(new Account(Name='有限会社 テスト商事'));
    insert acnts;
    System.assertEquals(null, [SELECT Id, Name, Site, Phone, BillingState, ShippingState FROM Account WHERE Name = 'テスト商事株式会社' LIMIT 1].Site);
    System.assertEquals(null, [SELECT Id, Name, Site, Phone, BillingState, ShippingState FROM Account WHERE Name = '株式会社 テスト商事運輸' LIMIT 1].Site);
    System.assertEquals(null, [SELECT Id, Name, Site, Phone, BillingState, ShippingState FROM Account WHERE Name = '有限会社 テスト商事' LIMIT 1].Site);

    Test.startTest();
    // 名刺 挿入
    List<NameCard__c> listCard = new List<NameCard__c>();
    listCard.add(new NameCard__c(Name='テスト 一郎', company_name__c='株式会社テスト商事', division__c='本社',
                    zip_code__c='150-0022', address_pref__c='東京都', address__c='渋谷区恵比寿南1-5-5',
                    tel1__c = '03-3333-3333', tel2__c = '03-4444-4444', // 電話番号
                    last_name__c='テスト', first_name__c='一郎', email__c='ichiro@test.com', delivery_type__c='2'));

    insert listCard;
    Test.stopTest();

    System.assertEquals(null, [SELECT Id, Name, Site, Phone, BillingState, ShippingState FROM Account WHERE Name = 'テスト商事株式会社' LIMIT 1].Site);
    System.assertEquals(null, [SELECT Id, Name, Site, Phone, BillingState, ShippingState FROM Account WHERE Name = '株式会社 テスト商事運輸' LIMIT 1].Site);
    System.assertEquals(null, [SELECT Id, Name, Site, Phone, BillingState, ShippingState FROM Account WHERE Name = '有限会社 テスト商事' LIMIT 1].Site);

  }

  // SV_DEV-893 【自動連携】1次納品段階で登録した活動履歴を取引先・取引先責任者に引き継ぎたい
  // 引き継ぐ設定
  @isTest
  static void test_Renkei_Acitivity_TakeOver_On() {
    // 会社名は法人格を除いて部分一致
    NameCardBasicSetting__c bs = [SELECT Id, RenkeiInheritEvent__c FROM NameCardBasicSetting__c LIMIT 1];
    bs.RenkeiInheritEvent__c = true;      // 自動連携:名刺の活動履歴を引き継ぐ
    update bs;

    List<Account> acnts = new List<Account>();
    acnts.add(new Account(Name='株式会社テスト商事'));
    insert acnts;

    Test.startTest();
    // 名刺 挿入
    List<NameCard__c> listCard = new List<NameCard__c>();
    listCard.add(new NameCard__c(Name='テスト 一郎', company_name__c='株式会社テスト商事', division__c='本社',
                    zip_code__c='150-0022', address_pref__c='東京都', address__c='渋谷区恵比寿南1-5-5',
                    tel1__c = '03-3333-3333', tel2__c = '03-4444-4444', // 電話番号
                    last_name__c='テスト', first_name__c='一郎', email__c='ichiro@test.com', delivery_type__c='1'));
    listCard.add(new NameCard__c(Name='テスト 一郎', company_name__c='（株）サンプル物産', division__c='本社',
                    zip_code__c='150-0022', address_pref__c='東京都', address__c='渋谷区恵比寿南1-5-5',
                    tel1__c = '03-5555-5555', tel2__c = '03-6666-6666', // 電話番号
                    last_name__c='テスト', first_name__c='一郎', email__c='ichiro@sample.com', delivery_type__c='1'));

    insert listCard;
    listCard = [SELECT Id, Name, OwnerId FROM NameCard__c WHERE delivery_type__c='1'];
    // 名刺にToDoをつける
    List<Task> listTask = new List<Task>();
    for (NameCard__c card : listCard) {
      listTask.add(new Task(Subject=card.Name + 'task', OwnerId=card.OwnerId, whatId=card.Id));
    }
    insert listTask;

    // 名刺に行動をつける
    List<Event> listEvent = new List<Event>();
    for (NameCard__c card : listCard) {
      listEvent.add(new Event(Subject=card.Name + 'event', OwnerId=card.OwnerId
        , IsAllDayEvent=true, ActivityDate=date.today(), whatId=card.Id));
    }
    insert listEvent;

    listCard = [SELECT Id, delivery_type__c FROM NameCard__c WHERE delivery_type__c='1'];
    for (NameCard__c card : listCard) {
      card.delivery_type__c = '2';
    }
    update listCard;

    Test.stopTest();

    System.assertEquals(1, [SELECT Id FROM Task WHERE WhoId IN (SELECT Id FROM Contact WHERE Account.Name='株式会社テスト商事')].size());
    System.assertEquals(1, [SELECT Id FROM Event WHERE WhoId IN (SELECT Id FROM Contact WHERE Account.Name='株式会社テスト商事')].size());
    System.assertEquals(1, [SELECT Id FROM Task WHERE WhoId IN (SELECT Id FROM Contact WHERE Account.Name='（株）サンプル物産')].size());
    System.assertEquals(1, [SELECT Id FROM Event WHERE WhoId IN (SELECT Id FROM Contact WHERE Account.Name='（株）サンプル物産')].size());

  }

  // SV_DEV-893 【自動連携】1次納品段階で登録した活動履歴を取引先・取引先責任者に引き継ぎたい
  // 引き継がない設定
  @isTest
  static void test_Renkei_Acitivity_TakeOver_Off() {
    // 会社名は法人格を除いて部分一致
    NameCardBasicSetting__c bs = [SELECT Id, RenkeiInheritEvent__c FROM NameCardBasicSetting__c LIMIT 1];
    bs.RenkeiInheritEvent__c = false;      // 自動連携:名刺の活動履歴を引き継ぐ
    update bs;

    List<Account> acnts = new List<Account>();
    acnts.add(new Account(Name='株式会社テスト商事'));
    insert acnts;

    Test.startTest();
    // 名刺 挿入
    List<NameCard__c> listCard = new List<NameCard__c>();
    listCard.add(new NameCard__c(Name='テスト 一郎', company_name__c='株式会社テスト商事', division__c='本社',
                    zip_code__c='150-0022', address_pref__c='東京都', address__c='渋谷区恵比寿南1-5-5',
                    tel1__c = '03-3333-3333', tel2__c = '03-4444-4444', // 電話番号
                    last_name__c='テスト', first_name__c='一郎', email__c='ichiro@test.com', delivery_type__c='1'));
    listCard.add(new NameCard__c(Name='テスト 一郎', company_name__c='（株）サンプル物産', division__c='本社',
                    zip_code__c='150-0022', address_pref__c='東京都', address__c='渋谷区恵比寿南1-5-5',
                    tel1__c = '03-5555-5555', tel2__c = '03-6666-6666', // 電話番号
                    last_name__c='テスト', first_name__c='一郎', email__c='ichiro@sample.com', delivery_type__c='1'));

    insert listCard;
    listCard = [SELECT Id, Name, OwnerId FROM NameCard__c WHERE delivery_type__c='1'];
    // 名刺にToDoをつける
    List<Task> listTask = new List<Task>();
    for (NameCard__c card : listCard) {
      listTask.add(new Task(Subject=card.Name + 'task', OwnerId=card.OwnerId, whatId=card.Id));
    }
    insert listTask;

    // 名刺に行動をつける
    List<Event> listEvent = new List<Event>();
    for (NameCard__c card : listCard) {
      listEvent.add(new Event(Subject=card.Name + 'event', OwnerId=card.OwnerId
        , IsAllDayEvent=true, ActivityDate=date.today(), whatId=card.Id));
    }
    insert listEvent;

    listCard = [SELECT Id, delivery_type__c FROM NameCard__c WHERE delivery_type__c='1'];
    for (NameCard__c card : listCard) {
      card.delivery_type__c = '2';
    }
    update listCard;

    Test.stopTest();

    System.assertEquals(0, [SELECT Id FROM Task WHERE WhoId IN (SELECT Id FROM Contact WHERE Account.Name='株式会社テスト商事')].size());
    System.assertEquals(0, [SELECT Id FROM Event WHERE WhoId IN (SELECT Id FROM Contact WHERE Account.Name='株式会社テスト商事')].size());
    System.assertEquals(0, [SELECT Id FROM Task WHERE WhoId IN (SELECT Id FROM Contact WHERE Account.Name='（株）サンプル物産')].size());
    System.assertEquals(0, [SELECT Id FROM Event WHERE WhoId IN (SELECT Id FROM Contact WHERE Account.Name='（株）サンプル物産')].size());

  }

}