sfdx-source/SmartVisca/main/default/objects/Account/fields/NameCard__c.field-meta.xml
<CustomField>
    <fullName>NameCard__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>名刺</label>
    <referenceTo>NameCard__c</referenceTo>
    <relationshipLabel>取引先</relationshipLabel>
    <relationshipName>AccountNameCards</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/Contact/fields/NameCard__c.field-meta.xml
<CustomField>
    <fullName>NameCard__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>名刺</label>
    <referenceTo>NameCard__c</referenceTo>
    <relationshipLabel>取引先責任者</relationshipLabel>
    <relationshipName>ContactNameCards</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/unpackaged/dev-config/main/default/objects/NameCard__c/NameCard__c.object-meta.xml
<CustomObject>
    <customHelpPage>SB_NameCard_UserGuide</customHelpPage>
    <description>スキャナから取り込んだ名刺情報がここに保存されます。
Business Card: Stores digitized business card information.</description>
    <label>名刺</label>
    <nameField>
        <label>氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/company_name__c.field-meta.xml
<CustomField>
    <fullName>company_name__c</fullName>
    <label>会社名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/delivery_type__c.field-meta.xml
<CustomField>
    <fullName>delivery_type__c</fullName>
    <inlineHelpText>1: 一次納品
2: 最終納品</inlineHelpText>
    <label>納品タイプ</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/email__c.field-meta.xml
<CustomField>
    <fullName>email__c</fullName>
    <label>メールアドレス</label>
    <type>Email</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/first_name__c.field-meta.xml
<CustomField>
    <fullName>first_name__c</fullName>
    <description>英語名刺の場合</description>
    <label>ファーストネーム</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCard__c/fields/last_name__c.field-meta.xml
<CustomField>
    <fullName>last_name__c</fullName>
    <description>英語名刺の場合</description>
    <label>ラストネーム</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/NameCardBasicSetting__c.object-meta.xml
<CustomObject>
    <label>名刺基本設定</label>
    <nameField>
        <label>基本設定</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/HojinkakuEquationLongAndAbbr__c.field-meta.xml
<CustomField>
    <fullName>HojinkakuEquationLongAndAbbr__c</fullName>
    <defaultValue>false</defaultValue>
    <label>法人格の略称を正称の表記とみなして会社名を比較する</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccount_Street__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccount_Street__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:町名・番地</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountAddressPref__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountAddressPref__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:都道府県</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountCity__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountCity__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:市区郡</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountCompany__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountCompany__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:取引先名</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountNOExistCreateNew__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountNOExistCreateNew__c</fullName>
    <defaultValue>true</defaultValue>
    <description>自動連携での取引先のクエリの結果既存の取引先がなければ新規作成する</description>
    <label>自動連携:既存の取引先がなければ新規作成する</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountOverwrite__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountOverwrite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>自動連携:既存の取引先を上書きする</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountPhone__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountPhone__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:電話</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountSite__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountSite__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:取引先 部門</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountSitePartialMatch__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountSitePartialMatch__c</fullName>
    <defaultValue>false</defaultValue>
    <label>自動連携:部署は部分一致検索</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountURL__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountURL__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:Web サイト</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountZipCode__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountZipCode__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:郵便番号</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiActive__c.field-meta.xml
<CustomField>
    <fullName>RenkeiActive__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>名刺データが2次納品された時に取引先・取引先責任者を自動で作成したり更新したりすることができます。「SmartVisca連携設定」タブで連携する条件の設定をします。リード拡張パッケージがインストールされている場合、取引先・取引先責任者に加えてリードを作成・更新できます。</inlineHelpText>
    <label>自動連携:自動連携機能を有効化</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiContactFirstName__c.field-meta.xml
<CustomField>
    <fullName>RenkeiContactFirstName__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:名</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiContactLastName__c.field-meta.xml
<CustomField>
    <fullName>RenkeiContactLastName__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:姓</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiContactMail__c.field-meta.xml
<CustomField>
    <fullName>RenkeiContactMail__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:メールアドレス</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiContactNOExistCreateNew__c.field-meta.xml
<CustomField>
    <fullName>RenkeiContactNOExistCreateNew__c</fullName>
    <defaultValue>false</defaultValue>
    <description>自動連携での取引先をひもづけて、その取引先に名刺に相当する取引先責任者がなければ作成する。</description>
    <inlineHelpText>自動連携での取引先をひもづけて、その取引先に名刺に相当する取引先責任者がなければ作成する。</inlineHelpText>
    <label>自動連携:既存の取引先責任者がなければ新規作成する</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiContactOverwrite__c.field-meta.xml
<CustomField>
    <fullName>RenkeiContactOverwrite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>自動連携:既存の取引先責任者を上書きする</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiExcludeHojinkaku__c.field-meta.xml
<CustomField>
    <fullName>RenkeiExcludeHojinkaku__c</fullName>
    <defaultValue>true</defaultValue>
    <description>自動連携で既存取引先の検索で、会社名は法人格を除いて中間一致検索する</description>
    <label>自動連携:取引先名は法人格を除いて検索</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiExcludeHojinkakuPartial__c.field-meta.xml
<CustomField>
    <fullName>RenkeiExcludeHojinkakuPartial__c</fullName>
    <defaultValue>false</defaultValue>
    <label>自動連携:取引先名は法人格を除いて部分一致検索</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiSpecificItems__c.field-meta.xml
<CustomField>
    <fullName>RenkeiSpecificItems__c</fullName>
    <inlineHelpText>他の条件に加え、取込時にセットしたメモ（手書きメモではありません）の内容と、『指定項目』の文字列が一致した場合に同一の取引先とみなします。</inlineHelpText>
    <label>自動連携:指定項目</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/classes/SB_NameCard_RenkeiTriggerHelperTest2.cls
/**
 *
 * SB_NameCard_RenkeiTriggerHelperTest2
 *  自動連携機能の、おもに 例外的なケースとか 会社名の照合のテストクラス
 *
 * Copyright (C) 2017 SunBridge Inc. All Rights Reserved.
 *
 *  @author sawano
 *  @Version 1      2017.11.xx v1.22 から
 *
 **/
@isTest
private class SB_NameCard_RenkeiTriggerHelperTest2
{

  // +--------------------
  public virtual class TestDb extends SB_NC_TestDB {

    public virtual override void initialize() {
      initializeUser();
      if (listUser.isEmpty() == false)
        insert listUser;
      // 名刺基本設定
      initializeBasicSetting();
      if (!listBasicSetting.isEmpty()) {
        insert listBasicSetting;
      }
      // 名刺連携項目マッピング
      initializeMapping();
      if (!listMapping.isEmpty()) {
        insert listMapping;
      }
    }
  } // public virtual class TestDb extends SB_NC_TestDB

  // 自動連携して 会社名は法人格を除いて完全一致
  public virtual class TestDbRenkeiExcludeHojinkaku extends TestDb {

    public virtual override void initializeBasicSetting() {
      NameCardBasicSetting__c bs = SB_NC_PostInstallScript.createDefaultBasicSetting();
      bs.RenkeiActive__c = true;      // 自動連携機能有効
      bs.RenkeiAccountOverwrite__c = true;   // 既存の取引先を上書き
      bs.RenkeiContactOverwrite__c = true;   // 既存の取引先責任者を上書き
      //bs.RenkeiAccountNOExistCreateNew__c = true; // 既存の取引先がなければ新規作成
      //bs.RenkeiContactNOExistCreateNew__c = true; // 既存の取引先責任者がなければ新規作成する
      //bs.RenkeiAccountAddressPref__c = false;   // アカウント 都道府県
      //bs.RenkeiAccount_Street__c = false;   // アカウント 町名・番地
      //bs.RenkeiAccountZipCode__c = false;   // アカウント 郵便番号
      //bs.RenkeiAccountCity__c = false;      // アカウント 市区郡
      //bs.RenkeiAccountURL__c = false;       // アカウント URL
      //bs.RenkeiAccountCompany__c = true;   // アカウント 会社名
      //bs.RenkeiAccountPhone__c = false;     // アカウント 電話番号
      //bs.RenkeiSpecificItems__c = null;        // アカウント 特定項目
      //bs.RenkeiAccountSite__c = false;        // アカウント 部署名
      bs.RenkeiExcludeHojinkakuPartial__c = false;      // 自動連携:会社名は法人格を除いて部分一致
      bs.RenkeiExcludeHojinkaku__c = true;      // 自動連携:会社名は法人格を除いて完全一致
      //bs.RenkeiAccountSitePartialMatch__c = true;      // 自動連携:部署は中間一致検索
      //bs.RenkeiContactMail__c = true;      // コンタクト メールアドレス
      //bs.RenkeiContactLastName__c = true;  // コンタクト ラストネーム
      //bs.RenkeiContactFirstName__c = false; // コンタクト ファーストネーム
      listBasicSetting.add(bs);
    }
  } // public virtual class TestDbRenkeiExcludeHojinkaku extends TestDb

  // 自動連携して 会社名は法人格を除いて部分一致
  public virtual class TestDbRenkeiExcludeHojinkakuPartial extends TestDb {

    public virtual override void initializeBasicSetting() {
      NameCardBasicSetting__c bs = SB_NC_PostInstallScript.createDefaultBasicSetting();
      bs.RenkeiActive__c = true;      // 自動連携機能有効
      bs.RenkeiAccountOverwrite__c = true;   // 既存の取引先を上書き
      bs.RenkeiContactOverwrite__c = true;   // 既存の取引先責任者を上書き
      //bs.RenkeiAccountNOExistCreateNew__c = true; // 既存の取引先がなければ新規作成
      //bs.RenkeiContactNOExistCreateNew__c = true; // 既存の取引先責任者がなければ新規作成する
      //bs.RenkeiAccountAddressPref__c = false;   // アカウント 都道府県
      //bs.RenkeiAccount_Street__c = false;   // アカウント 町名・番地
      //bs.RenkeiAccountZipCode__c = false;   // アカウント 郵便番号
      //bs.RenkeiAccountCity__c = false;      // アカウント 市区郡
      //bs.RenkeiAccountURL__c = false;       // アカウント URL
      //bs.RenkeiAccountCompany__c = true;   // アカウント 会社名
      //bs.RenkeiAccountPhone__c = false;     // アカウント 電話番号
      //bs.RenkeiSpecificItems__c = null;        // アカウント 特定項目
      //bs.RenkeiAccountSite__c = false;        // アカウント 部署名
      bs.RenkeiExcludeHojinkakuPartial__c = true;      // 自動連携:会社名は法人格を除いて部分一致
      bs.RenkeiExcludeHojinkaku__c = false;      // 自動連携:会社名は法人格を除いて完全一致
      //bs.RenkeiAccountSitePartialMatch__c = true;      // 自動連携:部署は中間一致検索
      //bs.RenkeiContactMail__c = true;      // コンタクト メールアドレス
      //bs.RenkeiContactLastName__c = true;  // コンタクト ラストネーム
      //bs.RenkeiContactFirstName__c = false; // コンタクト ファーストネーム
      listBasicSetting.add(bs);
    }
  } // public virtual class TestDbRenkeiExcludeHojinkakuPartial extends TestDb

  // 自動連携して 会社名は完全一致
  public virtual class TestDbRenkeiAccountNameMatch extends TestDb {

    public virtual override void initializeBasicSetting() {
      NameCardBasicSetting__c bs = SB_NC_PostInstallScript.createDefaultBasicSetting();
      bs.RenkeiActive__c = true;      // 自動連携機能有効
      bs.RenkeiAccountOverwrite__c = true;   // 既存の取引先を上書き
      bs.RenkeiContactOverwrite__c = true;   // 既存の取引先責任者を上書き
      //bs.RenkeiAccountNOExistCreateNew__c = true; // 既存の取引先がなければ新規作成
      //bs.RenkeiContactNOExistCreateNew__c = true; // 既存の取引先責任者がなければ新規作成する
      //bs.RenkeiAccountAddressPref__c = false;   // アカウント 都道府県
      //bs.RenkeiAccount_Street__c = false;   // アカウント 町名・番地
      //bs.RenkeiAccountZipCode__c = false;   // アカウント 郵便番号
      //bs.RenkeiAccountCity__c = false;      // アカウント 市区郡
      //bs.RenkeiAccountURL__c = false;       // アカウント URL
      //bs.RenkeiAccountCompany__c = true;   // アカウント 会社名
      //bs.RenkeiAccountPhone__c = false;     // アカウント 電話番号
      //bs.RenkeiSpecificItems__c = null;        // アカウント 特定項目
      //bs.RenkeiAccountSite__c = false;        // アカウント 部署名
      bs.RenkeiExcludeHojinkakuPartial__c = false;      // 自動連携:会社名は法人格を除いて部分一致
      bs.RenkeiExcludeHojinkaku__c = false;      // 自動連携:会社名は法人格を除いて完全一致
      //bs.RenkeiAccountSitePartialMatch__c = true;      // 自動連携:部署は中間一致検索
      //bs.RenkeiContactMail__c = true;      // コンタクト メールアドレス
      //bs.RenkeiContactLastName__c = true;  // コンタクト ラストネーム
      //bs.RenkeiContactFirstName__c = false; // コンタクト ファーストネーム
      bs.HojinkakuEquationLongAndAbbr__c = true; // 	法人格の略称を正称の表記とみなして会社名を比較する
      listBasicSetting.add(bs);
    }
  } // public virtual class TestDbRenkeiAccountNameMatch extends TestDb
  // +--------------------

  // 自動連携して 会社名は法人格を除いて完全一致
  @isTest
  static void test_RenkeiExcludeHojinkaku() {
    TestDb db = new TestDbRenkeiExcludeHojinkaku();
    db.initialize();

    Test.startTest();
    List<Account> listAccount = new List<Account>();
    listAccount.add(new Account(Name='株式会社 テスト商事'));
    insert listAccount;
    List<NameCard__c> listCard = new List<NameCard__c>();
    listCard.add(new NameCard__c(Name='テスト 一郎', company_name__c='株式会社テスト商事', last_name__c='テスト', first_name__c='一郎', email__c='ichiro@test.com', delivery_type__c='2'));
    listCard.add(new NameCard__c(Name='テスト 二郎', company_name__c='㈱テスト商事', last_name__c='テスト', first_name__c='二郎', email__c='jiro@test.com', delivery_type__c='2'));
    insert listCard;
    Test.stopTest();
    List<Account> updatedAccount = [SELECT Id, Name FROM Account];
    System.assertEquals(1, updatedAccount.size());
    List<Contact> updatedContact = [SELECT Id, Name FROM Contact];
    System.assertEquals(listCard.size(), updatedContact.size());
  }

  // 自動連携して 会社名は法人格を除いて部分一致
  @isTest
  static void test_RenkeiExcludeHojinkakuPartial() {
    TestDb db = new TestDbRenkeiExcludeHojinkakuPartial();
    db.initialize();

    Test.startTest();
    List<Account> listAccount = new List<Account>();
    listAccount.add(new Account(Name='株式会社いわゆるテスト商事商会'));
    insert listAccount;
    List<NameCard__c> listCard = new List<NameCard__c>();
    listCard.add(new NameCard__c(Name='テスト 一郎', company_name__c='株式会社テスト商事', last_name__c='テスト', first_name__c='一郎', email__c='ichiro@test.com', delivery_type__c='2'));
    listCard.add(new NameCard__c(Name='テスト 二郎', company_name__c='㈱テスト商事', last_name__c='テスト', first_name__c='二郎', email__c='jiro@test.com', delivery_type__c='2'));
    insert listCard;
    Test.stopTest();
    List<Account> updatedAccount = [SELECT Id, Name FROM Account];
    System.assertEquals(1, updatedAccount.size());
    List<Contact> updatedContact = [SELECT Id, Name FROM Contact];
    System.assertEquals(listCard.size(), updatedContact.size());
  }

  // 自動連携して 会社名は完全一致
  @isTest
  static void test_RenkeiAccountNameMatch() {
    TestDb db = new TestDbRenkeiAccountNameMatch();
    db.initialize();

    Test.startTest();
    List<Account> listAccount = new List<Account>();
    listAccount.add(new Account(Name='株式会社 テスト商事'));
    insert listAccount;
    List<NameCard__c> listCard = new List<NameCard__c>();
    listCard.add(new NameCard__c(Name='テスト 一郎', company_name__c='株式会社テスト商事', last_name__c='テスト', first_name__c='一郎', email__c='ichiro@test.com', delivery_type__c='2'));
    listCard.add(new NameCard__c(Name='テスト 二郎', company_name__c='㈱テスト商事', last_name__c='テスト', first_name__c='二郎', email__c='jiro@test.com', delivery_type__c='2'));
    insert listCard;
    Test.stopTest();
    List<Account> updatedAccount = [SELECT Id, Name FROM Account];
    // System.assertEquals(3, updatedAccount.size());
    System.assertEquals(1, updatedAccount.size());    // 2019.05.xx v2.4 SV_DEV-1647 法人格の正式名称と略称をマッチさせる（登録・自動連携） により 1つになる
    List<Contact> updatedContact = [SELECT Id, Name FROM Contact];
    System.assertEquals(listCard.size(), updatedContact.size());
  }


  // バックスラッシュとか、シングルクオートとかちゃんとしょりできるかテスト
  // 自動連携して 会社名は法人格を除いて一致。＼は ワイルドカード _ に変換してるので、SOQL で = で条件にするとヒットしないので、これでテスト
  // SV_DEV-673 会社名に全角バックスラッシュが含まれる名刺を自動連携すると、ORA-01424エラーが発生
  @isTest
  static void test_RenkeiAccountNameEscaoe() {
    TestDb db = new TestDbRenkeiExcludeHojinkakuPartial(); // 自動連携して 会社名は法人格を除いて一致
    db.initialize();

    List<Account> listAccount = new List<Account>();
    //listAccount.add(new Account(Name='株式会社テスト商事'));
    listAccount.add(new Account(Name='株式会社aaa\\aaa'));
    listAccount.add(new Account(Name='株式会社aaa\\\\aaa'));
    listAccount.add(new Account(Name='株式会社aaa\\\\aa\'a'));
    listAccount.add(new Account(Name='株式会社TBWA＼HAKUHODO'));
    listAccount.add(new Account(Name='HOGEHOGE＼FUGAFUGA'));
    listAccount.add(new Account(Name='株式会社TBWA＼HAKUH\'ODO'));
    listAccount.add(new Account(Name='恵比寿\'株式会社'));
    insert listAccount;
    List<Account> acnts = [SELECT Id, Name FROM Account];
    System.assertEquals(listAccount.size(), acnts.size());
    List<Contact> conts = [SELECT Id, Name FROM Contact];
    System.assertEquals(0, conts.size());

    Test.startTest();
    List<NameCard__c> listCard = new List<NameCard__c>();
    //listCard.add(new NameCard__c(Name='テスト 太郎', company_name__c='株式会社テスト商事', last_name__c='テスト', first_name__c='太郎', email__c='taro@test.com', delivery_type__c='2'));
    listCard.add(new NameCard__c(Name='テスト 一郎', company_name__c='株式会社aaa\\aaa', last_name__c='テスト', first_name__c='一郎', email__c='ichiro@test.com', delivery_type__c='2'));
    // 以下の２つ \\ がつづくと SB_NameCard_Util.getStringForPartialMatch の方をつかわないとだめ
    listCard.add(new NameCard__c(Name='テスト 二郎', company_name__c='株式会社aaa\\\\aaa', last_name__c='テスト', first_name__c='二郎', email__c='jiro@test.com', delivery_type__c='2'));
    listCard.add(new NameCard__c(Name='テスト 三郎', company_name__c='株式会社aaa\\\\aa\'a', last_name__c='テスト', first_name__c='三郎', email__c='saburo@test.com', delivery_type__c='2'));
    listCard.add(new NameCard__c(Name='テスト 四郎', company_name__c='株式会社TBWA＼HAKUHODO', last_name__c='テスト', first_name__c='四郎', email__c='shiro@test.com', delivery_type__c='2'));
    listCard.add(new NameCard__c(Name='テスト 四郎', company_name__c='HOGEHOGE＼FUGAFUGA', last_name__c='テスト', first_name__c='四郎', email__c='shiro@test.com', delivery_type__c='2'));
    listCard.add(new NameCard__c(Name='テスト 五郎', company_name__c='株式会社TBWA＼HAKUH\'ODO', last_name__c='テスト', first_name__c='五郎', email__c='goro@test.com', delivery_type__c='2'));
    listCard.add(new NameCard__c(Name='テスト 六郎', company_name__c='恵比寿\'株式会社', last_name__c='テスト', first_name__c='六郎', email__c='rokuro@test.com', delivery_type__c='2'));
    insert listCard;
    Test.stopTest();
    acnts = [SELECT Id, Name FROM Account];
    System.assertEquals(listAccount.size(), acnts.size());
    conts = [SELECT Id, Name FROM Contact];
    System.assertEquals(listCard.size(), conts.size());
  }


  // バックスラッシュとか、シングルクオートとかちゃんとしょりできるかテスト
  // 完全一致なら、置換やエスケープはしないので、それでいいかどうか
  @isTest
  static void test_RenkeiAccountNameWIthoutEscaoe() {
    TestDb db = new TestDbRenkeiAccountNameMatch(); // 自動連携して 会社名は 完全一致
    db.initialize();

    List<Account> listAccount = new List<Account>();
    //listAccount.add(new Account(Name='株式会社テスト商事'));
    listAccount.add(new Account(Name='株式会社aaa\\aaa'));
    listAccount.add(new Account(Name='株式会社aaa\\\\aaa'));
    listAccount.add(new Account(Name='株式会社aaa\\\\aa\'a'));
    listAccount.add(new Account(Name='株式会社TBWA＼HAKUHODO'));
    listAccount.add(new Account(Name='HOGEHOGE＼FUGAFUGA'));
    listAccount.add(new Account(Name='株式会社TBWA＼HAKUH\'ODO'));
    listAccount.add(new Account(Name='恵比寿\'株式会社'));
    insert listAccount;
    List<Account> acnts = [SELECT Id, Name FROM Account];
    System.assertEquals(listAccount.size(), acnts.size());
    List<Contact> conts = [SELECT Id, Name FROM Contact];
    System.assertEquals(0, conts.size());

    Test.startTest();
    List<NameCard__c> listCard = new List<NameCard__c>();
    //listCard.add(new NameCard__c(Name='テスト 太郎', company_name__c='株式会社テスト商事', last_name__c='テスト', first_name__c='太郎', email__c='taro@test.com', delivery_type__c='2'));
    listCard.add(new NameCard__c(Name='テスト 一郎', company_name__c='株式会社aaa\\aaa', last_name__c='テスト', first_name__c='一郎', email__c='ichiro@test.com', delivery_type__c='2'));
    listCard.add(new NameCard__c(Name='テスト 二郎', company_name__c='株式会社aaa\\\\aaa', last_name__c='テスト', first_name__c='二郎', email__c='jiro@test.com', delivery_type__c='2'));
    listCard.add(new NameCard__c(Name='テスト 三郎', company_name__c='株式会社aaa\\\\aa\'a', last_name__c='テスト', first_name__c='三郎', email__c='saburo@test.com', delivery_type__c='2'));
    listCard.add(new NameCard__c(Name='テスト 四郎', company_name__c='株式会社TBWA＼HAKUHODO', last_name__c='テスト', first_name__c='四郎', email__c='shiro@test.com', delivery_type__c='2'));
    listCard.add(new NameCard__c(Name='テスト 四郎', company_name__c='HOGEHOGE＼FUGAFUGA', last_name__c='テスト', first_name__c='四郎', email__c='shiro@test.com', delivery_type__c='2'));
    listCard.add(new NameCard__c(Name='テスト 五郎', company_name__c='株式会社TBWA＼HAKUH\'ODO', last_name__c='テスト', first_name__c='五郎', email__c='goro@test.com', delivery_type__c='2'));
    listCard.add(new NameCard__c(Name='テスト 六郎', company_name__c='恵比寿\'株式会社', last_name__c='テスト', first_name__c='六郎', email__c='rokuro@test.com', delivery_type__c='2'));
    insert listCard;
    Test.stopTest();
    acnts = [SELECT Id, Name FROM Account];
    System.assertEquals(listAccount.size(), acnts.size());
    conts = [SELECT Id, Name FROM Contact];
    System.assertEquals(listCard.size(), conts.size());
  }



}