sfdx-source/SmartVisca/main/default/objects/Account/fields/NameCard__c.field-meta.xml
<CustomField>
    <fullName>NameCard__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>名刺</label>
    <referenceTo>NameCard__c</referenceTo>
    <relationshipLabel>取引先</relationshipLabel>
    <relationshipName>AccountNameCards</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/Contact/fields/NameCard__c.field-meta.xml
<CustomField>
    <fullName>NameCard__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>名刺</label>
    <referenceTo>NameCard__c</referenceTo>
    <relationshipLabel>取引先責任者</relationshipLabel>
    <relationshipName>ContactNameCards</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>NameCard__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>名刺</label>
        <referenceTo>SmartViscaf__NameCard__c</referenceTo>
        <relationshipLabel>リード</relationshipLabel>
        <relationshipName>NameCards</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/SmartViscaf__NameCard__c.object
<CustomObject>
    <fields>
        <fullName>campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>キャンペーン</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>名刺</relationshipLabel>
        <relationshipName>nc_campaign</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

sfdx-source/unpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__account__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>名刺</relationshipLabel>
    <relationshipName>nc_account</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/unpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__address__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__address__c</fullName>
    <label>住所</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/unpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__address_pref__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__address_pref__c</fullName>
    <label>都道府県</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__card_exchange_date__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__card_exchange_date__c</fullName>
    <label>名刺交換日</label>
    <type>Date</type>
</CustomField>

sfdx-source/unpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__company_name__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__company_name__c</fullName>
    <label>会社名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__contact__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>取引先責任者</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>名刺</relationshipLabel>
    <relationshipName>nc_contact</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__email__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__email__c</fullName>
    <label>メールアドレス</label>
    <type>Email</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__fax1__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__fax1__c</fullName>
    <label>FAX番号</label>
    <type>Phone</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__lead__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>リード</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>名刺</relationshipLabel>
    <relationshipName>nc_lead</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/unpackaged - コピー/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__mobile__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__mobile__c</fullName>
    <label>携帯電話番号</label>
    <type>Phone</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__person_name_first__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__person_name_first__c</fullName>
    <label>名</label>
    <length>127</length>
    <type>Text</type>
</CustomField>

sfdx-source/unpackaged - コピー/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__person_name_last__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__person_name_last__c</fullName>
    <label>姓</label>
    <length>127</length>
    <type>Text</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__tel1__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__tel1__c</fullName>
    <label>電話番号</label>
    <type>Phone</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__title_name__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__title_name__c</fullName>
    <label>役職</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/unpackaged - コピー/main/default/objects/SmartViscaf__NameCard__c/fields/SmartViscaf__zip_code__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__zip_code__c</fullName>
    <label>郵便番号</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sfdx-source/unpackaged/dev-config/main/default/objects/SmartViscaf__NameCardBasicSetting__c/SmartViscaf__NameCardBasicSetting__c.object-meta.xml
<CustomObject>
    <label>名刺基本設定</label>
    <nameField>
        <label>基本設定</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCardBasicSetting__c/fields/SmartViscaf__RegistAccountNotOverWrite__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__RegistAccountNotOverWrite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>取引先登録:取引先を名刺情報で上書きしない</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCardBasicSetting__c/fields/SmartViscaf__RegistContactNotOverWrite__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__RegistContactNotOverWrite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>取引先登録:取引先責任者を名刺情報で上書きしない</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCardBasicSetting__c/fields/SmartViscaf__RegistDispAccountRectype__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__RegistDispAccountRectype__c</fullName>
    <defaultValue>true</defaultValue>
    <label>取引先登録:取引先レコードタイプ選択を表示する</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/unpackaged/main/default/objects/SmartViscaf__NameCardBasicSetting__c/fields/SmartViscaf__RegistDispContactRectype__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__RegistDispContactRectype__c</fullName>
    <defaultValue>true</defaultValue>
    <label>取引先登録:取引先責任者レコードタイプ選択を表示する</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCardBasicSetting__c/fields/SmartViscaf__RenkeiAccountAddressPref__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__RenkeiAccountAddressPref__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:都道府県</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/unpackaged/main/default/objects/SmartViscaf__NameCardBasicSetting__c/fields/SmartViscaf__RenkeiAccountCity__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__RenkeiAccountCity__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:市区郡</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/unpackaged/main/default/objects/SmartViscaf__NameCardBasicSetting__c/fields/SmartViscaf__RenkeiAccountCompany__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__RenkeiAccountCompany__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:取引先名</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/unpackaged/main/default/objects/SmartViscaf__NameCardBasicSetting__c/fields/SmartViscaf__RenkeiAccountNOExistCreateNew__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__RenkeiAccountNOExistCreateNew__c</fullName>
    <defaultValue>true</defaultValue>
    <description>自動連携での取引先のクエリの結果既存の取引先がなければ新規作成する</description>
    <label>自動連携:既存の取引先がなければ新規作成する</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/unpackaged - コピー/main/default/objects/SmartViscaf__NameCardBasicSetting__c/fields/SmartViscaf__RenkeiAccountOverwrite__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__RenkeiAccountOverwrite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>自動連携:既存の取引先を上書きする</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCardBasicSetting__c/fields/SmartViscaf__RenkeiAccountQueryRecordTypeIds__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__RenkeiAccountQueryRecordTypeIds__c</fullName>
    <description>自動連携で既存の取引先を検索するときの対象とするレコードタイプ。</description>
    <label>自動連携:自動連携で検索対象の取引先レコードタイプ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCardBasicSetting__c/fields/SmartViscaf__RenkeiAccountRecordTypes__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__RenkeiAccountRecordTypes__c</fullName>
    <label>自動連携:取引先レコードタイプ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCardBasicSetting__c/fields/SmartViscaf__RenkeiAccountSite__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__RenkeiAccountSite__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:取引先 部門</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCardBasicSetting__c/fields/SmartViscaf__RenkeiAccountZipCode__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__RenkeiAccountZipCode__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:郵便番号</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCardBasicSetting__c/fields/SmartViscaf__RenkeiContactFirstName__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__RenkeiContactFirstName__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:名</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/unpackaged/main/default/objects/SmartViscaf__NameCardBasicSetting__c/fields/SmartViscaf__RenkeiContactLastName__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__RenkeiContactLastName__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:姓</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCardBasicSetting__c/fields/SmartViscaf__RenkeiContactMail__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__RenkeiContactMail__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:メールアドレス</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/unpackaged/main/default/objects/SmartViscaf__NameCardBasicSetting__c/fields/SmartViscaf__RenkeiContactNOExistCreateNew__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__RenkeiContactNOExistCreateNew__c</fullName>
    <defaultValue>false</defaultValue>
    <description>自動連携での取引先をひもづけて、その取引先に名刺に相当する取引先責任者がなければ作成する。</description>
    <inlineHelpText>自動連携での取引先をひもづけて、その取引先に名刺に相当する取引先責任者がなければ作成する。</inlineHelpText>
    <label>自動連携:既存の取引先責任者がなければ新規作成する</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/unpackaged/main/default/objects/SmartViscaf__NameCardBasicSetting__c/fields/SmartViscaf__RenkeiContactQueryRecordTypeIds__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__RenkeiContactQueryRecordTypeIds__c</fullName>
    <description>自動連携で既存の取引先責任者を検索するときの対象とするレコードタイプ。</description>
    <label>自動連携:自動連携で検索対象の取引先責任者レコードタイプ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/unpackaged/main/default/objects/SmartViscaf__NameCardBasicSetting__c/fields/SmartViscaf__RenkeiSpecificItems__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__RenkeiSpecificItems__c</fullName>
    <inlineHelpText>他の条件に加え、取込時にセットしたメモ（手書きメモではありません）の内容と、『指定項目』の文字列が一致した場合に同一の取引先とみなします。</inlineHelpText>
    <label>自動連携:指定項目</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/unpackaged/qa-config/main/default/objects/SmartViscaf__NameCardRenkeiMapping__c/SmartViscaf__NameCardRenkeiMapping__c.object-meta.xml
<CustomObject>
    <label>名刺連携項目マッピング</label>
    <nameField>
        <displayFormat>RM-{000000}</displayFormat>
        <label>名刺連携項目マッピングNo</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

sfdx-source/unpackaged - コピー/main/default/objects/SmartViscaf__NameCardRenkeiMapping__c/fields/SmartViscaf__BasicSetting__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__BasicSetting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>名刺基本設定</label>
    <referenceTo>SmartViscaf__NameCardBasicSetting__c</referenceTo>
    <relationshipLabel>名刺連携項目マッピング</relationshipLabel>
    <relationshipName>BasicSetting</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCardRenkeiMapping__c/fields/SmartViscaf__IsActive__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>有効</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SVunpackaged/main/default/objects/SmartViscaf__NameCardRenkeiMapping__c/fields/SmartViscaf__NameCardName__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__NameCardName__c</fullName>
    <label>名刺の項目(API名称)</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/unpackaged/main/default/objects/SmartViscaf__NameCardRenkeiMapping__c/fields/SmartViscaf__TargetName__c.field-meta.xml
<CustomField>
    <fullName>SmartViscaf__TargetName__c</fullName>
    <label>対象の項目(API名称)</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/classes/SB_NameCardL_TwowayRegistControllerTest.cls
@isTest
private class SB_NameCardL_TwowayRegistControllerTest {

  /**
    * @description 実行ユーザを作成するメソッド
  **/
  private static List<User> insertUser() {
    List<User> us = new List<User>();
    Profile prof = [SELECT Id, UserType, Name FROM Profile WHERE Name = 'System Administrator' OR Name = 'システム管理者'];
    User u = new User(Alias = 'test', Email='newusertest@testorgtest.com',
    EmailEncodingKey='UTF-8', LastName='Testingtest', LanguageLocaleKey='en_US',
    LocaleSidKey='en_US', ProfileId = prof.Id,UserPermissionsMarketingUser = true,
    TimeZoneSidKey='America/Los_Angeles', UserName='newusertesttest@testorgtestA.com');

    User u1 = new User(Alias = 'test1', Email='newusertest1@testorgtest.com',
    EmailEncodingKey='UTF-8', LastName='Testingtest1', LanguageLocaleKey='en_US',
    LocaleSidKey='en_US', ProfileId = prof.Id,UserPermissionsMarketingUser = true,
    TimeZoneSidKey='America/Los_Angeles', UserName='newusertesttest1@testorgtestB.com');
    insert new User[]{u, u1};

    us.add(u);
    us.add(u1);
    return us;
  }

  /**
    * @description データー作成用のメソッド
  **/
  private static void setData(Boolean needNameCard, Boolean needAccount, Boolean needContact, Boolean needLead, Boolean needCampaign) {
    SmartViscaf__NameCard__c nc = new SmartViscaf__NameCard__c();
    nc.SmartViscaf__zip_code__c = '150-0022';
    nc.SmartViscaf__address_pref__c = '東京都';
    nc.SmartViscaf__address__c = '渋谷区恵比寿南';
    nc.SmartViscaf__company_name__c = 'TestCompany';
    nc.SmartViscaf__tel1__c = '03-1111-1111';
    nc.SmartViscaf__fax1__c = '03-1111-1112';
    nc.SmartViscaf__title_name__c = 'TestTitle';
    nc.SmartViscaf__person_name_last__c = 'TestLast';
    nc.SmartViscaf__person_name_first__c = 'TestFirst';
    nc.SmartViscaf__email__c = 'Test@test.com';

    //nc.SmartViscaf__email__c = 'test@sbnc.example.com';
    nc.SmartViscaf__mobile__c = '090-1111-1111';
    nc.SmartViscaf__card_exchange_date__c = Date.today();

    Database.DMLOptions dml = new Database.DMLOptions();

    dml.OptAllOrNone = false;

    if (needCampaign) {
      Campaign cc = new Campaign();
      cc.Name = 'test';
      if (needNameCard) {
        Database.SaveResult sr = SmartViscaf.SB_NameCard_CrudFls.screate(new List<Campaign>{cc},dml)[0];
        System.assertEquals(0, sr.getErrors().size(), 'saveCampaign error');
      }
      nc.campaign__c = cc.Id;
    }

    Database.SaveResult sr1 = SmartViscaf.SB_NameCard_CrudFls.screate(new List<SmartViscaf__NameCard__c>{nc},dml)[0];
    System.assertEquals(0, sr1.getErrors().size(), 'savenamecard error');

    System.debug('SB_NameCard_LeadRegistTest nc.Id: '+nc.Id);
    Account a ;
    if (needAccount) {
      a = new Account(Name = 'TestCompany');
      a.SmartViscaf__NameCard__c = nc.Id;
      a.Site = 'TestSite';
      a.BillingState = 'TestBillingState';
      insert a;
      nc.SmartViscaf__account__c = a.Id;
    }

    if (needContact) {
      Contact cont = new Contact();
      if (a != null) {
        cont.AccountId = a.Id;
      }
      cont.LastName = 'TestLast';
      cont.FirstName = 'TestFirst';
      cont.SmartViscaf__NameCard__c = nc.Id;
      cont.MailingState = 'TestMailingState';
      cont.Title = 'TestTitle';
      cont.MobilePhone = '1234321';
      cont.Email = 'Test@test.com';
      cont.Department = 'TestDepartment';
      insert cont;
      nc.SmartViscaf__contact__c = cont.Id;
    }

    if (needLead) {
      Lead lea = new Lead();
      lea.LastName = 'TestLast';
      lea.FirstName = 'TestFirst';
      lea.Company = 'TestCompany';
      lea.NameCard__c = nc.Id;
      lea.Email = 'Test@test.com';
      lea.MobilePhone = '123321';
      lea.Title = 'TestTitle';
      lea.State = 'TestState';
      insert lea;
      nc.SmartViscaf__lead__c = lea.Id;
    }
    update nc;
  }

  /**
    * @description 連携マッピング用データー作成するメソッド
  **/
  private static void setMappingDate() {
    SmartViscaf__NameCardBasicSetting__c setting = new SmartViscaf__NameCardBasicSetting__c();
    setting.Name = 'BasicSetting';
    setting.SmartViscaf__RenkeiContactFirstName__c = false;
    setting.SmartViscaf__RenkeiContactLastName__c = false;
    setting.SmartViscaf__RenkeiAccountCompany__c = false;
    setting.SmartViscaf__RenkeiContactMail__c = false;
    setting.SmartViscaf__RenkeiAccountSite__c = false;
    setting.SmartViscaf__RenkeiAccountZipCode__c = false;
    setting.SmartViscaf__RenkeiSpecificItems__c = 'Name';
    setting.SmartViscaf__RenkeiAccountRecordTypes__c  = '123;321';
    setting.SmartViscaf__RenkeiAccountAddressPref__c = false;
    setting.SmartViscaf__RenkeiAccountQueryRecordTypeIds__c = '123;01228000000vWgqAAE';
    setting.SmartViscaf__RenkeiContactQueryRecordTypeIds__c = '01228000000w0mBAAQ;01228000000vWgqAAE';
    setting.SmartViscaf__RenkeiAccountCity__c = false;
    setting.SmartViscaf__RenkeiAccountOverwrite__c = true;
    setting.SmartViscaf__RenkeiAccountNOExistCreateNew__c = true;
    setting.SmartViscaf__RenkeiAccountRecordTypes__c = '01228000000vWgqAAE';
    setting.SmartViscaf__RegistDispAccountRectype__c = true; // 取引先・取引先任者に登録 取引先レコードタイプ選択を表示する
    setting.SmartViscaf__RegistAccountNotOverWrite__c = false; // 取引先・取引先任者に登録 取引先を名刺情報で上書きしない
    setting.SmartViscaf__RegistDispContactRectype__c = true; // 取引先・取引先任者に登録 取引先責任者レコードタイプ選択を表示する
    setting.SmartViscaf__RegistContactNotOverWrite__c = false; // 取引先・取引先任者に登録 取引先責任者を名刺情報で上書きしない
    setting.SmartViscaf__RenkeiAccountNOExistCreateNew__c = true;  //既存の取引先がなければ新規作成する
    setting.SmartViscaf__RenkeiContactNOExistCreateNew__c = true;  // 既存の取引先責任者がなければ新規作成する
    insert setting;

    String objname = 'SmartViscaf__NameCardRenkeiMapping__c';
    List<RecordType> res = [SELECT Id,Name,Developername FROM RecordType WHERE SobjectType = :objname AND Developername ='Lead'];
    System.debug('resresres' + res);
    List<SmartViscaf__NameCardRenkeiMapping__c> testmapplist = new List<SmartViscaf__NameCardRenkeiMapping__c>();
    SmartViscaf__NameCardRenkeiMapping__c amap = new SmartViscaf__NameCardRenkeiMapping__c();
    amap.SmartViscaf__IsActive__c = true;
    amap.SmartViscaf__TargetName__c = 'Company';
    amap.SmartViscaf__NameCardName__c = 'SmartViscaf__company_name__c';
    amap.SmartViscaf__BasicSetting__c = setting.Id;
    if(res.size()>0){
        amap.RecordTypeId = res[0].Id;
    }
    testmapplist.add(amap);

    SmartViscaf__NameCardRenkeiMapping__c cmap = new SmartViscaf__NameCardRenkeiMapping__c();
    cmap.SmartViscaf__IsActive__c = true;
    cmap.SmartViscaf__TargetName__c = 'LastName';
    cmap.SmartViscaf__NameCardName__c = 'SmartViscaf__person_name_last__c';
    if(res.size()>1){
        cmap.RecordTypeId = res[0].Id;
    }
    testmapplist.add(cmap);
    cmap.SmartViscaf__BasicSetting__c = setting.Id;


    insert testmapplist;
  }

  /**
    * @description ChangeOwnerメソッドのテストメソッド
  **/
  static testMethod void testChangeOwner() {
    List<User> us = insertUser();
    System.runAs(us[0]) {
      setData(true, true, true, true, true);
      List<SmartViscaf__NameCard__c> cards = [SELECT Id,
                                                     SmartViscaf__company_name__c,
                                                     SmartViscaf__person_name_last__c
                                                FROM SmartViscaf__NameCard__c];
      System.assertEquals(1, cards.size());
      List<Account> acc = [SELECT Id
                             FROM Account];
      System.assertEquals(1, acc.size());
      List<Contact> con = [SELECT Id
                          FROM Contact];
      System.assertEquals(1, con.size());
      List<Lead> lea = [SELECT Id
                          FROM Lead];
      System.assertEquals(1, lea.size());
      PageReference pageRef = Page.SB_NameCardL_TwowayRegist;
      pageRef.getParameters().put('lookUpContactIndex', '2');
      Test.setCurrentPage(pageRef);
      ApexPages.StandardController sc = new ApexPages.StandardController(cards[0]);
      SB_NameCardL_TwowayRegistController ctrl = new SB_NameCardL_TwowayRegistController(sc);
      ctrl.registTodo = true;
      ctrl.canEditTodo = false;
      ctrl.changeOwner();
      System.assertEquals(false, ctrl.registTodo);
      ctrl.registTodo = true;
      ctrl.canEditTodo = true;
      ctrl.changeOwner();
      System.assertEquals(true, ctrl.registTodo);
    }
  }

  /**
    * @description cancelメソッドのテストメソッド
  **/
  static testMethod void testCnacel() {
    List<User> us = insertUser();
    System.runAs(us[0]) {
      setData(true, true, true, true, true);
      List<SmartViscaf__NameCard__c> cards = [SELECT Id,
                                                     SmartViscaf__company_name__c,
                                                     SmartViscaf__person_name_last__c
                                                FROM SmartViscaf__NameCard__c];
      System.assertEquals(1, cards.size());
      List<Account> acc = [SELECT Id
                             FROM Account];
      System.assertEquals(1, acc.size());
      List<Contact> con = [SELECT Id
                          FROM Contact];
      System.assertEquals(1, con.size());
      List<Lead> lea = [SELECT Id
                          FROM Lead];
      System.assertEquals(1, lea.size());
      PageReference pageRef = Page.SB_NameCardL_TwowayRegist;
      Test.setCurrentPage(pageRef);
      ApexPages.StandardController sc = new ApexPages.StandardController(cards[0]);
      SB_NameCardL_TwowayRegistController ctrl = new SB_NameCardL_TwowayRegistController(sc);
      System.assertEquals((new ApexPages.StandardController(cards[0])).view().getUrl(), ctrl.cancel().getUrl());
    }
  }

  /**
    * @description LeadCandidate innerclassに関するテストメソッド
  **/
  static testMethod void testLeadCandidate() {
    List<User> us = insertUser();
    System.runAs(us[0]) {
      setData(true, true, true, true, true);
      List<SmartViscaf__NameCard__c> cards = [SELECT Id,
                                                     SmartViscaf__company_name__c,
                                                     SmartViscaf__person_name_last__c
                                                FROM SmartViscaf__NameCard__c];
      System.assertEquals(1, cards.size());
      List<Account> acc = [SELECT Id
                             FROM Account];
      System.assertEquals(1, acc.size());
      List<Contact> con = [SELECT Id
                          FROM Contact];
      System.assertEquals(1, con.size());
      List<Lead> lea = [SELECT Id, Name
                          FROM Lead];
      System.assertEquals(1, lea.size());
      PageReference pageRef = Page.SB_NameCardL_TwowayRegist;
      Test.setCurrentPage(pageRef);
      ApexPages.StandardController sc = new ApexPages.StandardController(cards[0]);
      SB_NameCardL_TwowayRegistController ctrl = new SB_NameCardL_TwowayRegistController(sc);
      System.assertEquals(3, ctrl.leadRecordList.size());
      ctrl.lookUpIndex = 0;
      SB_NameCardL_TwowayRegistController.LeadCandidate leadRec = (SB_NameCardL_TwowayRegistController.LeadCandidate)ctrl.leadRecordList.get(ctrl.lookUpIndex);
      System.assertEquals(lea[0].Name, leadRec.getLeadName());
      System.assertEquals(lea[0].Id, leadRec.getLeadId());
      System.assertEquals('Testingtest', leadRec.getLeadOwnerName());
      System.assertEquals('TestTitle', leadRec.getTitle());
      System.assertEquals('123321', leadRec.getMobile());
      System.assertEquals('test@test.com', leadRec.getEmail());
      System.assertNotEquals(null, leadRec.getLastModifiedDate());
      System.assertEquals('TestCompany', leadRec.getLeadCompany());
      System.assertEquals(us[0].Id, leadRec.getLeadOwnerId());
      System.assertEquals('TestState', leadRec.getState());
      leadRec.adopt(cards[0]);
    }
  }

  /**
    * @description LeadLookupCandidate innerclassに関するテストメソッド
  **/
  static testMethod void testLeadLookupCandidate() {
    List<User> us = insertUser();
    System.runAs(us[0]) {
      setData(true, true, true, true, true);
      List<SmartViscaf__NameCard__c> cards = [SELECT Id,
                                                     SmartViscaf__company_name__c,
                                                     SmartViscaf__person_name_last__c
                                                FROM SmartViscaf__NameCard__c];
      System.assertEquals(1, cards.size());
      List<Account> acc = [SELECT Id
                             FROM Account];
      System.assertEquals(1, acc.size());
      List<Contact> con = [SELECT Id
                          FROM Contact];
      System.assertEquals(1, con.size());
      List<Lead> lea = [SELECT Id, Name
                          FROM Lead];
      System.assertEquals(1, lea.size());
      PageReference pageRef = Page.SB_NameCardL_TwowayRegist;
      Test.setCurrentPage(pageRef);
      ApexPages.StandardController sc = new ApexPages.StandardController(cards[0]);
      SB_NameCardL_TwowayRegistController ctrl = new SB_NameCardL_TwowayRegistController(sc);
      System.assertEquals(3, ctrl.leadRecordList.size());
      ctrl.lookUpIndex = 1;
      SB_NameCardL_TwowayRegistController.LeadLookupCandidate leadRec = (SB_NameCardL_TwowayRegistController.LeadLookupCandidate)ctrl.leadRecordList.get(ctrl.lookUpIndex);
      leadRec.card4Lookup.SmartViscaf__lead__c = lea[0].Id;
      System.assertEquals(null, leadRec.getLeadCompany());
      System.assertEquals(null, leadRec.getLeadOwnerId());
      System.assertEquals(null, leadRec.getLastModifiedDate());
      System.assertEquals(null, leadRec.getEmail());
      System.assertEquals(null, leadRec.getMobile());
      System.assertEquals(null, leadRec.getTitle());
      System.assertEquals(null, leadRec.getLeadOwnerName());
      System.assertEquals(null, leadRec.getLeadId());
      System.assertEquals(null, leadRec.getLeadName());
      ctrl.setLookUp();
      System.assertEquals('TestCompany', leadRec.getLeadCompany());
      System.assertEquals(us[0].Id, leadRec.getLeadOwnerId());
      System.assertNotEquals(null, leadRec.getLastModifiedDate());
      System.assertEquals('test@test.com', leadRec.getEmail());
      System.assertEquals('123321', leadRec.getMobile());
      System.assertEquals('TestTitle', leadRec.getTitle());
      System.assertEquals('Testingtest', leadRec.getLeadOwnerName());
      System.assertEquals(lea[0].Id, leadRec.getLeadId());
      System.assertEquals(lea[0].Name, leadRec.getLeadName());
      leadRec.adopt(cards[0]);
      leadRec.postLookup();
    }
  }

  /**
    * @description NewLeadCandidate innerclassに関するテストメソッド
  **/
  static testMethod void testNewLeadCandidate() {
    List<User> us = insertUser();
    System.runAs(us[0]) {
      setData(true, true, true, true, true);
      List<SmartViscaf__NameCard__c> cards = [SELECT Id,
                                                     SmartViscaf__company_name__c,
                                                     SmartViscaf__person_name_last__c,
                                                     SmartViscaf__person_name_first__c
                                                FROM SmartViscaf__NameCard__c];
      System.assertEquals(1, cards.size());
      List<Account> acc = [SELECT Id
                             FROM Account];
      System.assertEquals(1, acc.size());
      List<Contact> con = [SELECT Id
                          FROM Contact];
      System.assertEquals(1, con.size());
      List<Lead> lea = [SELECT Id, Name
                          FROM Lead];
      System.assertEquals(1, lea.size());
      PageReference pageRef = Page.SB_NameCardL_TwowayRegist;
      Test.setCurrentPage(pageRef);
      ApexPages.StandardController sc = new ApexPages.StandardController(cards[0]);
      SB_NameCardL_TwowayRegistController ctrl = new SB_NameCardL_TwowayRegistController(sc);
      System.assertEquals(3, ctrl.leadRecordList.size());
      ctrl.lookUpIndex = 2;
      SB_NameCardL_TwowayRegistController.NewLeadCandidate leadRec = (SB_NameCardL_TwowayRegistController.NewLeadCandidate)ctrl.leadRecordList.get(ctrl.lookUpIndex);
      System.assertEquals(String.format(System.Label.SB_NCLD_Label_CreateNewLeadDEV, new String[]{ Account.sObjectType.getDescribe().getLabel() }), leadRec.getAccountName());
      System.assertEquals(String.format(System.Label.SB_NCLD_Label_CreateNewLeadDEV, new String[]{ Contact.sObjectType.getDescribe().getLabel() }), leadRec.getContactName());
      System.assertEquals(String.format(System.Label.SB_NCLD_Label_CreateNewLeadDEV, new String[]{ Lead.sObjectType.getDescribe().getLabel() }), leadRec.getLeadName());
      leadRec.adopt(cards[0]);
    }
  }

  /**
    * @description ContactCandidate innerclassに関するテストメソッド
  **/
  static testMethod void testContactCandidate() {
    List<User> us = insertUser();
    System.runAs(us[0]) {
      setData(true, true, true, true, true);
      List<SmartViscaf__NameCard__c> cards = [SELECT Id,
                                                     SmartViscaf__division__c,
                                                     SmartViscaf__company_name__c,
                                                     SmartViscaf__person_name_last__c,
                                                     SmartViscaf__person_name_first__c
                                                FROM SmartViscaf__NameCard__c];
      System.assertEquals(1, cards.size());
      List<Account> acc = [SELECT Id
                             FROM Account];
      System.assertEquals(1, acc.size());
      List<Contact> con = [SELECT Id,
                                  Name
                          FROM Contact];
      System.assertEquals(1, con.size());
      List<Lead> lea = [SELECT Id, Name
                          FROM Lead];
      System.assertEquals(1, lea.size());
      PageReference pageRef = Page.SB_NameCardL_TwowayRegist;
      Test.setCurrentPage(pageRef);
      ApexPages.StandardController sc = new ApexPages.StandardController(cards[0]);
      SB_NameCardL_TwowayRegistController ctrl = new SB_NameCardL_TwowayRegistController(sc);
      System.assertEquals(5, ctrl.candidateTable.size());
      SB_NameCardL_TwowayRegistController.ContactCandidate contachRec = (SB_NameCardL_TwowayRegistController.ContactCandidate)ctrl.candidateTable.get(0);

      System.assertEquals('TestCompany', contachRec.getAccountName());
      System.assertEquals(acc[0].Id, contachRec.getAccountId());
      System.assertEquals(con[0].Name, contachRec.getContactName());
      System.assertEquals(con[0].Id, contachRec.getContactId());
      System.assertEquals('Testingtest', contachRec.getAccountOwnerName());
      System.assertEquals('Testingtest', contachRec.getContactOwnerName());
      System.assertEquals(us[0].Id, contachRec.getAccountOwnerId());
      System.assertEquals(us[0].Id, contachRec.getContactOwnerId());
      System.assertEquals('TestDepartment', contachRec.getDivision());
      System.assertEquals('TestMailingState', contachRec.getState());
      System.assertEquals('TestTitle', contachRec.getTitle());
      System.assertEquals('1234321', contachRec.getMobile());
      System.assertEquals('test@test.com', contachRec.getEmail());
      System.assertNotEquals(null, contachRec.getLastModifiedDate());
      contachRec.adopt(cards[0]);
    }
  }

  /**
    * @description AccountCandidate innerclassに関するテストメソッド
  **/
  static testMethod void testAccountCandidate() {
    List<User> us = insertUser();
    System.runAs(us[0]) {
      setData(true, true, true, true, true);
      List<SmartViscaf__NameCard__c> cards = [SELECT Id,
                                                     SmartViscaf__division__c,
                                                     SmartViscaf__company_name__c,
                                                     SmartViscaf__person_name_last__c,
                                                     SmartViscaf__person_name_first__c
                                                FROM SmartViscaf__NameCard__c];
      System.assertEquals(1, cards.size());
      List<Account> acc = [SELECT Id
                             FROM Account];
      System.assertEquals(1, acc.size());
      List<Contact> con = [SELECT Id
                          FROM Contact];
      System.assertEquals(1, con.size());
      List<Lead> lea = [SELECT Id, Name
                          FROM Lead];
      System.assertEquals(1, lea.size());
      PageReference pageRef = Page.SB_NameCardL_TwowayRegist;
      Test.setCurrentPage(pageRef);
      ApexPages.StandardController sc = new ApexPages.StandardController(cards[0]);
      SB_NameCardL_TwowayRegistController ctrl = new SB_NameCardL_TwowayRegistController(sc);
      System.assertEquals(5, ctrl.candidateTable.size());
      SB_NameCardL_TwowayRegistController.AccountCandidate contachRec = (SB_NameCardL_TwowayRegistController.AccountCandidate)ctrl.candidateTable.get(1);

      System.assertEquals('TestCompany', contachRec.getAccountName());
      System.assertEquals(acc[0].Id, contachRec.getAccountId());
      System.assertEquals(String.format(System.Label.SB_NCLD_Label_CreateNewLeadDEV, new String[]{ Contact.sObjectType.getDescribe().getLabel() }), contachRec.getContactName());
      System.assertEquals('Testingtest', contachRec.getAccountOwnerName());
      System.assertEquals('TestSite', contachRec.getDivision());
      System.assertEquals('TestBillingState', contachRec.getState());
      System.assertNotEquals(null, contachRec.getLastModifiedDate());
      System.assertEquals(us[0].Id, contachRec.getAccountOwnerId());
      contachRec.adopt(cards[0]);
    }
  }

  /**
    * @description 取引先責任者参照テスト
  **/
  static testMethod void testContactSetLookup() {
    List<User> us = insertUser();
    System.runAs(us[0]) {
      setData(true, true, true, true, true);
      List<SmartViscaf__NameCard__c> cards = [SELECT Id,
                                                     SmartViscaf__company_name__c,
                                                     SmartViscaf__person_name_last__c
                                                FROM SmartViscaf__NameCard__c];
      System.assertEquals(1, cards.size());
      List<Account> acc = [SELECT Id
                             FROM Account];
      System.assertEquals(1, acc.size());
      List<Contact> con = [SELECT Id
                          FROM Contact];
      System.assertEquals(1, con.size());
      List<Lead> lea = [SELECT Id, Name
                          FROM Lead];
      System.assertEquals(1, lea.size());
      PageReference pageRef = Page.SB_NameCardL_TwowayRegist;
      Test.setCurrentPage(pageRef);
      ApexPages.StandardController sc = new ApexPages.StandardController(cards[0]);
      SB_NameCardL_TwowayRegistController ctrl = new SB_NameCardL_TwowayRegistController(sc);
      System.assertEquals(3, ctrl.leadRecordList.size());
      pageRef.getParameters().put('lookUpContactIndex', '2');
      SB_NameCardL_TwowayRegistController.ContactLookupCandidate contachRec = (SB_NameCardL_TwowayRegistController.ContactLookupCandidate)ctrl.candidateTable.get(2);
      contachRec.card4Lookup.SmartViscaf__contact__c = con[0].Id;
      System.assertEquals(null, contachRec.getAccountName());
      System.assertEquals(null, contachRec.getAccountOwnerName());
      System.assertEquals(null, contachRec.getLastModifiedDate());
      System.assertEquals(null, contachRec.getAccountOwnerId());
      System.assertEquals(null, contachRec.getContactOwnerId());
      ctrl.postLookupContact();
      System.assertEquals('TestCompany', contachRec.getAccountName());
      System.assertEquals('Testingtest', contachRec.getAccountOwnerName());
      System.assertNotEquals(null, contachRec.getLastModifiedDate());
      System.assertEquals(us[0].Id, contachRec.getAccountOwnerId());
      System.assertEquals(us[0].Id, contachRec.getContactOwnerId());
      contachRec.adopt(cards[0]);
    }
  }

  /**
    * @description AccountLookupCandidate innerclassに関するテストメソッド
  **/
  static testMethod void testAccountLookupCandidate() {
    List<User> us = insertUser();
    System.runAs(us[0]) {
      setData(true, true, true, true, true);
      List<SmartViscaf__NameCard__c> cards = [SELECT Id,
                                                     SmartViscaf__division__c,
                                                     SmartViscaf__company_name__c,
                                                     SmartViscaf__person_name_last__c,
                                                     SmartViscaf__person_name_first__c
                                                FROM SmartViscaf__NameCard__c];
      System.assertEquals(1, cards.size());
      List<Account> acc = [SELECT Id
                             FROM Account];
      System.assertEquals(1, acc.size());
      List<Contact> con = [SELECT Id
                          FROM Contact];
      System.assertEquals(1, con.size());
      List<Lead> lea = [SELECT Id, Name
                          FROM Lead];
      System.assertEquals(1, lea.size());
      PageReference pageRef = Page.SB_NameCardL_TwowayRegist;
      Test.setCurrentPage(pageRef);
      ApexPages.StandardController sc = new ApexPages.StandardController(cards[0]);
      SB_NameCardL_TwowayRegistController ctrl = new SB_NameCardL_TwowayRegistController(sc);
      System.assertEquals(5, ctrl.candidateTable.size());
      SB_NameCardL_TwowayRegistController.AccountLookupCandidate contachRec = (SB_NameCardL_TwowayRegistController.AccountLookupCandidate)ctrl.candidateTable.get(3);
      contachRec.card4Lookup.SmartViscaf__account__c = acc[0].Id;

      System.assertEquals(null, contachRec.getDivision());
      System.assertEquals(null, contachRec.getState());
      System.assertEquals(String.format(System.Label.SB_NCLD_Label_CreateNewLeadDEV, new String[]{ Contact.sObjectType.getDescribe().getLabel() }), contachRec.getContactName());
      System.assertEquals(null, contachRec.getAccountOwnerId());
      contachRec.postLookup();

      System.assertEquals('TestSite', contachRec.getDivision());
      System.assertEquals('TestBillingState', contachRec.getState());
      System.assertEquals(String.format(System.Label.SB_NCLD_Label_CreateNewLeadDEV, new String[]{ Contact.sObjectType.getDescribe().getLabel() }), contachRec.getContactName());
      System.assertEquals(us[0].Id, contachRec.getAccountOwnerId());
      contachRec.adopt(cards[0]);
    }
  }

  /**
    * @description NewAccountCandidate innerclassに関するテストメソッド
  **/
  static testMethod void testNewAccountCandidate() {
    List<User> us = insertUser();
    System.runAs(us[0]) {
      setData(true, true, true, true, true);
      List<SmartViscaf__NameCard__c> cards = [SELECT Id,
                                                     SmartViscaf__division__c,
                                                     SmartViscaf__company_name__c,
                                                     SmartViscaf__person_name_last__c,
                                                     SmartViscaf__person_name_first__c
                                                FROM SmartViscaf__NameCard__c];
      System.assertEquals(1, cards.size());
      List<Account> acc = [SELECT Id
                             FROM Account];
      System.assertEquals(1, acc.size());
      List<Contact> con = [SELECT Id
                          FROM Contact];
      System.assertEquals(1, con.size());
      List<Lead> lea = [SELECT Id, Name
                          FROM Lead];
      System.assertEquals(1, lea.size());
      PageReference pageRef = Page.SB_NameCardL_TwowayRegist;
      Test.setCurrentPage(pageRef);
      ApexPages.StandardController sc = new ApexPages.StandardController(cards[0]);
      SB_NameCardL_TwowayRegistController ctrl = new SB_NameCardL_TwowayRegistController(sc);
      System.assertEquals(5, ctrl.candidateTable.size());
      SB_NameCardL_TwowayRegistController.NewAccountCandidate contachRec = (SB_NameCardL_TwowayRegistController.NewAccountCandidate)ctrl.candidateTable.get(4);
      System.assertEquals(String.format(System.Label.SB_NCLD_Label_CreateNewLeadDEV, new String[]{ Account.sObjectType.getDescribe().getLabel() }), contachRec.getAccountName());
      System.assertEquals(String.format(System.Label.SB_NCLD_Label_CreateNewLeadDEV, new String[]{ Contact.sObjectType.getDescribe().getLabel() }), contachRec.getContactName());
      contachRec.adopt(cards[0]);
    }
  }

  /**
    * @description 
  **/
  static testMethod void testCheckRadio() {
    List<User> us = insertUser();
    System.runAs(us[0]) {
      setData(true, true, true, true, true);
      List<SmartViscaf__NameCard__c> cards = [SELECT Id,
                                                     SmartViscaf__company_name__c,
                                                     SmartViscaf__person_name_last__c
                                                FROM SmartViscaf__NameCard__c];
      System.assertEquals(1, cards.size());
      List<Account> acc = [SELECT Id
                             FROM Account];
      System.assertEquals(1, acc.size());
      List<Contact> con = [SELECT Id
                          FROM Contact];
      System.assertEquals(1, con.size());
      List<Lead> lea = [SELECT Id
                          FROM Lead];
      System.assertEquals(1, lea.size());
      PageReference pageRef = Page.SB_NameCardL_TwowayRegist;
      Test.setCurrentPage(pageRef);
      ApexPages.StandardController sc = new ApexPages.StandardController(cards[0]);
      SB_NameCardL_TwowayRegistController ctrl = new SB_NameCardL_TwowayRegistController(sc);
      List<RecordTypeInfo> LEADRECORDTYPES = SB_NameCardL_TwowayRegistController.getRecordType(Lead.sObjectType);
      ctrl.leadRecordListIndex = 0;
      ctrl.checkRadio();
      System.assertEquals(false, ctrl.leadRecTypeEdit);
      ctrl.leadRecordListIndex = ctrl.leadRecordList.size() - 1;
      ctrl.checkRadio();
      System.assertEquals(true, ctrl.leadRecTypeEdit);
    }
  }

  static testMethod void testMethod1() {
    List<User> us = insertUser();
    System.runAs(us[0]) {
      setData(true, true, true, true, true);
      List<SmartViscaf__NameCard__c> cards = [SELECT Id,
                                                     SmartViscaf__company_name__c,
                                                     SmartViscaf__person_name_last__c
                                                FROM SmartViscaf__NameCard__c];
      System.assertEquals(1, cards.size());
      List<Account> acc = [SELECT Id
                             FROM Account];
      System.assertEquals(1, acc.size());
      List<Contact> con = [SELECT Id
                          FROM Contact];
      System.assertEquals(1, con.size());
      List<Lead> lea = [SELECT Id
                          FROM Lead];
      System.assertEquals(1, lea.size());
      PageReference pageRef = Page.SB_NameCardL_TwowayRegist;
      Test.setCurrentPage(pageRef);
      ApexPages.StandardController sc = new ApexPages.StandardController(cards[0]);
      SB_NameCardL_TwowayRegistController ctrl = new SB_NameCardL_TwowayRegistController(sc);
      SB_NameCardL_TwowayRegistController.getRenkeiTypeList();
      SB_NameCardL_TwowayRegistController.getSearchTypeList();
      System.assertEquals(3, ctrl.leadRecordList.size());
      System.assertEquals(5, ctrl.candidateTable.size());
      ctrl.leadRecordListIndex = 0;
      ctrl.accountTableIndex = 0;
      ctrl.candidateTable[2].card4Lookup.SmartViscaf__contact__c = con[0].Id;
      ctrl.getSearchTypeSelectOpts();
      ctrl.getleadRecordTypeOptions();
      ctrl.getContRecTypeSelectOpts();
      ctrl.getAccRecTypeSelectOpts();
      ctrl.changeCampaign();
      ctrl.saveRenkei();
      for (SB_NameCardL_TwowayRegistController.CandidateRecord record : ctrl.candidateTable) {

      }
      System.assertEquals(null, ctrl.testError);
    }
  }

  static testMethod void testMethod2() {
    List<User> us = insertUser();
    System.runAs(us[0]) {
      setData(true, true, true, true, true);
      List<SmartViscaf__NameCard__c> cards = [SELECT Id,
                                                     SmartViscaf__company_name__c,
                                                     SmartViscaf__person_name_last__c
                                                FROM SmartViscaf__NameCard__c];
      System.assertEquals(1, cards.size());
      List<Account> acc = [SELECT Id
                             FROM Account];
      System.assertEquals(1, acc.size());
      List<Contact> con = [SELECT Id
                          FROM Contact];
      System.assertEquals(1, con.size());
      List<Lead> lea = [SELECT Id
                          FROM Lead];
      System.assertEquals(1, lea.size());
      PageReference pageRef = Page.SB_NameCardL_TwowayRegist;
      Test.setCurrentPage(pageRef);
      ApexPages.StandardController sc = new ApexPages.StandardController(cards[0]);
      SB_NameCardL_TwowayRegistController ctrl = new SB_NameCardL_TwowayRegistController(sc);
      SB_NameCardL_TwowayRegistController.getRenkeiTypeList();
      SB_NameCardL_TwowayRegistController.getSearchTypeList();
      System.assertEquals(3, ctrl.leadRecordList.size());
      System.assertEquals(5, ctrl.candidateTable.size());
      ctrl.leadRecordListIndex = 0;
      ctrl.accountTableIndex = 0;
      ctrl.candidateTable[2].card4Lookup.SmartViscaf__contact__c = con[0].Id;
      ctrl.getSearchTypeSelectOpts();
      ctrl.getleadRecordTypeOptions();
      ctrl.getContRecTypeSelectOpts();
      ctrl.getAccRecTypeSelectOpts();
      ctrl.changeCampaign();
      ctrl.renkeiType = 'Lead';
      ctrl.saveRenkei();
      for (SB_NameCardL_TwowayRegistController.CandidateRecord record : ctrl.candidateTable) {

      }
      System.assertEquals(null, ctrl.testError);
    }
  }
}