sfdx-source/SmartVisca/main/default/objects/NameCardSettingValues__c/NameCardSettingValues__c.object-meta.xml
<CustomObject>
    <label>名刺設定値</label>
    <nameField>
        <displayFormat>NCSV-{00000}</displayFormat>
        <label>名刺設定値名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/SmartVisca/main/default/objects/NameCardSettingValues__c/fields/TextValue01__c.field-meta.xml
<CustomField>
    <fullName>TextValue01__c</fullName>
    <label>テキスト値01</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardSettingValues__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>種別</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SaishinInherit</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/SmartVisca/main/default/classes/SB_NameCard_SettingValues.cls
/**
 *
 * SB_NameCard_SettingValues
 *  名刺設定値のレコードを参照する用のクラス with sharing で動かす（共有設定に依存する）ためにクラスを分けます。
 *
 * Copyright (C) 2017 SunBridge Inc. All Rights Reserved.
 *
 *  @author sawano
 *  @Version 1      2017.01.xx
 *
 **/
public with sharing class SB_NameCard_SettingValues {

  // 最新の名刺へ 引継ぐ項目 のリスト
  public static List<NameCardSettingValues__c> saishinInheritFields {
    get {
      if (saishinInheritFields == null) {
        Schema.DescribeSObjectResult sobjResult = NameCardSettingValues__c.getSObjectType().getDescribe();
        if (sobjResult.isAccessible()) {
          saishinInheritFields = [Select Id, Name, TextValue01__c From NameCardSettingValues__c Where Type__c = 'SaishinInherit'];
        }
        else {
          saishinInheritFields = new List<NameCardSettingValues__c>();
        }
      }
      return saishinInheritFields;
    }
    private set;
  }
}