sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/NameCardBasicSetting__c.object-meta.xml
<CustomObject>
    <label>名刺基本設定</label>
    <nameField>
        <label>基本設定</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/MappingLastModifiedUser__c.field-meta.xml
<CustomField>
    <fullName>MappingLastModifiedUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>マッピング最終更新者</label>
    <referenceTo>User</referenceTo>
    <relationshipName>MappingLastModifiedUser</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardRenkeiMapping__c/NameCardRenkeiMapping__c.object-meta.xml
<CustomObject>
    <label>名刺連携項目マッピング</label>
    <nameField>
        <displayFormat>RM-{000000}</displayFormat>
        <label>名刺連携項目マッピングNo</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/SmartVisca/main/default/objects/NameCardRenkeiMapping__c/fields/BasicSetting__c.field-meta.xml
<CustomField>
    <fullName>BasicSetting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>名刺基本設定</label>
    <referenceTo>NameCardBasicSetting__c</referenceTo>
    <relationshipLabel>名刺連携項目マッピング</relationshipLabel>
    <relationshipName>BasicSetting</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardRenkeiMapping__c/fields/NameCardName__c.field-meta.xml
<CustomField>
    <fullName>NameCardName__c</fullName>
    <label>名刺の項目(API名称)</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardRenkeiMapping__c/fields/TargetName__c.field-meta.xml
<CustomField>
    <fullName>TargetName__c</fullName>
    <label>対象の項目(API名称)</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/classes/SB_NameCard_RenkeiMappingHandlerTest.cls
/**
 *
 * SB_NameCard_RenkeiMappingHandlerTest    (SB_NameCard_RenkeiMappingHandlerのテストクラス)
 *  連携マッピングを変化があった時基本設定の更新
 *
 *  Copyright (C) 2017 SunBridge Inc. All Rights Reserved.
 *
 *  @author gao
 *  @Version 1.20      2017.02.XX
 *
 **/
@isTest
private class SB_NameCard_RenkeiMappingHandlerTest {

  public static void setsetting() {
    NameCardBasicSetting__c bas = new NameCardBasicSetting__c();
    insert bas;
  }

  //連携マッピングを新規作成時の基本設定の更新
  @isTest static void test_Insert() {
    setsetting();
    List<NameCardBasicSetting__c> bas = [Select Id,Name,MappingLastModifiedUser__c From NameCardBasicSetting__c];
    System.assertEquals(bas.size(),1);
    NameCardRenkeiMapping__c mapping = new NameCardRenkeiMapping__c();
    mapping.TargetName__c = 'Name';
    mapping.NameCardName__c = 'Name';
    insert mapping;
    NameCardRenkeiMapping__c jy = [Select Id,Name,BasicSetting__c From NameCardRenkeiMapping__c Where Id=:mapping.Id];
    List<NameCardBasicSetting__c> bas1 = [Select Id,Name,MappingLastModifiedUser__c From NameCardBasicSetting__c];
    System.assertEquals(jy.BasicSetting__c,bas1[0].Id);
    System.assertEquals(bas1[0].MappingLastModifiedUser__c,UserInfo.getUserId());
  }

  //連携マッピングを更新時の基本設定の更新
  @isTest static void test_Update() {
    setsetting();
    List<NameCardBasicSetting__c> bas = [Select Id,Name,MappingLastModifiedUser__c From NameCardBasicSetting__c];
    System.assertEquals(bas.size(),1);
    NameCardRenkeiMapping__c mapping = new NameCardRenkeiMapping__c();
    mapping.TargetName__c = 'Name';
    mapping.NameCardName__c = 'Name';
    insert mapping;
    NameCardRenkeiMapping__c jy = [Select Id,Name,BasicSetting__c From NameCardRenkeiMapping__c Where Id=:mapping.Id];
    List<NameCardBasicSetting__c> bas1 = [Select Id,Name,MappingLastModifiedUser__c From NameCardBasicSetting__c];
    System.assertEquals(jy.BasicSetting__c,bas1[0].Id);
    System.assertEquals(bas1[0].MappingLastModifiedUser__c,UserInfo.getUserId());
    mapping.NameCardName__c = 'Phone';
    update mapping;
  }
}