sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/NameCardBasicSetting__c.object-meta.xml
<CustomObject>
    <label>名刺基本設定</label>
    <nameField>
        <label>基本設定</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/NayoseJyoken__c.field-meta.xml
<CustomField>
    <fullName>NayoseJyoken__c</fullName>
    <label>名寄せ:条件</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RegistAccountCompareCustomize__c.field-meta.xml
<CustomField>
    <fullName>RegistAccountCompareCustomize__c</fullName>
    <defaultValue>false</defaultValue>
    <label>取引先登録:取引先 会社名と比較する項目をカスタマイズする</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RegistAccountCompareField__c.field-meta.xml
<CustomField>
    <fullName>RegistAccountCompareField__c</fullName>
    <label>取引先登録:取引先 会社名と比較する項目</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RegistAccountNotOverWrite__c.field-meta.xml
<CustomField>
    <fullName>RegistAccountNotOverWrite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>取引先登録:取引先を名刺情報で上書きしない</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RegistAccountQueryRecordTypeIds__c.field-meta.xml
<CustomField>
    <fullName>RegistAccountQueryRecordTypeIds__c</fullName>
    <label>取引先登録:取引先レコードタイプ</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RegistContactNotOverWrite__c.field-meta.xml
<CustomField>
    <fullName>RegistContactNotOverWrite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>取引先登録:取引先責任者を名刺情報で上書きしない</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RegistContactQueryRecordTypeIds__c.field-meta.xml
<CustomField>
    <fullName>RegistContactQueryRecordTypeIds__c</fullName>
    <label>取引先登録:取引先責任者レコードタイプ</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RegistDispAccountOverWriteCheckbox__c.field-meta.xml
<CustomField>
    <fullName>RegistDispAccountOverWriteCheckbox__c</fullName>
    <defaultValue>true</defaultValue>
    <description>オンの場合、「既存の取引先を名刺情報で上書きする」チェックボックスを表示します。</description>
    <label>取引先登録:「既存の取引先を名刺情報で上書きする」を表示する</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RegistDispAccountRectype__c.field-meta.xml
<CustomField>
    <fullName>RegistDispAccountRectype__c</fullName>
    <defaultValue>true</defaultValue>
    <label>取引先登録:取引先レコードタイプ選択を表示する</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RegistDispContactOverWriteCheckbox__c.field-meta.xml
<CustomField>
    <fullName>RegistDispContactOverWriteCheckbox__c</fullName>
    <defaultValue>true</defaultValue>
    <description>オンの場合、「既存の取引先責任者を名刺情報で上書きする」チェックボックスを表示します。</description>
    <label>取引先登録:「既存の取引先責任者を名刺情報で上書きする」を表示する</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RegistDispContactRectype__c.field-meta.xml
<CustomField>
    <fullName>RegistDispContactRectype__c</fullName>
    <defaultValue>true</defaultValue>
    <label>取引先登録:取引先責任者レコードタイプ選択を表示する</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RegistDispLeadOverWriteCheckbox__c.field-meta.xml
<CustomField>
    <fullName>RegistDispLeadOverWriteCheckbox__c</fullName>
    <defaultValue>true</defaultValue>
    <description>オンの場合、「既存のリードを名刺情報で上書きする」チェックボックスを表示します。</description>
    <label>取引先登録:「既存のリードを名刺情報で上書きする」を表示する</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RegistDispLeadRectype__c.field-meta.xml
<CustomField>
    <fullName>RegistDispLeadRectype__c</fullName>
    <defaultValue>true</defaultValue>
    <label>取引先登録:リードレコードタイプ選択を表示する</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RegistDispOverWriteCheckbox__c.field-meta.xml
<CustomField>
    <fullName>RegistDispOverWriteCheckbox__c</fullName>
    <defaultValue>true</defaultValue>
    <description>v.1.21から、オブジェクトごとに項目を設けた。未使用</description>
    <label>取引先登録:「上書きする」チェックボックスを表示する</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RegistLeadCompareCustomize__c.field-meta.xml
<CustomField>
    <fullName>RegistLeadCompareCustomize__c</fullName>
    <defaultValue>false</defaultValue>
    <label>取引先登録:リード 会社名と比較する項目をカスタマイズする</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RegistLeadCompareField__c.field-meta.xml
<CustomField>
    <fullName>RegistLeadCompareField__c</fullName>
    <label>取引先登録:リード 会社名と比較する項目</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RegistLeadNoToDo__c.field-meta.xml
<CustomField>
    <fullName>RegistLeadNoToDo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>取引先登録:リードToDo登録しない</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RegistLeadNotOverWrite__c.field-meta.xml
<CustomField>
    <fullName>RegistLeadNotOverWrite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>取引先登録:リードを名刺情報で上書きしない</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RegistLeadQueryRecordTypeIds__c.field-meta.xml
<CustomField>
    <fullName>RegistLeadQueryRecordTypeIds__c</fullName>
    <label>取引先登録:リードレコードタイプ</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RegistLeadToDoOwner__c.field-meta.xml
<CustomField>
    <fullName>RegistLeadToDoOwner__c</fullName>
    <label>取引先登録:リードToDoの任命先</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>リードの所有者</fullName>
                <default>true</default>
                <label>リードの所有者</label>
            </value>
            <value>
                <fullName>名刺の所有者</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RegistLeadToDoSubject__c.field-meta.xml
<CustomField>
    <fullName>RegistLeadToDoSubject__c</fullName>
    <label>取引先登録:リードToDo件名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RegistNoToDo__c.field-meta.xml
<CustomField>
    <fullName>RegistNoToDo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>取引先登録:ToDo登録しない</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RegistToDoOwner__c.field-meta.xml
<CustomField>
    <fullName>RegistToDoOwner__c</fullName>
    <label>取引先登録:ToDoの任命先</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ContactOwner</fullName>
                <default>true</default>
                <label>取引先責任者の所有者</label>
            </value>
            <value>
                <fullName>NameCardOwner</fullName>
                <label>名刺の所有者</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RegistToDoSubject__c.field-meta.xml
<CustomField>
    <fullName>RegistToDoSubject__c</fullName>
    <defaultValue>&apos;名刺交換&apos;</defaultValue>
    <label>取引先登録:ToDo件名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccount_Street__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccount_Street__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:町名・番地</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountCity__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountCity__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:市区郡</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountCompany__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountCompany__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:取引先名</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountOverwrite__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountOverwrite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>自動連携:既存の取引先を上書きする</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountPhone__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountPhone__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:電話</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountSite__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountSite__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:取引先 部門</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountURL__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountURL__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:Web サイト</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountZipCode__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountZipCode__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:郵便番号</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiActive__c.field-meta.xml
<CustomField>
    <fullName>RenkeiActive__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>名刺データが2次納品された時に取引先・取引先責任者を自動で作成したり更新したりすることができます。「SmartVisca連携設定」タブで連携する条件の設定をします。リード拡張パッケージがインストールされている場合、取引先・取引先責任者に加えてリードを作成・更新できます。</inlineHelpText>
    <label>自動連携:自動連携機能を有効化</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiActiveCampaignMember__c.field-meta.xml
<CustomField>
    <fullName>RenkeiActiveCampaignMember__c</fullName>
    <defaultValue>false</defaultValue>
    <description>自動連携で作成・更新した人をキャンペーンメンバーにする。</description>
    <label>自動連携:スキャン時選択したキャンペーンのメンバーにする</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiCampaignStatus__c.field-meta.xml
<CustomField>
    <fullName>RenkeiCampaignStatus__c</fullName>
    <label>自動連携:キャンペーンの状況</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiContactLastName__c.field-meta.xml
<CustomField>
    <fullName>RenkeiContactLastName__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:姓</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiContactMail__c.field-meta.xml
<CustomField>
    <fullName>RenkeiContactMail__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:メールアドレス</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiContactOverwrite__c.field-meta.xml
<CustomField>
    <fullName>RenkeiContactOverwrite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>自動連携:既存の取引先責任者を上書きする</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiContactRecordTypes__c.field-meta.xml
<CustomField>
    <fullName>RenkeiContactRecordTypes__c</fullName>
    <label>自動連携:取引先責任者レコードタイプ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiExcludeHojinkaku__c.field-meta.xml
<CustomField>
    <fullName>RenkeiExcludeHojinkaku__c</fullName>
    <defaultValue>true</defaultValue>
    <description>自動連携で既存取引先の検索で、会社名は法人格を除いて中間一致検索する</description>
    <label>自動連携:取引先名は法人格を除いて検索</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiExcludeHojinkakuPartial__c.field-meta.xml
<CustomField>
    <fullName>RenkeiExcludeHojinkakuPartial__c</fullName>
    <defaultValue>false</defaultValue>
    <label>自動連携:取引先名は法人格を除いて部分一致検索</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiLeadActive__c.field-meta.xml
<CustomField>
    <fullName>RenkeiLeadActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>自動連携におけるリード登録機能 を有効化する。リード登録機能 はリード拡張パッケージの機能だが、設定は基本パッケージ内に持つ</description>
    <label>自動連携:リード登録機能を有効化</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiLeadNOExistCreateNew__c.field-meta.xml
<CustomField>
    <fullName>RenkeiLeadNOExistCreateNew__c</fullName>
    <defaultValue>false</defaultValue>
    <label>自動連携:既存のリードがなければ新規作成する</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiSpecificItems__c.field-meta.xml
<CustomField>
    <fullName>RenkeiSpecificItems__c</fullName>
    <inlineHelpText>他の条件に加え、取込時にセットしたメモ（手書きメモではありません）の内容と、『指定項目』の文字列が一致した場合に同一の取引先とみなします。</inlineHelpText>
    <label>自動連携:指定項目</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/SaishinInheritValues__c.field-meta.xml
<CustomField>
    <fullName>SaishinInheritValues__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>同じ人の名刺（同一の姓、名、メールアドレス）が複数ある場合、２次納品のとき、名刺交換日をもとに最新の名刺を判定します。最新の名刺に変更があった場合、新しい最新の名刺に、お客様が名刺オブジェクトに追加したカスタム項目の値を引継ぐことが可能です。この機能は、追加したカスタム項目がない場合、選択できません。</inlineHelpText>
    <label>最新の名刺が値を引継ぐ機能:有効化</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/ScanSelectCampaign__c.field-meta.xml
<CustomField>
    <fullName>ScanSelectCampaign__c</fullName>
    <defaultValue>false</defaultValue>
    <label>スキャン:キャンペーン選択を有効化</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/classes/SB_NameCard_NameCardBasicSettingDTO.cls
/**
 *
 * SB_NameCard_NameCardBasicSettingDTO
 * Lightning SB_NameCard_NameCardBasicSettingページにNameCardBasicSetting__cを使うためのbinクラス
 *
 *
 *
 *  Copyright (C) 2017 SunBridge Inc. All Rights Reserved.
 *
 *  @author mao
 *  @Version 1.20      2017.02.XX
 *  @Version 2.4       2019.06.XX SV_DEV-XXXX SmartVisca 基本設定機能追加
 *  @Version 2.5       2019.12.XX SV_DEV-2390 Classic SV設定：リード登録時のToDo登録機能に関する設定項目の追加
 *  @Version 2.6   全  2020.09.xx PRODUCT-835 SmartVisca設定 画面 「リードまたは取引先・取引先責任者に登録」 の 「ToDo登録」の初期値オン の反映先項目が不適切
 *
 **/

public with sharing class SB_NameCard_NameCardBasicSettingDTO {

  /*
  public static final String NC_QUERY_SIMPLE_FIELDS = 'Id,Name,RegistNoToDo__c,RenkeiActive__c,RegistToDoSubject__c,RegistAccountNotOverWrite__c,RegistContactNotOverWrite__c,LastModifiedById,SaishinInheritValues__c,RegistDispLeadRectype__c,RenkeiCampaignStatus__c,' + 
                                                       'RegistDispAccountRectype__c,RegistDispContactRectype__c,RegistDispOverWriteCheckbox__c,ScanSelectCampaign__c,RenkeiLeadActive__c,RegistLeadNotOverWrite__c,RenkeiActiveCampaignMember__c,RegistDispLeadOverWriteCheckbox__c,' + 
                                                       'RegistDispAccountOverWriteCheckbox__c,RegistDispContactOverWriteCheckbox__c';
  */
  public static final String NC_QUERY_SIMPLE_FIELDS = 'Id,Name,RegistNoToDo__c,RenkeiActive__c,RegistToDoSubject__c,RegistAccountNotOverWrite__c,RegistContactNotOverWrite__c,LastModifiedById,SaishinInheritValues__c,RegistDispLeadRectype__c,RenkeiCampaignStatus__c,' + 
                                                       'RegistDispAccountRectype__c,RegistDispContactRectype__c,RegistDispOverWriteCheckbox__c,ScanSelectCampaign__c,RenkeiLeadActive__c,RegistLeadNotOverWrite__c,RenkeiActiveCampaignMember__c,RegistDispLeadOverWriteCheckbox__c,' + 
                                                       'RegistDispAccountOverWriteCheckbox__c,RegistDispContactOverWriteCheckbox__c,' +
                                                       'RegistAccountCompareCustomize__c,RegistAccountCompareField__c,RegistLeadCompareCustomize__c,RegistLeadCompareField__c,' +
                                                       'RegistToDoOwner__c,RegistAccountQueryRecordTypeIds__c,RegistContactQueryRecordTypeIds__c,RegistLeadQueryRecordTypeIds__c,' +
                                                       'NayoseJyoken__c,RegistLeadToDoSubject__c,RegistLeadNoToDo__c,RegistLeadToDoOwner__c';

  public static final String NC_QUERY_FIELDS = 'Id,Name,LastModifiedById,RenkeiContactMail__c,RenkeiAccountCity__c,RenkeiExcludeHojinkaku__c,RenkeiExcludeHojinkakuPartial__c,RenkeiLeadNOExistCreateNew__c,RegistLeadNotOverWrite__c,' + 
                                                                             'RenkeiAccountSite__c,RenkeiAccountURL__c,RenkeiSpecificItems__c,RenkeiContactRecordTypes__c,' +
                                                                             'RenkeiAccountPhone__c,RenkeiAccount_Street__c,RenkeiAccountZipCode__c,RenkeiContactOverwrite__c,' + 
                                                                             'RenkeiAccountCompany__c,RenkeiAccountOverwrite__c,RenkeiContactLastName__c,RenkeiContactFirstName__c,' + 
                                                                             'RenkeiAccountAddressPref__c,RenkeiAccountRecordTypes__c,RenkeiLeadRecordTypes__c,' + 
                                                                             'RenkeiContactNOExistCreateNew__c,RenkeiAccountNOExistCreateNew__c,RenkeiContactQueryRecordTypeIds__c,RenkeiAccountQueryRecordTypeIds__c,RenkeiLeadQueryRecordTypeIds__c,RenkeiInheritEvent__c,' +
                                                                             'HojinkakuEquationLongAndAbbr__c,' +
                                                                             // リード
                                                                             'RenkeiLeadCompany__c,RenkeiLeadPhone__c,RenkeiLeadMail__c,RenkeiLeadURL__c,RenkeiLeadStreet__c,RenkeiLeadExcludeHojinkaku__c,RenkeiLeadExcludeHojinkakuPartial__c,' +
                                                                             'RenkeiLeadCity__c,RenkeiLeadLastName__c,RenkeiLeadAddressPref__c,RenkeiLeadFirstName__c,RenkeiLeadZipCode__c,' +
                                                                             'RenkeiActive__c,RenkeiLeadActive__c,RenkeiActiveCampaignMember__c,RenkeiCampaignStatus__c,RenkeiLeadOverwrite__c,' +
                                                                             // リードの自動連携に関する応用設定
                                                                             'RenkeiCreateContactOnAcountWithLead__c,RenkeiCreateContactOnAcountWithoutLead__c,RenkeiCreateLeadOnTooManyAccounts__c,RenkeiUpdateAllLeadsOnCondition__c';
  private static final Set<String> box = new Set<String>{'RegistAccountNotOverWrite__c','RegistContactNotOverWrite__c','RegistNoToDo__c','RegistLeadNoToDo__c','RegistLeadNotOverWrite__c'};
  //NameCardBasicSetting__c から map
  public static Map<String,String> bind(NameCardBasicSetting__c basicsetting){
    Map<String,String> dto = new Map<String,String>();
    for(String str : NC_QUERY_FIELDS.split(',')){
      dto.put(str,String.valueOf(basicsetting.get(str)));
    }
    dto.put('LastModifiedByName',String.isBlank(basicsetting.LastModifiedBy.Name) ? System.Label.SB_NC_MAPPING_NOUPDATE : basicsetting.LastModifiedBy.Name);
    dto.put('LastModifiedByDate',String.valueOf(Datetime.valueOf(basicsetting.LastModifiedDate)));
    return dto;
  }

  //NameCardBasicSetting__c から map
  public static Map<String,String> bindSimple(NameCardBasicSetting__c basicsetting){
    Map<String,String> dto = new Map<String,String>();
    for(String str : NC_QUERY_SIMPLE_FIELDS.split(',')){
      if(box.contains(str)){
        dto.put(str,String.valueOf(String.valueOf(basicsetting.get(str)) == 'false'));
        continue;
      }
      dto.put(str,String.valueOf(basicsetting.get(str)));
    }
    dto.put('LastModifiedByName',String.isBlank(basicsetting.LastModifiedBy.Name) ? System.Label.SB_NC_MAPPING_NOUPDATE : basicsetting.LastModifiedBy.Name);
    dto.put('LastModifiedByDate',String.valueOf(basicsetting.LastModifiedDate));
    return dto;
  }

  //mapから NameCardBasicSetting__c
  public static NameCardBasicSetting__c DebindSimple(Map<String,String> bs){
    return SB_NameCard_NameCardBasicSettingDTO.DebindSimple(bs, null);
  }

  //mapから NameCardBasicSetting__c
  public static NameCardBasicSetting__c DebindSimple(Map<String,String> bs, NameCardBasicSetting__c bass){
    NameCardBasicSetting__c basicsetting;
    if (bass == null) {
      basicsetting = new NameCardBasicSetting__c();
    } else {
      basicsetting = bass;
    }
    Map<String,String> o1 = new Map<String,String>();
    Map<String,String> o2 = new Map<String,String>();
    SB_NameCard_RenkeiMapperUtil.createApiNameKeyDataTypeMap(SB_NameCard_RenkeiMapperUtil.getManagedObjectName('NameCardBasicSetting__c'),o1,o2,'',false);
    System.debug(o1);
    for(String str : NC_QUERY_SIMPLE_FIELDS.split(',')){
      if(str == 'LastModifiedByName' || str == 'LastModifiedByDate' || str == 'LastModifiedById'){
        continue;
      }
      if(o1.get(SB_NameCard_RenkeiMapperUtil.getManagedfileName('NameCardBasicSetting__c',str)) == 'BOOLEAN'){
        if(box.contains(str)){
          basicsetting.put(str,String.valueOf(bs.get(str)) == 'false');
          continue;
        }
        basicsetting.put(str,String.valueOf(bs.get(str)) == 'true');
        continue;
      }
      System.debug(str + '   ' + bs.get(str));
      basicsetting.put(str,String.valueOf(bs.get(str)));
    }
    System.debug(basicsetting);
    return basicsetting;
  }

  //mapから NameCardBasicSetting__c
  public static NameCardBasicSetting__c Debind(Map<String,String> bs){
    return SB_NameCard_NameCardBasicSettingDTO.Debind(bs, null);
  }

  //mapから NameCardBasicSetting__c
  public static NameCardBasicSetting__c Debind(Map<String,String> bs, NameCardBasicSetting__c bass){
    NameCardBasicSetting__c basicsetting;
    if (bass == null) {
      basicsetting = new NameCardBasicSetting__c();
    } else {
      basicsetting = bass;
    }
    Map<String,String> o1 = new Map<String,String>();
    Map<String,String> o2 = new Map<String,String>();
    SB_NameCard_RenkeiMapperUtil.createApiNameKeyDataTypeMap(SB_NameCard_RenkeiMapperUtil.getManagedObjectName('NameCardBasicSetting__c'),o1,o2,'',false);
    System.debug(o1);
    for(String str : NC_QUERY_FIELDS.split(',')){
      if(str == 'LastModifiedByName' || str == 'LastModifiedByDate' || str == 'LastModifiedById'){
        continue;
      }
      if(o1.get(SB_NameCard_RenkeiMapperUtil.getManagedfileName('NameCardBasicSetting__c',str)) == 'BOOLEAN'){
        System.debug(bs);
        System.debug(o1.get(str) + '  ' + str + '   ');
        basicsetting.put(str,String.valueOf(bs.get(str)) == 'true');
      } else{
        basicsetting.put(str,String.valueOf(bs.get(str)));
      }
    }
    System.debug(basicsetting);
    return basicsetting;
  }

}