sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/NameCardBasicSetting__c.object-meta.xml
<CustomObject>
    <label>名刺基本設定</label>
    <nameField>
        <label>基本設定</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountAddressPref__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountAddressPref__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:都道府県</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountCity__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountCity__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:市区郡</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountCompany__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountCompany__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:取引先名</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountNOExistCreateNew__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountNOExistCreateNew__c</fullName>
    <defaultValue>true</defaultValue>
    <description>自動連携での取引先のクエリの結果既存の取引先がなければ新規作成する</description>
    <label>自動連携:既存の取引先がなければ新規作成する</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountOverwrite__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountOverwrite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>自動連携:既存の取引先を上書きする</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountSite__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountSite__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:取引先 部門</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiAccountZipCode__c.field-meta.xml
<CustomField>
    <fullName>RenkeiAccountZipCode__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:郵便番号</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiContactFirstName__c.field-meta.xml
<CustomField>
    <fullName>RenkeiContactFirstName__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:名</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiContactLastName__c.field-meta.xml
<CustomField>
    <fullName>RenkeiContactLastName__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:姓</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiContactMail__c.field-meta.xml
<CustomField>
    <fullName>RenkeiContactMail__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動連携:メールアドレス</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/RenkeiSpecificItems__c.field-meta.xml
<CustomField>
    <fullName>RenkeiSpecificItems__c</fullName>
    <inlineHelpText>他の条件に加え、取込時にセットしたメモ（手書きメモではありません）の内容と、『指定項目』の文字列が一致した場合に同一の取引先とみなします。</inlineHelpText>
    <label>自動連携:指定項目</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardRenkeiJyoken__c/NameCardRenkeiJyoken__c.object-meta.xml
<CustomObject>
    <label>名刺自動連携条件設定</label>
    <nameField>
        <displayFormat>RC-{000000}</displayFormat>
        <label>連携設定</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/SmartVisca/main/default/objects/NameCardRenkeiJyoken__c/fields/NameCardDataType__c.field-meta.xml
<CustomField>
    <fullName>NameCardDataType__c</fullName>
    <label>名刺の項目(データ型)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>String</fullName>
            </value>
            <value>
                <fullName>Boolean</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Double</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Url</fullName>
            </value>
            <value>
                <fullName>Textarea</fullName>
            </value>
            <value>
                <fullName>Datetime</fullName>
            </value>
            <value>
                <fullName>Integer</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
                <isActive>false</isActive>
                <label>Number</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardRenkeiJyoken__c/fields/NameCardName__c.field-meta.xml
<CustomField>
    <fullName>NameCardName__c</fullName>
    <label>名刺の項目(API名称)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardRenkeiJyoken__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <label>演算子</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Matches_next_character_string</fullName>
            </value>
            <value>
                <fullName>Does_not_match_next_character_string</fullName>
            </value>
            <value>
                <fullName>Start_with_the_following_string</fullName>
            </value>
            <value>
                <fullName>Contains_the_following_character_string</fullName>
            </value>
            <value>
                <fullName>Not_contain_the_following_character_string</fullName>
            </value>
            <value>
                <fullName>Matches_the_following_regular_expression</fullName>
            </value>
            <value>
                <fullName>＜</fullName>
            </value>
            <value>
                <fullName>＞</fullName>
            </value>
            <value>
                <fullName>＜＝</fullName>
            </value>
            <value>
                <fullName>＞＝</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardRenkeiJyoken__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>値</label>
    <type>TextArea</type>
</CustomField>

sfdx-source/SmartVisca/main/default/classes/SB_NameCard_RenkeiSettingLcTest.cls
/**
 *
 * SB_NameCard_RenkeiSettingLcTest    (SB_NameCard_RenkeiSettingLcController)
 *
 *
 *  Copyright (C) 2017 SunBridge Inc. All Rights Reserved.
 *
 *  @author mao
 *  @Version 1.20      2017.02.20
 *  @Version 1.21 kou 2017.10.xx No Assert v1.21 for code scan
 *  @Version 2.1       2018.04.XX  SV_DEV-876   連携設定条件に名刺項目に参照項目が選択できないことを変更
 *  @Version 2.1       2018.04.XX  SV_DEV-885 基本設定、連携条件設定、連携マッピングタブ切り替えの見直し
 *  @Version 2.1       2018.04.XX  SV_DEV-1106 SmartVisca基本設定レコードの一部項目の値が反転して表示される。
 **/


@isTest
private class SB_NameCard_RenkeiSettingLcTest {

  public  static NameCardBasicSetting__c setDate(){
    NameCardBasicSetting__c setting = new NameCardBasicSetting__c();
    setting.Name = 'BasicSetting';
    setting.RenkeiContactFirstName__c = true;
    setting.RenkeiContactLastName__c = true;
    setting.RenkeiAccountCompany__c = true;
    setting.RenkeiContactMail__c = true;
    setting.RenkeiAccountSite__c = true;
    setting.RenkeiAccountZipCode__c = true;
    setting.RenkeiSpecificItems__c = 'Name';
    setting.RenkeiAccountAddressPref__c = true;
    setting.RenkeiAccountCity__c = true;
    setting.RenkeiAccountOverwrite__c = true;
    setting.RenkeiAccountNOExistCreateNew__c = true;
    insert setting;

    NameCardRenkeiJyoken__c jyouken = new NameCardRenkeiJyoken__c();
    jyouken.NameCardName__c = 'Name';
    jyouken.Operator__c = 'Matches_next_character_string';
    jyouken.Value__c = 'test';
    insert jyouken;

    return SB_NameCard_BasicSetting.getNameCardBasicSetting();
  }

  // データ取得テスト
  @isTest static void test_GetAllData() {
    NameCardBasicSetting__c bas = setdate();
    NameCardRenkeiJyoken__c jyouken1 = new NameCardRenkeiJyoken__c();
    jyouken1.NameCardName__c = 'Name';
    jyouken1.Operator__c = 'Matches_next_character_string';
    jyouken1.Value__c = '';
    insert jyouken1;
    SB_NameCard_RenkeiSettingLcController.getallmap();
    String jyous1 = SB_NameCard_RenkeiSettingLcController.getalldata();
    List<SB_NameCard_NameCardRenkeiJyokenDTO> jyous = new List<SB_NameCard_NameCardRenkeiJyokenDTO>();
    jyous = (List<SB_NameCard_NameCardRenkeiJyokenDTO>)System.JSON.deserializeStrict(jyous1,List<SB_NameCard_NameCardRenkeiJyokenDTO> .Class);
    System.assertEquals(jyous.size(),2);
  }

  // 連携条件更新テスト
  @isTest static void test_Updae() {
    NameCardBasicSetting__c bas = setdate();
    List<NameCardRenkeiJyoken__c> ses = [Select Id,Name,NameCardName__c,Operator__c,Value__c From  NameCardRenkeiJyoken__c];
    ses[0].NameCardName__c = 'Name';
    ses[0].Operator__c = 'Does_not_match_next_character_string';
    ses[0].Value__c = 'tttt';
    List<SB_NameCard_NameCardRenkeiJyokenDTO> ds = new List<SB_NameCard_NameCardRenkeiJyokenDTO>();
    for(NameCardRenkeiJyoken__c jyo : ses){
      SB_NameCard_NameCardRenkeiJyokenDTO d = new SB_NameCard_NameCardRenkeiJyokenDTO();
      d.bind(jyo);
      ds.add(d);
    }
    SB_NameCard_RenkeiSettingLcController.savesetting(JSON.serialize(ds),SB_NameCard_NameCardBasicSettingDTO.bind(bas), false);
    ses = [Select Id,Name,NameCardName__c,Operator__c,Value__c From  NameCardRenkeiJyoken__c ORDER BY CreatedDate DESC];
    System.debug(ses);
    System.assertEquals(ses[0].Value__c,'tttt');
    System.assertEquals(ses[0].Operator__c,'Does_not_match_next_character_string');
    System.assertEquals(ses[0].NameCardName__c,'Name');
  }

  // 連携条件新規テスト
  @isTest static void test_crete() {
    List<NameCardRenkeiJyoken__c> ses = [Select Id,Name,NameCardName__c,Operator__c,Value__c From  NameCardRenkeiJyoken__c];
    System.assertEquals(ses.size(),0);
    SB_NameCard_RenkeiSettingLcController.getallmap();
    NameCardBasicSetting__c aa = new NameCardBasicSetting__c ();
    aa.RenkeiContactMail__c = true;
    List<SB_NameCard_NameCardRenkeiJyokenDTO> ds = new List<SB_NameCard_NameCardRenkeiJyokenDTO>();
    for(NameCardRenkeiJyoken__c jyo : ses){
      SB_NameCard_NameCardRenkeiJyokenDTO d = new SB_NameCard_NameCardRenkeiJyokenDTO();
      d.bind(jyo);
      ds.add(d);
    }
    SB_NameCard_RenkeiSettingLcController.savesetting(JSON.serialize(ds),SB_NameCard_NameCardBasicSettingDTO.bind(aa), false);
    List<NameCardBasicSetting__c> sett = [Select Id,Name From NameCardBasicSetting__c ORDER BY LastModifiedDate DESC];
    System.assertEquals(sett.size(),1);
  }

  // 基本設定がなく，保存すると新規作成テスト
  @isTest static void test_BaseSetInsert() {
    NameCardBasicSetting__c setting = new NameCardBasicSetting__c();
    setting.Name = 'Test';
    setting.RenkeiContactMail__c = true;
    String backmessage1 = SB_NameCard_RenkeiSettingLcController.savesetting(JSON.serialize(new List<SB_NameCard_NameCardRenkeiJyokenDTO>()),SB_NameCard_NameCardBasicSettingDTO.bind(setting), false);
    SB_NameCard_RenkeiSettingLcController.SaveRenkeiData backmessage = new SB_NameCard_RenkeiSettingLcController.SaveRenkeiData();
    backmessage = (SB_NameCard_RenkeiSettingLcController.SaveRenkeiData)System.JSON.deserializeStrict(backmessage1,SB_NameCard_RenkeiSettingLcController.SaveRenkeiData .Class);
    List<NameCardBasicSetting__c> ssting = [Select Id,Name From  NameCardBasicSetting__c];
    System.assertEquals(ssting.size() , 1);
    System.assertEquals(backmessage.state , 'ok');
  }

  // 基本設定保存すると更新作成テスト
  @isTest static void test_BaseSetUpdate() {

    NameCardBasicSetting__c setting = new NameCardBasicSetting__c();
    setting.Name = 'Test';
    setting.RenkeiContactMail__c = true;
    insert setting;
    setting = SB_NameCard_BasicSetting.getNameCardBasicSetting();
    String backmessage1 = SB_NameCard_RenkeiSettingLcController.savesetting(JSON.serialize(new List<SB_NameCard_NameCardRenkeiJyokenDTO>()),SB_NameCard_NameCardBasicSettingDTO.bind(setting), false);
    SB_NameCard_RenkeiSettingLcController.SaveRenkeiData backmessage = new SB_NameCard_RenkeiSettingLcController.SaveRenkeiData();
    backmessage = (SB_NameCard_RenkeiSettingLcController.SaveRenkeiData)System.JSON.deserializeStrict(backmessage1,SB_NameCard_RenkeiSettingLcController.SaveRenkeiData .Class);
    System.assertEquals(backmessage.state , 'ok');
  }

  // 連携条件新規保存エラー
  @isTest static void test_JyouKenErrorInsert() {
    List<NameCardRenkeiJyoken__c>jyous = new List<NameCardRenkeiJyoken__c>();
    jyous.add(new NameCardRenkeiJyoken__c());
    jyous.add(new NameCardRenkeiJyoken__c());
    List<SB_NameCard_NameCardRenkeiJyokenDTO> ds = new List<SB_NameCard_NameCardRenkeiJyokenDTO>();
    for(NameCardRenkeiJyoken__c jyo : jyous){
      SB_NameCard_NameCardRenkeiJyokenDTO d = new SB_NameCard_NameCardRenkeiJyokenDTO();
      d.bind(jyo);
      ds.add(d);
    }
    NameCardBasicSetting__c setting = new NameCardBasicSetting__c();
    setting.Name = 'Test';
    setting.RenkeiContactMail__c = true;
    String backmessage = SB_NameCard_RenkeiSettingLcController.savesetting(JSON.serialize(ds),SB_NameCard_NameCardBasicSettingDTO.bind(setting), false);
    SB_NameCard_RenkeiSettingLcController.SaveRenkeiData backmessage1 = new SB_NameCard_RenkeiSettingLcController.SaveRenkeiData();
    backmessage1 = (SB_NameCard_RenkeiSettingLcController.SaveRenkeiData)System.JSON.deserializeStrict(backmessage, SB_NameCard_RenkeiSettingLcController.SaveRenkeiData .Class);
    System.assertEquals(backmessage1.messages[0] , String.format(System.Label.SB_NC_SETTING_NoNCField_ErrorMessage,
                    new String[]{jyous[0].NameCardName__c}));
    System.assertEquals(backmessage1.state , 'ngs');
  }

  // 連携条件更新保存エラー
  @isTest static void test_JyouKenErrorUpdate() {
    setdate();
    setdate();
    List<NameCardRenkeiJyoken__c> ses = [Select Id,Name,NameCardName__c,Operator__c,Value__c,NameCardDataType__c,LastModifiedBy.Name,LastModifiedById,LastModifiedDate From  NameCardRenkeiJyoken__c];
    System.assertEquals(ses.size(),2);
    List<SB_NameCard_NameCardRenkeiJyokenDTO> ds = new List<SB_NameCard_NameCardRenkeiJyokenDTO>();
    for(NameCardRenkeiJyoken__c jyo : ses){
      SB_NameCard_NameCardRenkeiJyokenDTO d = new SB_NameCard_NameCardRenkeiJyokenDTO();
      d.bind(jyo);
      ds.add(d);
    }
    String backmessage1 = SB_NameCard_RenkeiSettingLcController.savesetting(JSON.serialize(ds),SB_NameCard_NameCardBasicSettingDTO.bind(SB_NameCard_BasicSetting.getNameCardBasicSetting()), false);
    SB_NameCard_RenkeiSettingLcController.SaveRenkeiData backmessage = new SB_NameCard_RenkeiSettingLcController.SaveRenkeiData();
    backmessage = (SB_NameCard_RenkeiSettingLcController.SaveRenkeiData)System.JSON.deserializeStrict(backmessage1,SB_NameCard_RenkeiSettingLcController.SaveRenkeiData .Class);
    System.assertEquals(backmessage.state , 'ok');
  }

  // 連携条件削除保存
  @isTest static void test_JyouKenDelete() {
    setdate();
    setdate();
    List<NameCardRenkeiJyoken__c> ses = [Select Id,Name,NameCardName__c,Operator__c,Value__c From  NameCardRenkeiJyoken__c];
    System.assertEquals(ses.size(),2);
    String backmessage1 = SB_NameCard_RenkeiSettingLcController.savesetting(JSON.serialize(new List<SB_NameCard_NameCardRenkeiJyokenDTO>()),SB_NameCard_NameCardBasicSettingDTO.bind(SB_NameCard_BasicSetting.getNameCardBasicSetting()), false);
    SB_NameCard_RenkeiSettingLcController.SaveRenkeiData backmessage = new SB_NameCard_RenkeiSettingLcController.SaveRenkeiData();
    backmessage = (SB_NameCard_RenkeiSettingLcController.SaveRenkeiData)System.JSON.deserializeStrict(backmessage1,SB_NameCard_RenkeiSettingLcController.SaveRenkeiData .Class);
    System.debug('aaaaaaaaaa' + backmessage.state);
    System.assertEquals(backmessage.state , 'ok');
  }

  // 基本設定レコードない場合のエラーメッセージ
  @isTest static void test_NoBasicSettingError() {
    List<NameCardRenkeiJyoken__c> ses = [Select Id,Name,NameCardName__c,Operator__c,Value__c From  NameCardRenkeiJyoken__c];
    System.assertEquals(ses.size(),0);
    String str = SB_NameCard_RenkeiSettingLcController.getallmap();

    SB_NameCard_RenkeiSettingLcController.RenkeiPageAllDate renkeiSetting = new SB_NameCard_RenkeiSettingLcController.RenkeiPageAllDate();
    renkeiSetting = (SB_NameCard_RenkeiSettingLcController.RenkeiPageAllDate)System.JSON.deserializeStrict(str, SB_NameCard_RenkeiSettingLcController.RenkeiPageAllDate .Class);
    System.assertEquals(renkeiSetting.warMsg.size(), 1);
    System.assertEquals(renkeiSetting.warMsg[0], System.Label.SB_NC_SETTING_ERROR_No_NameCardBasicSetting);
  }

  // 基本設定他ユーザ変更のエラーメッセージ
  @isTest static void test_OtherUserSaved() {
    NameCardBasicSetting__c bas = setdate();

    List<NameCardRenkeiJyoken__c> ses = [Select Id,Name,NameCardName__c,Operator__c,Value__c From  NameCardRenkeiJyoken__c];
    ses[0].NameCardName__c = 'test';
    ses[0].Operator__c = 'Does_not_match_next_character_string';
    ses[0].Value__c = 'tttt';
    List<SB_NameCard_NameCardRenkeiJyokenDTO> ds = new List<SB_NameCard_NameCardRenkeiJyokenDTO>();
    for(NameCardRenkeiJyoken__c jyo : ses){
      SB_NameCard_NameCardRenkeiJyokenDTO d = new SB_NameCard_NameCardRenkeiJyokenDTO();
      d.bind(jyo);
      ds.add(d);
    }

    Map<String,String> jyoukenMap = SB_NameCard_NameCardBasicSettingDTO.bind(bas);
    jyoukenMap.put('LastModifiedByDate', String.valueOf(Datetime.valueOf(Datetime.now().addDays(-1))));
    String saveDate = SB_NameCard_RenkeiSettingLcController.savesetting(JSON.serialize(ds), jyoukenMap, false);

    SB_NameCard_RenkeiSettingLcController.SaveRenkeiData renkeiSetting = new SB_NameCard_RenkeiSettingLcController.SaveRenkeiData();
    renkeiSetting = (SB_NameCard_RenkeiSettingLcController.SaveRenkeiData)System.JSON.deserializeStrict(saveDate, SB_NameCard_RenkeiSettingLcController.SaveRenkeiData .Class);
    System.assertEquals(renkeiSetting.state, 'warning');
    System.assertEquals(renkeiSetting.message, System.Label.SB_NC_SETTING_ERROR_OtherSection_Saved);
  }

  // 指定項目が存在しない項目場合Warningメッセージテスト
  // Triggerにはチェックがあるためデーターが作成できません
  // @isTest static void test_WrongSpecificItems() {
  //   NameCardBasicSetting__c setting = new NameCardBasicSetting__c();
  //   setting.Name = 'testba';
  //   setting.RenkeiContactFirstName__c = true;
  //   setting.RenkeiContactLastName__c = true;
  //   setting.RenkeiAccountCompany__c = true;
  //   setting.RenkeiContactMail__c = true;
  //   setting.RenkeiAccountSite__c = true;
  //   setting.RenkeiAccountZipCode__c = true;
  //   // setting.RenkeiSpecificItems__c = 'TestXX__x';
  //   setting.RenkeiAccountAddressPref__c = true;
  //   setting.RenkeiAccountCity__c = true;
  //   setting.RenkeiAccountOverwrite__c = true;
  //   setting.RenkeiAccountNOExistCreateNew__c = true;
  //   insert setting;

  //   String str = SB_NameCard_RenkeiSettingLcController.getallmap();

  //   SB_NameCard_RenkeiSettingLcController.RenkeiPageAllDate renkeiSetting = new SB_NameCard_RenkeiSettingLcController.RenkeiPageAllDate();
  //   renkeiSetting = (SB_NameCard_RenkeiSettingLcController.RenkeiPageAllDate)System.JSON.deserializeStrict(str, SB_NameCard_RenkeiSettingLcController.RenkeiPageAllDate .Class);
  //   System.assertEquals(renkeiSetting.warMsg.size(), 1);
  //   System.assertEquals(renkeiSetting.warMsg[0], String.format(System.Label.SB_NC_SETTING_ERROR_Wrong_RenkeiSpecificItems, new String[]{setting.RenkeiSpecificItems__c}));
  // }


  // 指定項目が存在する項目場合Warningメッセージテスト
  @isTest static void test_RightSpecificItems() {
    NameCardBasicSetting__c setting = new NameCardBasicSetting__c();
    setting.Name = 'testba';
    setting.RenkeiContactFirstName__c = true;
    setting.RenkeiContactLastName__c = true;
    setting.RenkeiAccountCompany__c = true;
    setting.RenkeiContactMail__c = true;
    setting.RenkeiAccountSite__c = true;
    setting.RenkeiAccountZipCode__c = true;
    setting.RenkeiSpecificItems__c = 'Name';
    setting.RenkeiAccountAddressPref__c = true;
    setting.RenkeiAccountCity__c = true;
    setting.RenkeiAccountOverwrite__c = true;
    setting.RenkeiAccountNOExistCreateNew__c = true;
    insert setting;

    String str = SB_NameCard_RenkeiSettingLcController.getallmap();

    SB_NameCard_RenkeiSettingLcController.RenkeiPageAllDate renkeiSetting = new SB_NameCard_RenkeiSettingLcController.RenkeiPageAllDate();
    renkeiSetting = (SB_NameCard_RenkeiSettingLcController.RenkeiPageAllDate)System.JSON.deserializeStrict(str, SB_NameCard_RenkeiSettingLcController.RenkeiPageAllDate .Class);
    System.assertEquals(renkeiSetting.warMsg.size(), 0);
  }


}