sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/NameCardBasicSetting__c.object-meta.xml
<CustomObject>
    <label>名刺基本設定</label>
    <nameField>
        <label>基本設定</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/fields/MConditionLastModifiedUser__c.field-meta.xml
<CustomField>
    <fullName>MConditionLastModifiedUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>連携設定最終更新者</label>
    <referenceTo>User</referenceTo>
    <relationshipName>MConditionLastModifiedUser</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardRenkeiJyoken__c/NameCardRenkeiJyoken__c.object-meta.xml
<CustomObject>
    <label>名刺自動連携条件設定</label>
    <nameField>
        <displayFormat>RC-{000000}</displayFormat>
        <label>連携設定</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/SmartVisca/main/default/objects/NameCardRenkeiJyoken__c/fields/BasicSetting__c.field-meta.xml
<CustomField>
    <fullName>BasicSetting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>名刺基本設定</label>
    <referenceTo>NameCardBasicSetting__c</referenceTo>
    <relationshipLabel>名刺自動連携条件設定</relationshipLabel>
    <relationshipName>BasicSetting1</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardRenkeiJyoken__c/fields/NameCardDataType__c.field-meta.xml
<CustomField>
    <fullName>NameCardDataType__c</fullName>
    <label>名刺の項目(データ型)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>String</fullName>
            </value>
            <value>
                <fullName>Boolean</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Double</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Url</fullName>
            </value>
            <value>
                <fullName>Textarea</fullName>
            </value>
            <value>
                <fullName>Datetime</fullName>
            </value>
            <value>
                <fullName>Integer</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
                <isActive>false</isActive>
                <label>Number</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardRenkeiJyoken__c/fields/NameCardName__c.field-meta.xml
<CustomField>
    <fullName>NameCardName__c</fullName>
    <label>名刺の項目(API名称)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardRenkeiJyoken__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <label>演算子</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Matches_next_character_string</fullName>
            </value>
            <value>
                <fullName>Does_not_match_next_character_string</fullName>
            </value>
            <value>
                <fullName>Start_with_the_following_string</fullName>
            </value>
            <value>
                <fullName>Contains_the_following_character_string</fullName>
            </value>
            <value>
                <fullName>Not_contain_the_following_character_string</fullName>
            </value>
            <value>
                <fullName>Matches_the_following_regular_expression</fullName>
            </value>
            <value>
                <fullName>＜</fullName>
            </value>
            <value>
                <fullName>＞</fullName>
            </value>
            <value>
                <fullName>＜＝</fullName>
            </value>
            <value>
                <fullName>＞＝</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardRenkeiJyoken__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>値</label>
    <type>TextArea</type>
</CustomField>

sfdx-source/SmartVisca/main/default/classes/SB_NameCard_RenkeiSettingHandlerTest.cls
/**
 * SB_NameCard_RenkeiSettingHandlerTest
 * SB_NameCard_RenkeiSettingTriggerのテストクラス
 *
 *
 * Copyright (C) 2012-2017 SunBridge Inc. All Rights Reserved.
 *
 *  @author gao
 *  History :
 *  @Version 1.20      2017.3.XX
 *
 **/

@isTest
private class SB_NameCard_RenkeiSettingHandlerTest {

  public static void setsetting() {
    NameCardBasicSetting__c bas = new NameCardBasicSetting__c();
    insert bas;
  }

  //連携条件を差込
  @isTest static void test_Insert() {
    setsetting();
    List<NameCardBasicSetting__c> bas = [Select Id,Name,MConditionLastModifiedUser__c From NameCardBasicSetting__c];
    System.assertEquals(bas.size(),1);
    NameCardRenkeiJyoken__c jyo = new NameCardRenkeiJyoken__c();
    jyo.Operator__c = 'Start_with_the_following_string';
    jyo.Value__c = 'test';
    jyo.NameCardName__c = 'Name';
    jyo.NameCardDataType__c = 'String';
    insert jyo;
    NameCardRenkeiJyoken__c jy = [Select Id,Name,BasicSetting__c From NameCardRenkeiJyoken__c Where Id=:jyo.Id];
    List<NameCardBasicSetting__c> bas1 = [Select Id,Name,MConditionLastModifiedUser__c From NameCardBasicSetting__c];
    System.assertEquals(jy.BasicSetting__c,bas1[0].Id);
    System.assertEquals(bas1[0].MConditionLastModifiedUser__c,UserInfo.getUserId());
  }

  //連携条件を更新
  @isTest static void test_Update() {
    setsetting();
    List<NameCardBasicSetting__c> bas = [Select Id,Name,MConditionLastModifiedUser__c From NameCardBasicSetting__c];
    System.assertEquals(bas.size(),1);
    NameCardRenkeiJyoken__c jyo = new NameCardRenkeiJyoken__c();
    jyo.Operator__c = 'Start_with_the_following_string';
    jyo.Value__c = 'test';
    jyo.NameCardName__c = 'Name';
    jyo.NameCardDataType__c = 'String';
    insert jyo;
    NameCardRenkeiJyoken__c jy = [Select Id,Name,BasicSetting__c From NameCardRenkeiJyoken__c Where Id=:jyo.Id];
    List<NameCardBasicSetting__c> bas1 = [Select Id,Name,MConditionLastModifiedUser__c From NameCardBasicSetting__c];
    System.assertEquals(jy.BasicSetting__c,bas1[0].Id);
    System.assertEquals(bas1[0].MConditionLastModifiedUser__c,UserInfo.getUserId());

    jyo.Value__c = 'test2';
    update jyo;
  }

}