sfdx-source/SmartVisca/main/default/objects/NameCardUserSetting__c/NameCardUserSetting__c.object-meta.xml
<CustomObject>
    <label>名刺ユーザ設定</label>
    <nameField>
        <displayFormat>NUS-{00000}</displayFormat>
        <label>名刺ユーザ設定No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/SmartVisca/main/default/objects/NameCardUserSetting__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ユーザ</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SmartViscaUserSetting</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/SmartViscaConfig__c/SmartViscaConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>SmartViscaの表示設定や、Triggerの設定を持ちます。</description>
    <label>SmartVisca設定</label>
</CustomObject>

sfdx-source/SmartVisca/main/default/objects/SmartViscaConfig__c/fields/SExtraNamespace__c.field-meta.xml
<CustomField>
    <fullName>SExtraNamespace__c</fullName>
    <description>特別に名前空間名の指定が必要場合に使う</description>
    <inlineHelpText>サンブリッジサポートの指示があった場合のみ設定します。</inlineHelpText>
    <label>S別名前空間名</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/SmartViscaConfig__c/fields/SSmartViscaServerOptions__c.field-meta.xml
<CustomField>
    <fullName>SSmartViscaServerOptions__c</fullName>
    <description>必要に応じてSmartViscaサーバへ送る追加のパラメータを指定します。
セッションCookieが使えない環境では、 proxy_flag:1</description>
    <inlineHelpText>必要に応じてSmartViscaサーバへ送る追加のパラメータを指定します。</inlineHelpText>
    <label>SSmartViscaサーバ オプション</label>
    <type>TextArea</type>
</CustomField>

sfdx-source/SmartVisca/main/default/classes/SB_NameCard_SvcConfigTest.cls
/**
 *
 * SB_NameCard_SvcConfigTest
 * SB_NameCard_SvcConfig  のテストクラス 
 *
 * Copyright (C) 2019 SunBridge Inc. All Rights Reserved.
 *
 *  @author sawano
 *  @Version 1      2019.05.xx
 *
 **/
@isTest
private class SB_NameCard_SvcConfigTest {

  @isTest
  static void test_constructor() {
    SmartViscaConfig__c config = new SmartViscaConfig__c();
    config.SSmartViscaServerOptions__c = 'AAA:111\r\nBBB:222';
    insert config;
    NameCardUserSetting__c setting = new NameCardUserSetting__c();
    setting.User__c = UserInfo.getUserId();
    setting.SvcLastListName__c = '前回のリスト名';
    insert setting;
    SB_NameCard_SvcConfig svcConfig = SB_NameCard_SvcConfig.getInstance();
    System.assert(!svcConfig.getValues().isEmpty());
    Map<String, String> opts = (Map<String, String>)svcConfig.getValues().get('sSmartViscaServerOptions');
    System.assertEquals('111', opts.get('AAA'));
    System.assertEquals(setting.SvcLastListName__c, svcConfig.getValues().get('svcLastListName'));
  }

  @isTest
  static void test_getValeus_sExtraNamespace() {
    SmartViscaConfig__c config = new SmartViscaConfig__c();
    config.SSmartViscaServerOptions__c = 'AAA:111\r\nBBB:222';
    config.SExtraNamespace__c = 'カスタム設定で名前空間名を指定';
    insert config;
    NameCardUserSetting__c setting = new NameCardUserSetting__c();
    setting.User__c = UserInfo.getUserId();
    setting.SvcLastListName__c = '前回のリスト名';
    insert setting;
    System.assertEquals(config.SExtraNamespace__c, SB_NameCard_SImageController.namespace);
  }

  // SV_DEV-1938 SmartViscaカメラから固定で proxy_flag及びservice_id を名刺サーバに送る
  @isTest
  static void test_FixedSeverOptions() {
    SmartViscaConfig__c config = new SmartViscaConfig__c();
    insert config;
    SB_NameCard_SvcConfig svcConfig = SB_NameCard_SvcConfig.getInstance();
    System.assert(!svcConfig.getValues().isEmpty());
    Map<String, String> opts = (Map<String, String>)svcConfig.getValues().get('sSmartViscaServerOptions');
    System.assertEquals('1', opts.get('proxy_flag'));
    System.assertEquals('SFDCAPEX', opts.get('service_id'));
  }


}