sfdx-source/SmartVisca/main/default/objects/DefaultRenkeiMapping__mdt/DefaultRenkeiMapping__mdt.object-meta.xml
<CustomObject>
    <label>デフォルト名刺連携項目マッピング</label>
</CustomObject>

sfdx-source/SmartVisca/main/default/objects/DefaultRenkeiMapping__mdt/fields/NameCardName__c.field-meta.xml
<CustomField>
    <fullName>NameCardName__c</fullName>
    <label>名刺の項目(API名称)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/DefaultRenkeiMapping__mdt/fields/recordtype__c.field-meta.xml
<CustomField>
    <fullName>recordtype__c</fullName>
    <label>レコードタイプ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/DefaultRenkeiMapping__mdt/fields/TargetName__c.field-meta.xml
<CustomField>
    <fullName>TargetName__c</fullName>
    <label>対象の項目(API名称)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardBasicSetting__c/NameCardBasicSetting__c.object-meta.xml
<CustomObject>
    <label>名刺基本設定</label>
    <nameField>
        <label>基本設定</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/SmartVisca/main/default/objects/NameCardRenkeiJyoken__c/NameCardRenkeiJyoken__c.object-meta.xml
<CustomObject>
    <label>名刺自動連携条件設定</label>
    <nameField>
        <displayFormat>RC-{000000}</displayFormat>
        <label>連携設定</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/SmartVisca/main/default/objects/NameCardRenkeiJyoken__c/fields/BasicSetting__c.field-meta.xml
<CustomField>
    <fullName>BasicSetting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>名刺基本設定</label>
    <referenceTo>NameCardBasicSetting__c</referenceTo>
    <relationshipLabel>名刺自動連携条件設定</relationshipLabel>
    <relationshipName>BasicSetting1</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardRenkeiJyoken__c/fields/NameCardDataType__c.field-meta.xml
<CustomField>
    <fullName>NameCardDataType__c</fullName>
    <label>名刺の項目(データ型)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>String</fullName>
            </value>
            <value>
                <fullName>Boolean</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Double</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Url</fullName>
            </value>
            <value>
                <fullName>Textarea</fullName>
            </value>
            <value>
                <fullName>Datetime</fullName>
            </value>
            <value>
                <fullName>Integer</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
                <isActive>false</isActive>
                <label>Number</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardRenkeiJyoken__c/fields/NameCardName__c.field-meta.xml
<CustomField>
    <fullName>NameCardName__c</fullName>
    <label>名刺の項目(API名称)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardRenkeiJyoken__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <label>演算子</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Matches_next_character_string</fullName>
            </value>
            <value>
                <fullName>Does_not_match_next_character_string</fullName>
            </value>
            <value>
                <fullName>Start_with_the_following_string</fullName>
            </value>
            <value>
                <fullName>Contains_the_following_character_string</fullName>
            </value>
            <value>
                <fullName>Not_contain_the_following_character_string</fullName>
            </value>
            <value>
                <fullName>Matches_the_following_regular_expression</fullName>
            </value>
            <value>
                <fullName>＜</fullName>
            </value>
            <value>
                <fullName>＞</fullName>
            </value>
            <value>
                <fullName>＜＝</fullName>
            </value>
            <value>
                <fullName>＞＝</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardRenkeiJyoken__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>値</label>
    <type>TextArea</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardRenkeiMapping__c/NameCardRenkeiMapping__c.object-meta.xml
<CustomObject>
    <label>名刺連携項目マッピング</label>
    <nameField>
        <displayFormat>RM-{000000}</displayFormat>
        <label>名刺連携項目マッピングNo</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/SmartVisca/main/default/objects/NameCardRenkeiMapping__c/fields/BasicSetting__c.field-meta.xml
<CustomField>
    <fullName>BasicSetting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>名刺基本設定</label>
    <referenceTo>NameCardBasicSetting__c</referenceTo>
    <relationshipLabel>名刺連携項目マッピング</relationshipLabel>
    <relationshipName>BasicSetting</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardRenkeiMapping__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>有効</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardRenkeiMapping__c/fields/NameCardName__c.field-meta.xml
<CustomField>
    <fullName>NameCardName__c</fullName>
    <label>名刺の項目(API名称)</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardRenkeiMapping__c/fields/TargetName__c.field-meta.xml
<CustomField>
    <fullName>TargetName__c</fullName>
    <label>対象の項目(API名称)</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardSettingValues__c/NameCardSettingValues__c.object-meta.xml
<CustomObject>
    <label>名刺設定値</label>
    <nameField>
        <displayFormat>NCSV-{00000}</displayFormat>
        <label>名刺設定値名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/SmartVisca/main/default/objects/NameCardSettingValues__c/fields/Index__c.field-meta.xml
<CustomField>
    <fullName>Index__c</fullName>
    <label>並び順</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardSettingValues__c/fields/TextValue01__c.field-meta.xml
<CustomField>
    <fullName>TextValue01__c</fullName>
    <label>テキスト値01</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/SmartVisca/main/default/objects/NameCardSettingValues__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>種別</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SaishinInherit</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/SmartVisca/main/default/classes/SB_NameCard_BasicSettingUtil.cls
/*
 *
 * SV_DEV-596 連携条件レコードの取得方法を統一
 *
 * Copyright (c) 2017 SunBridge Inc.
 *
 *  @author mao
 *  @Version 1.22      2017.09.XX
 */
public class SB_NameCard_BasicSettingUtil {
  /*
      @param recordType 連携マッピングのレコードタイプ
      @param keySet  検索される項目のSet .... 削除済みの項目は画面に表示しないため、保存の時削除されます
  */
  public static List<NameCardRenkeiMapping__c> getNameCardMapping(String recordType, Set<String> keySet) {
    NameCardBasicSetting__c bb = SB_NameCard_BasicSetting.getNameCardBasicSetting();
    if (keySet == null || keySet.isEMpty()) {
        return [select Id,Name,RecordTypeId,TargetName__c,NameCardName__c,IsActive__c,LastModifiedDate,LastModifiedById,LastModifiedBy.Name,Recordtype.Developername
                                                            from NameCardRenkeiMapping__c Where RecordTypeId = :recordType AND BasicSetting__c =:bb.Id AND BasicSetting__c!= null
                                                            ORDER BY LastModifiedDate Desc limit 10000 ];
    } else {
        return [select Id,Name,RecordTypeId,TargetName__c,NameCardName__c,IsActive__c,LastModifiedDate,LastModifiedById,LastModifiedBy.Name,Recordtype.Developername
                                                            from NameCardRenkeiMapping__c Where RecordTypeId = :recordType AND BasicSetting__c =:bb.Id AND BasicSetting__c!= null
                                                                And TargetName__c IN :keySet
                                                            ORDER BY LastModifiedDate Desc limit 10000 ];
    }
  }
  /*
      連携マッピングメタデータ取得
      @param reid 連携マッピングメタデータのレコードタイプ
  */
  public static List<DefaultRenkeiMapping__mdt> getMappingMetadata(String reid) {
    return [Select ID,TargetName__c,NameCardName__c,IsActive__c,recordtype__c
              From DefaultRenkeiMapping__mdt
              Where recordtype__c = :reid];
  }
  /*
      名刺設定値をセユトク
      @param settingType 名刺設定値タイプ(現在は名刺から引き継ぐ項目とOhter)
  */
  public static List<NameCardSettingValues__c> getSettingValues(String settingType) {
    return [Select Id,Name,TextValue01__c,Type__c From NameCardSettingValues__c Where Type__c = :settingType ORDER BY CreatedDate ASC, index__c];
  }
  /*
      連携条件取得
  */
  public static List<NameCardRenkeiJyoken__c> getNameCardRenkeiJyoken(String rid) {
    if (String.isBlank(rid)) {
      NameCardBasicSetting__c bb = SB_NameCard_BasicSetting.getNameCardBasicSetting();
      return [select Id,Name, NameCardName__c,Operator__c,Value__c,NameCardDataType__c,LastModifiedById,LastModifiedBy.Name,LastModifiedDate
                                                from NameCardRenkeiJyoken__c Where BasicSetting__c=:bb.Id AND BasicSetting__c != null Order By LastModifiedDate Desc
                                                limit 10000 ];
    } else {
      return [select Id,Name, NameCardName__c,Operator__c,Value__c,NameCardDataType__c,LastModifiedById,LastModifiedBy.Name,LastModifiedDate
                                            from NameCardRenkeiJyoken__c Where BasicSetting__c=:rid AND BasicSetting__c != null Order By LastModifiedDate Desc
                                            limit 10000 ];
    }
  }
}